### ISSUE TITLE
How can I commit and install modules separately 

### ISSUE THREAD

**Issue by coding-sunshine** [caffeinated/modules#101]
I wanted to add individual module as package, so I can use them around my multiple projects.
I am not sure how can I achieve this. Do you support composer/installers?

Thanks very much for such amazing package btw. It saves me a lot of time.

**Comment by kaidesu** [comment]
I don't. I intentionally left that out of the package as I believe it should be up to the developer how they wish to manage their modules for their project.

**Comment by coding-sunshine** [comment]
Thanks. I think you are right. I should keep modules on packages separate. Thanks
