### ISSUE TITLE
Speed Improvements

### ISSUE THREAD

**Issue by MrGrygson** [caffeinated/modules#102]
Hey, 
is there any way to cache registration of modules or something that will speed up this component?

Currently we are using about 20 modules and whole process of registering each module each request is slow, even if route caching is on (laravel 5.1).

Debugger shows that response with simple html comes in about 1.5sec, an bootlenecks are when iterrating directories in caffeinated modules.

Any ideas?

**Comment by kaidesu** [comment]
Yes, this is a known issue that I've been trying to work out. Definitely needs some form of caching the registered modules rather than re-scanning and re-registering modules on every page request.

Can reference https://github.com/caffeinated/modules/issues/77 for some more backstory on the matter. I'll keep this issue open though until a solid improvement is put into place.

I'm definitely open to any ideas anyone may have as well~

**Comment by friedlysol** [comment]
Setting 
$defer = true;

Takes the page from loading in 1.2 seconds to 0.25 seconds.

On our api requests this happens

ReflectionException' with message 'Class caffeinated.module does not exist' in /vendor/laravel/framework/src/Illuminate/Container/Container.php:736\\nStack trace:\\n#0 /vendor/laravel/framework/src/Illuminate/Container/Container.php(736): ReflectionClass->__construct('caffeinated.mod...')\\n#1 /vendor/laravel/framework/src/Illuminate/Container/Container.php(626): Illuminate\\\\Container\\\\Container->build('caffeinated.mod...', Array)\\n#2 /vendor/laravel/framework/src/Illuminate/Foundation/Application.php(674): Illuminate\\\\Container\\\\Container->make('caffeinated.mod...', Array)\\n#3 /vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(123): I

I like this deferred loading - what would we need to change to make this work?
Register the middleware somewhere else?

**Comment by friedlysol** [comment]
We've resolved the issue by getting rid of this module. Its a great module - but it turned out we could get away without it. Requests dropped down to 70ms.

**Comment by kaidesu** [comment]
A module or this package?

**Comment by friedlysol** [comment]
Sorry - this package. caffeinated/modules

**Comment by mohamedsharaf** [comment]
@kaidesu  look at this loading
https://github.com/pingpong-labs/modules

**Comment by mohamedsharaf** [comment]
https://github.com/pingpong-labs/modules/blob/master/ModulesServiceProvider.php
