### ISSUE TITLE
Does not handle camelcase module names well

### ISSUE THREAD

**Issue by mattzuba** [caffeinated/modules#103]
I created a module named 'DatabaseLogger', but the slug ended up being created as databaselogger.  It appears that the 'slug' is used for a lot of transformations to determine where things are at, so it was looking for the 'DatabaseloggerServiceProvider' (notice the lowercase 'l'), which didn't work.  When I changed the slug to be databaseLogger, then other things started going wrong because of things it needed the lowercase l for.

**Comment by zorx** [comment]
same thing when you try "hello.world" "hello--world" as a plugin name etc.

to fix all this I've edited the `fire` method in  `src/Console/Commands/ModuleMakeCommand.php`: 
```
public function fire(Command $console, $slug)
{
  $this->console = $console;
  $this->slug    = str_slug($slug, '');
  $this->name    = studly_case($this->slug);
  if ($this->module->exists($this->slug)) {
    $console->comment("Module [{$this->name}] already exists."); // changin ' to "

    return false;
  }

  $this->generate($console);
}
```

**Comment by kaidesu** [comment]
Consolidating this issue with #105.
