### ISSUE TITLE
As you might create modules with 2 words. 

### ISSUE THREAD

**Issue by aculvi** [caffeinated/modules#104]
For example ProfessioalCategories
I miss the artisan 
php module:make professional_categories 
And creates well but to create a migration returns the error.
Module [ProfessionalCategories] unknow

**Comment by kaidesu** [comment]
Consolidating this issue with #105.

**Comment by aculvi** [comment]
I've been able to solve.

First use the version is 1.1.

To do this in the vendor / caffeinated / file modules / src / Caffeinated / Modules / modules.php have changed 2 lines.

In the function getAllSlugs
getAllSlugs protected function ()
{
$ modules = $ this-> all ();
$ slug = array ();

foreach ($ modules as $ module)
{
// $ slugs [] = $ module ['slug'];
                         $ slugs [] = Str :: studly ($ module ['slug']);
}

return $ slugs;
}

And in the function exists
public function exists ($ slug)
{
                 // $ slug = strtolower ($ slug);
                 $ slug = Str :: studly ($ slug);
return in_array ($ slug, $ this-> getAllSlugs ());
}

**Comment by BlueFreakLP** [comment]
Than do a pullrequest ^^
