### ISSUE TITLE
Improve module:make command

### ISSUE THREAD

**Issue by kaidesu** [caffeinated/modules#105]
**This issue is consolidating the issues reported in #103 and #104.**

- [x] Provide a "wizard" to walk through manually setting up the module manifest file. This will be the default behavior. (Example of this would be npm's init command that asks for the name, author, version, etc.)

```
php artisan module:make blog
This wizard will walk you through creating your module's manifest file.
It only covers the most common items, and tries to guess sane defaults.

Press ^C at any time to quit.
name: (Blog) _
slug: (blog) _
version: (1.0.0) _
description: _
author: _
license: (MIT) _
About to write to ~/Code/example/app/Modules/Blog/module.json:

{
    "name": "Blog",
    "slug": "blog",
    "version": "1.0.0",
    "description": "",
    "author": "",
    "license": "MIT",
}

Is this ok? (yes) _
```

- [ ] Provide a "quick" option that may be passed if you wish for the package to auto-generate the manifest values for you (the behavior now). This should be trigger-able by passing `--quick` or `-q` along with the command: `php artisan module:make blog -q`
- [x] May add a `namespace` manifest setting for generating/loading files properly.

**Comment by phillipmadsen** [comment]
Take this a step further and speed up the workflow all in one command

#### Create A Migration? (yes) _
* TableName?
* AddFields? *title:string, excerpt:textarea, content:textarea*

**php artisan module:make:migration blog {TableName} fields="{AddFields}"**

#### Create Another Migration? (yes) _
* TableName? *categories*
* AddFields? *name:string* 

**php artisan module:make:migration blog {categories} fields="{name:string}"**


#### Create Requests? (singular term)(yes) _
* *post category*
 
**php artisan module:make:request blog CreatePostRequest**
**php artisan module:make:request blog CreateCategoryRequest**

#### Create Controllers? (plural term) (yes) _
* *posts categories*

**php artisan module:make:controller blog PostsController**
**php artisan module:make:controller blog CategoriesController**
