### ISSUE TITLE
Where do I store specific css and js for one module?

### ISSUE THREAD

**Issue by rafamds** [caffeinated/modules#108]
I wanted to store each js in the folder of its module, where should I do that? And to load it on the view?

**Comment by kaidesu** [comment]
It'll be the same process as done for package development. You may bundle your assets with your module, but you will need to `publish` them to the `public` directory before they may be used. See here for the documentation on how to accomplish this:

http://laravel.com/docs/5.1/packages#public-assets

**Comment by kaidesu** [comment]
Wrote a wiki page specifically on it as well, which I hope helps:

https://github.com/caffeinated/modules/wiki/Public-Assets

**Comment by rafamds** [comment]
Thanks for your fast answer, it worked as expected.
Cheers.
