### ISSUE TITLE
issue with translate

### ISSUE THREAD

**Issue by mikhi** [caffeinated/modules#111]
Hi,
i have an issue with translate option. I place messages.php file in Resources\Lang directory, and then from module controller i tried:

dd(trans('rbac::messages.page_title'));

This is how it looks the module manifest file:
{
	"name": "rbac",
	"slug": "rbac",
	"version": "1.0",
	"description": "Role-based access control.",
	"enabled": true
}

Any idea what i'am doing wrong?

**Comment by nickurt** [comment]
You placed it into ?

    app/Modules/{Module}/Resources/Lang/{nl|de|en|fr}/

**Comment by mikhi** [comment]
Now works fine.Thanks allot! 
My bad...
