### ISSUE TITLE
Reading from language files placed in sub-directories not working

### ISSUE THREAD

**Issue by marlongichie** [caffeinated/modules#116]
The trans function returns the language line key instead of the value when attempting to read from files located in sub-directories like so:
```
app/Modules/{Module}/Resources/Lang/en/{sub-directory}/file.line
```

and using:
```
echo trans('module::sub-directory.file.line');
```

Note: it works like normal when reading from the base directory.

Would be nice to be able to separate language files that are used for different purposes. 

Anyone else come across this?

**Comment by kaidesu** [comment]
Pretty sure that's a limitation of Laravel itself - my package simply uses the [`loadTranslationsFrom`](http://laravel.com/docs/5.1/packages#translations) method provided by Laravel to register language files bundled with your modules.

On that note though, I've personally never seen anyone split up their language/translation files into subdirectories - should try and group related content together at the root of your locale directory so everything is easy to find when it comes time to manage or add translations.
