### ISSUE TITLE
suggest : multi key "enabled" in module.json

### ISSUE THREAD

**Issue by maengkom** [caffeinated/modules#119]
I am developing a CMS for multisite using this modules. And will modify "enabled" key to used in database, so when editor login, first page will display options which website he need to login, and for different site, could be disable or enable for a module.

I suggest module.json like this 

	"name": "Video",
	"slug": "video",
	"version": "1.0",
	"description": "This is the description for the Video module.",
	"enabled": { 
            "site-A" : true,
            "site-B" : false
        }

I guess this could be used for other case, not only multisite.

**Comment by kaidesu** [comment]
This is well outside the scope of the package - your application should be the one that handles managing multiple sites for your needs.
