### ISSUE TITLE
Action not defined in Blade View

### ISSUE THREAD

**Issue by appdezign** [caffeinated/modules#122]
I have setup Modules in Laravel 5.1 and everything seems to work. Routes, Models, Controller and views: they all work just fine. But when I try to define an action in a blade template te reference a controller I get an exception:

Blade template:

    <a href="{{ action('ArticlesController@show', [$article->id] ) }}">{{ $article->title }}</a>

```
Exception:
ErrorException in UrlGenerator.php line 576: Action App\Http\Controllers\ArticlesController@show not defined. (View: /home/vagrant/Code/lara5/modules/Blog/Resources/Views/articles/index.blade.php)
```

Question:
It seems that Laravel is looking for the controller in App\Http\Controllers instead of modules\Blog\Http\Controllers\.
What am I doing wrong here?

PS - I should mention that I have moved the Module Directory to the root, but like I said: the modules are working just fine, except for referencing the controller from the template.

**Comment by kaidesu** [comment]
Pretty sure you need to specify the full path to the module's controller - otherwise Laravel is going to assume that you're referencing a controller from your base App directory.

**Comment by appdezign** [comment]
It's not a pretty solution, but it works. Thanks.

    <a href="{{ action('\Modules\Blog\Http\Controllers\ArticlesController@show', [$article->id] ) }}">{{ $article->title }}</a>

**Comment by kaidesu** [comment]
Nope, it's not - instead of specifying the action namespace directly, I would use the `route()` helper and specify named routes instead~

http://laravel.com/docs/5.1/routing#named-routes

**Comment by appdezign** [comment]
Ah ... That's a good idea. Thanks again.

**Comment by kaidesu** [comment]
No problem :+1:
