### ISSUE TITLE
make:controller command

### ISSUE THREAD

**Issue by hamrahpay** [caffeinated/modules#123]
hello dear
I opened an issue becuase the pull request is disabled,
It's better to add make:controller and make:model command to modules ,

Best regards

**Comment by hamrahpay** [comment]
Ok , I write this command , and send to pull request , its good to merg to master branch :)

best regards
Ali

**Comment by kaidesu** [comment]
Thanks for the contribution!

In the future, you're able to group all the changes/additions you made into one pull-request instead of multiple ones.

**Comment by hamrahpay** [comment]
Your welcome , yes you're right , in the next time I will made into one pull-request :)
