### ISSUE TITLE
Class not found exception

### ISSUE THREAD

**Issue by developernaren** [caffeinated/modules#13]
I did a fresh installation for this and created a new module with 

`php artisan module:make blog` like in example

    <?php
    namespace App\Http\Controllers\Blog;

    use App\Http\Controllers\Controller;

    class BlogController extends Controller{
    
    function home() {
        
        return "hello";
    }
    }`

This is my blog controller inside the module

and this is my route file

    Route::group(['prefix' => 'blog'], function() {
	Route::get('/', function() {
		dd('This is the Blog module index page.');
	});
        
        get('/home','Blog\BlogController@home');
    });`

but when i hit blog/home i get this `Blog\BlogController not found error`

what am I missing?
am i supposed to include any folder for autoload?

**Comment by kaidesu** [comment]
You're referencing your blog controllers namespace incorrectly in your routes file. It should be `App\Http\Controllers\Blog\BlogController@home`.

**Comment by developernaren** [comment]
I tried that still not working

`get('/home','App\Http\Controllers\Blog\BlogController@home');`

this is code in my route file but this is still not working

**Comment by kaidesu** [comment]
Sorry, I didn't notice it earlier, but it looks like you're misusing the route get method, you should have the following:

```php
Route::group(['prefix' => 'blog'], function() {
	Route::get('/', function() {
		dd('This is the Blog module index page.');
	});

	Route::get('home', 'App\Http\Controllers\Blog\BlogController@home');
});
```

**Comment by developernaren** [comment]
still not working..I think `Route::get` and `get` are the same in laravel 5. So I still do not think that it is the issue.

![error](https://cloud.githubusercontent.com/assets/3628468/5700307/164050ba-9a64-11e4-9f03-dcdd54347ff5.png)

This is my folder structure and you have seen the content. Is there anything else that I need to provide to make this easier to fix

**Comment by kaidesu** [comment]
The only thing that I can think of off the top of my head at the moment is to make sure you've added the modules package service provider to your app config file. This is the file that will autoload all of your modules.

**Comment by developernaren** [comment]
this is the facade
    'Form'  => 'Illuminate\Html\FormFacade',
        'HTML'  => 'Illuminate\Html\HtmlFacade',
        'Module' => 'Caffeinated\Modules\Facades\Module'        

and this is the serviceProvider
    'App\Providers\EventServiceProvider',
        'App\Providers\RouteServiceProvider',
        'Caffeinated\Modules\ModulesServiceProvider'

**Comment by kaidesu** [comment]
I just installed a clean version of Laravel 5 - here is my blog controller and routes file for reference:

**Controller**
```php
<?php
namespace App\Modules\Blog\Http\Controllers;

use App\Http\Controllers\Controller;

class BlogController extends Controller
{
	public function home()
	{
		dd('Hello World! This is the Blog Home method!');
	}
}

```

**Routes**
```php
<?php

/*
|--------------------------------------------------------------------------
| Module Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for the module.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the Closure to execute when that URI is requested.
|
*/

Route::group(['prefix' => 'blog'], function() {
	Route::get('/', function() {
		dd('This is the Blog module index page.');
	});

	Route::get('home', 'App\Modules\Blog\Http\Controllers\BlogController@home');
});
```

Cross reference and double check your namespaces.

![Screenshot](http://i.imgur.com/zbB5CWt.png)

**Comment by developernaren** [comment]
This is working for me too. Seems like the namespace that I am using is not working, I checked the namespace and tried to work it but it is just not working, I will use the way that you suggested, I will use the namespace just like yours.
Thanks for a great modules and for the help with this issue :)

**Comment by kaidesu** [comment]
No problem, glad your issue is resolved. Now go code something awesome!
