### ISSUE TITLE
module:make problem

### ISSUE THREAD

**Issue by alainbelez** [caffeinated/modules#130]
i use `composer require caffeinated/modules` and it installed `version 2.1.10`

problem is if i do a `php artisan module:make TestModule` or any camelCase or PascalCase module name it will throw and error in the browser
~~~
Fatal error: Class 'App\Modules\Testmodule\Providers\TestmoduleServiceProvider' not found
~~~

**Comment by kaidesu** [comment]
This will be resolved with v3.0~ Re-writing the `module:make` command and adding a new namespace manifest key.
