### ISSUE TITLE
Extract generators into their own service provider

### ISSUE THREAD

**Issue by kaidesu** [caffeinated/modules#133]
All current `module:make` commands should be extracted out to their own service provider to make management of them easier. This includes:

- `module:make`
- `module:make:controller`
- `module:make:request`
- `module:make:migration`

**Comment by kaidesu** [comment]
Generators will follow the convention of using `make` as the first keyword:

- `make:module`
- `make:module:controller`
- `make:module:request`
- `make:module:migration`

**Comment by vdjkelly** [comment]
make:module:controller No existe y module:make:controller No existe

Fix hecho por mi no se si este bien o mal 


controller.stub

cambien 

namespace {{namespace}}\{{moduleName}}\Http\Controllers;

por 

namespace {{namespace}}\{{name}}\Http\Controllers;

crear archivo MakeControllerCommand.php en Generators 


<?php namespace Caffeinated\Modules\Console\Generators;

use Caffeinated\Modules\Modules;
use Illuminate\Console\Command;
use Illuminate\Filesystem\Filesystem;
use Illuminate\Support\Str;
use Symfony\Component\Console\Input\InputArgument;


class MakeControllerCommand extends Command {

  /**
   * The console command name.
   *
   * @var string
   */
  protected $name = 'make:module:controller';

  /**
   * The console command description.
   *
   * @var string
   */
  protected $description = 'Create a new module controller class';

  /**
   * Array to store the configuration details.
   *
   * @var array
   */
  protected $container;

  /**
   * Create a new command instance.
   *
   * @param Filesystem  $files
   * @param Modules  $module
   */
  public function __construct(Filesystem $files, Modules $module)
  {
      parent::__construct();

      $this->files  = $files;
      $this->module = $module;
  }


  /**
	 * Execute the console command.
	 *
	 * @return mixed
	 */
	public function fire()
	{

    $this->container['slug']  = $this->argument('slug');
    $this->container['name']      = Str::studly($this->argument('slug'));

    $this->container['className']     = studly_case($this->argument('className'));

    if ($this->module->exists($this->container['slug'])) {
        $this->makeFile();

        $this->info('Create Module Migration: '.$this->getFilename());

        return exec('composer dump-autoload');
    }

    return $this->info('Module does not exist.');

	}

  protected function makeFile()
  {
      return $this->files->put($this->getDestinationFile(), $this->getStubContent());
  }



      /**
       * Get file destination.
       *
       * @return string
       */
      protected function getDestinationFile()
      {
          return $this->getPath().$this->formatContent($this->getFilename());
      }

      /**
       * Get module migration path.
       *
       * @return string
       */
      protected function getPath()
      {
          $path = $this->module->getModulePath($this->container['slug']);

          return $path.'Http/Controllers/';
      }

      /**
       * Get the migration filename.
       *
       * @return string
       */
      protected function getFilename()
      {
          return $this->container['className'].'.php';
      }

      /**
       * Get the stub content.
       *
       * @return string
       */
      protected function getStubContent()
      {
          return $this->formatContent($this->files->get(__DIR__.'/../../../resources/stubs/controller.stub'));
      }

      /**
  	 * Replace placeholder text with correct values.
  	 *
  	 * @return string
  	 */
  	protected function formatContent($content)
      {

        return str_replace(
    			['{{className}}', '{{name}}', '{{namespace}}'],
    			[$this->container['className'], $this->container['name'], $this->module->getNamespace()],
    			$content
    		);

      }

      /**
       * Get the console command arguments.
       *
       * @return array
       */
      protected function getArguments()
      {
        return [
    			['slug', InputArgument::REQUIRED, 'The slug of the module'],
    			['className', InputArgument::REQUIRED, 'The name of the class']
    		];
      }


}
