### ISSUE TITLE
Event listeners

### ISSUE THREAD

**Issue by avramovic** [caffeinated/modules#135]
First of all: I'm already using your themes package and it seems like I'm keeping it in my project as I like it so far.

Now, I'm looking to provide modules (or plugins) support in my application, similarly like Wordpress' "hook" based system. Translated into Laravel world, it seems it would be something like events (provided by my application) and event listeners (provided by plugins/modules). Correct me if I'm wrong, I'm still new to Laravel.

Is it possible to achieve something like this with your modules package? And if not, do you plan to implement something like that? Or do you maybe have idea how to achieve this?

For example when user creates a new account with my application I want to set up a hook (event) so any module can respond and do whatever it wants with newly registered user.

**Comment by kaidesu** [comment]
Yup, and in fact that functionality is already built into the core of Laravel itself:

http://laravel.com/docs/5.1/events

You're able to make full use of events within your modules as well. There's excellent screencasts on Laracasts if you'd like to learn more about Laravel's Event system~

https://laracasts.com/series/intermediate-laravel/episodes/3

Hope this helps, and glad to hear the themes package is useful!

**Comment by avramovic** [comment]
Thanks for your reply. After watching the video you linked, and a bit of playing I managed to register my custom event service provider (MyEventServiceProvider) within test module's service provider, and make custom event listener which was triggered from base application. This is great!

btw. It would be cool if you created dummy EventServiceProvider when the module is first created, and also something like module:make:listener for Artisan :) I would like to help, but as I said I'm still new to Laravel so I'm not sure where to start.
