### ISSUE TITLE
Autoload for module migration structures

### ISSUE THREAD

**Issue by dakiesse** [caffeinated/modules#137]
Hi! I have module with name ```ClientageApp``` that contain in path ```app/Modules/ClientageApp``` with namespace ```App/Modules/ClientageApp```.
I create migration for that model via ```module:make:migration clientage_app create_something_table```.

The problem is that the autload know nothing about file in the folder app/Modules/ClientageApp/Database/Migrations, since the file names do not correspond to the PSR-0/4. Because of what the the command ```module:migrate:rollback``` works with the error ``` Class 'CreateSomethingTable' not found```.

**Comment by TerrePorter** [comment]
Try running 'composer dump-autoload', after creating the migration file
