### ISSUE TITLE
Laravel 5.2

### ISSUE THREAD

**Issue by jimmck** [caffeinated/modules#140]
Is Laravel 5.2 supported?  Did a install test of 5.2 and got version errors on update.  Nice work.

**Comment by kaidesu** [comment]
It's in the works - the current master branch has 5.2 support but I have other updates coming down the pipeline that will be bundled with it. See here for more information: http://caffeinated.ninja/blog/news/changes-to-packages

I'll leave this issue open until the next release is tagged.

**Comment by BartReymenants** [comment]
still impossible to install v2.1 on Laravel 5.2.6
when is Milestone v3.0 coming up?
greatly appreciated

**Comment by ruelluna** [comment]
+1

**Comment by theomessin** [comment]
+1

**Comment by MattDaviesHD** [comment]
+1

**Comment by KieronMeen** [comment]
+1

**Comment by antho-firuze** [comment]
+1

**Comment by alexeitav** [comment]
+1

**Comment by smartniazi** [comment]
+1

**Comment by appdezign** [comment]
+1

**Comment by yamilrevilla** [comment]
+1

**Comment by kaidesu** [comment]
It's coming guys! Sorry for the wait; getting out of the bouts of a coding burnout so I will jump back into things again shortly. Thanks for your patience~

**Comment by Dijir** [comment]
+1

**Comment by WoLfulus** [comment]
+1
