### ISSUE TITLE
module:migrate failed

### ISSUE THREAD

**Issue by uemaen** [caffeinated/modules#143]
Hi kaidesu,

got following Error with module:migrate
"Argument 2 passed to Illuminate\Database\Migrations\Migrator::run() must be of the type array, boolean given, called in D:\TTOS2\www\vendor\caffeinated\modules\src\Console\Commands\ModuleMigrateCommand.php on line 98 and defined"

so i added at line 97 $pretend = array($pretend);
with this change module:migrate works again.

"laravel/framework": "5.2.*" (Laravel 5.2.10)
"caffeinated/modules":"3.0.x-dev"

best regards
uemaen

**Comment by heikobihlmaier** [comment]
Same error here.

@kaidesu: Can u correct this ?

+1

**Comment by TerrePorter** [comment]
That is likely because the code is not yet compatible with laravel 5.2, see https://github.com/caffeinated/modules/issues/140
