### ISSUE TITLE
Error install laravel 5.2

### ISSUE THREAD

**Issue by allanjhonne** [caffeinated/modules#145]
D:\Servidor\laragon\www\projetos\codecoursers>composer require caffeinated/modules
Reading composer.json of alanoliver/modules (master)
Skipped branch master, Could not parse version constraint ^1.1.*: Invalid version string "^1.1.*"

Using version ^2.1 for caffeinated/modules
./composer.json has been updated
> php artisan clear-compiled
Loading composer repositories with package information
Reading composer.json of alanoliver/modules (master)
Skipped branch master, Could not parse version constraint ^1.1.*: Invalid version string "^1.1.*"

Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Conclusion: remove laravel/framework v5.2.11
    - Conclusion: don't install laravel/framework v5.2.11
    - caffeinated/modules v2.1 requires illuminate/routing 5.1.* -> satisfiable by illuminate/routing[v5.1.1, v5.1.13, v5.1.16, v5.1.2, v5.1.20, v5.1.22, v5.1.25, v5.1.28, v5.1.6, v5.1.8].
    - caffeinated/modules v2.1.1 requires illuminate/routing 5.1.* -> satisfiable by illuminate/routing[v5.1.1, v5.1.13, v5.1.16, v5.1.2, v5.1.20, v5.1.22, v5.1.25, v5.1.28, v5.1.6, v5.1.8].
    - caffeinated/modules v2.1.10 requires illuminate/routing 5.1.* -> satisfiable by illuminate/routing[v5.1.1, v5.1.13, v5.1.16, v5.1.2, v5.1.20, v5.1.22, v5.1.25, v5.1.28, v5.1.6, v5.1.8].
    - caffeinated/modules v2.1.11 requires illuminate/routing 5.1.* -> satisfiable by illuminate/routing[v5.1.1, v5.1.13, v5.1.16, v5.1.2, v5.1.20, v5.1.22, v5.1.25, v5.1.28, v5.1.6, v5.1.8].
    - caffeinated/modules v2.1.2 requires illuminate/routing 5.1.* -> satisfiable by illuminate/routing[v5.1.1, v5.1.13, v5.1.16, v5.1.2, v5.1.20, v5.1.22, v5.1.25, v5.1.28, v5.1.6, v5.1.8].
    - caffeinated/modules v2.1.3 requires illuminate/routing 5.1.* -> satisfiable by illuminate/routing[v5.1.1, v5.1.13, v5.1.16, v5.1.2, v5.1.20, v5.1.22, v5.1.25, v5.1.28, v5.1.6, v5.1.8].
    - caffeinated/modules v2.1.4 requires illuminate/routing 5.1.* -> satisfiable by illuminate/routing[v5.1.1, v5.1.13, v5.1.16, v5.1.2, v5.1.20, v5.1.22, v5.1.25, v5.1.28, v5.1.6, v5.1.8].
    - caffeinated/modules v2.1.5 requires illuminate/routing 5.1.* -> satisfiable by illuminate/routing[v5.1.1, v5.1.13, v5.1.16, v5.1.2, v5.1.20, v5.1.22, v5.1.25, v5.1.28, v5.1.6, v5.1.8].
    - caffeinated/modules v2.1.6 requires illuminate/routing 5.1.* -> satisfiable by illuminate/routing[v5.1.1, v5.1.13, v5.1.16, v5.1.2, v5.1.20, v5.1.22, v5.1.25, v5.1.28, v5.1.6, v5.1.8].
    - caffeinated/modules v2.1.7 requires illuminate/routing 5.1.* -> satisfiable by illuminate/routing[v5.1.1, v5.1.13, v5.1.16, v5.1.2, v5.1.20, v5.1.22, v5.1.25, v5.1.28, v5.1.6, v5.1.8].
    - caffeinated/modules v2.1.8 requires illuminate/routing 5.1.* -> satisfiable by illuminate/routing[v5.1.1, v5.1.13, v5.1.16, v5.1.2, v5.1.20, v5.1.22, v5.1.25, v5.1.28, v5.1.6, v5.1.8].
    - caffeinated/modules v2.1.9 requires illuminate/routing 5.1.* -> satisfiable by illuminate/routing[v5.1.1, v5.1.13, v5.1.16, v5.1.2, v5.1.20, v5.1.22, v5.1.25, v5.1.28, v5.1.6, v5.1.8].
    - don't install illuminate/routing v5.1.1|don't install laravel/framework v5.2.11
    - don't install illuminate/routing v5.1.13|don't install laravel/framework v5.2.11
    - don't install illuminate/routing v5.1.16|don't install laravel/framework v5.2.11
    - don't install illuminate/routing v5.1.2|don't install laravel/framework v5.2.11
    - don't install illuminate/routing v5.1.20|don't install laravel/framework v5.2.11
    - don't install illuminate/routing v5.1.22|don't install laravel/framework v5.2.11
    - don't install illuminate/routing v5.1.25|don't install laravel/framework v5.2.11
    - don't install illuminate/routing v5.1.28|don't install laravel/framework v5.2.11
    - don't install illuminate/routing v5.1.6|don't install laravel/framework v5.2.11
    - don't install illuminate/routing v5.1.8|don't install laravel/framework v5.2.11
    - Installation request for laravel/framework == 5.2.11.0 -> satisfiable by laravel/framework[v5.2.11].
    - Installation request for caffeinated/modules ^2.1 -> satisfiable by caffeinated/modules[v2.1, v2.1.1, v2.1.10, v2.1.11, v2.1.2, v2.1.3, v2.1.4, v2.1.5, v2.1.6, v2.1.7, v2.1.8, v2.1.9].

Installation failed, reverting ./composer.json to its original content.

**Comment by kaidesu** [comment]
Please see #140 - Laravel 5.2 support is still being worked on~
