### ISSUE TITLE
'ReflectionException' with message 'Class translator does not exist' 

### ISSUE THREAD

**Issue by mitajunior** [caffeinated/modules#147]
Am trying to use your package but i get this error...after creating the module do i need to add it in my list of service providers?

**Comment by samwilson** [comment]
This is probably a long shot, but I've seen this error come up (as have [others](https://laracasts.com/discuss/channels/general-discussion/reflectionexception-class-log-does-not-exist-in-homevagrantcode/replies/127424)) when including spaces in unquoted `.env` variables. Do you have any of them?

**Comment by mitajunior** [comment]
No i dont have such instances

**Comment by samwilson** [comment]
Not sure where to look then.

I assume `composer update` has completed without error? it's odd that it's a lowercase 't' in 'translator', as usually a class would be referred to in CamelCase.

I'm sure someone will know more than me! :)
