### ISSUE TITLE
The migration always run with pretend option true

### ISSUE THREAD

**Issue by SherifElfadaly** [caffeinated/modules#149]
Hey,

Any migration run with pretend option true result on returning the sql rather than creating the tables, the problem in this line : `$pretend = array(Arr::get($this->option(), 'pretend', false));`. Removing the array fixed the issue.

**Comment by kaidesu** [comment]
What version of Laravel are you using?

There was a bug with the migration (which I fixed here a380bf3e7cd9385fb2e828824464bcdf8cc0ecec), but a different one than you've explained.

**Comment by mikhi** [comment]
Hi,
same for me after updating the package with composer update command. i'm using L5.1

**Comment by kaidesu** [comment]
should be good to go now in v2.2.2
