### ISSUE TITLE
Modules only as needed

### ISSUE THREAD

**Issue by mreschke** [caffeinated/modules#15]
Hi Kai,

I have been worried about Laravel workbenches since Taylor removed them from Laravel 5.0.  I was using workbenches for something they were never really intended to be used as; modules.  Basically my CMS allows users to create "apps" on the fly, these apps are actually workbenches.  Now users can code "apps" in true Laravel, which was the entire point because we all love Laravel.  My CMS has a custom URL parser with a Mysql router table, if the route has a "app" tied to it, only then do I actually Add the apps workbench service provide, mod the views path...actually fire up the "app".  This allows me to have thousand of workbenches (apps) that are ONLY registered when needed based on the url...very efficient.  

Your new modules project looks like a perfect replacement to exactly what I need and I was wondering how it works with thousands of modules.  Are all 1000 registered always, or only as needed and can I take control of when they are registered (via URL analysis) instead of your module.json file ??

**Comment by kaidesu** [comment]
At the moment, all modules are registered at run-time. I do want to add other methods of scanning/registering modules in a configurable manner though, but haven't given it much thought.

I'd be open to any suggestions/ideas/pull-requests you may have though! Right now I don't know when I'll get around to looking at this specific functionality.

**Comment by kaidesu** [comment]
@mreschke, One thing I did forget to mention (that I just thought of now going through all the issues here), is that you *can* disabled modules through the module's manifest file (module.json). Disabling the module will *not* load the module at run-time within your application.

You can dynamically update the manifest file as well through the use of the facade method `Module::setProperty()`:

To disable the "blog" module:
```php
Module::setProperty('blog::enabled', false);
```

To enable the "blog" module:
```php
Module::setProperty('blog::enabled', true);
```

Is this the type of functionality you were wanting?

**Comment by torrentalle** [comment]
Is possible to choose wich modules are loaded on boot. Simply enable or disable modules on the AppServiceProvider of yor application

**/app/Providers/AppServiceProvider.php**

````
<?php namespace App\Providers;

use Illuminate\Support\ServiceProvider;

class AppServiceProvider extends ServiceProvider {

	/**
	 * Bootstrap any application services.
	 *
	 * @return void
	 */
	public function boot()
	{
		//
	}

	/**
	 * Register any application services.
	 *
	 * This service provider is a great spot to register your various container
	 * bindings with the application. As you can see, we are registering our
	 * "Registrar" implementation here. You can add your own bindings too!
	 *
	 * @return void
	 */
	public function register()
	{
		$this->app->bind(
			'Illuminate\Contracts\Auth\Registrar',
			'App\Services\Registrar'
		);

        $this->app->booting( function ($app) {
            \Module::disable('blog');
        } );
	}

}

````
Then you can mantain a repository (database, storage, ...) of modules to load at run-time.
