### ISSUE TITLE
Using Artisan::call() for create a module

### ISSUE THREAD

**Issue by UnderlineWords** [caffeinated/modules#150]
I'm using backend side for create a module in my application.
(type a module name in an input text then controller calls `make:module` command)

`Artisan::call('make:module', ['name' => $request->name]);`

But i can't create a module in my application's backend since the last updates. Any suggestion?

**Comment by kaidesu** [comment]
Hmm, I actually hadn't considered this functionality before. I'll add a `--quick` option that you can pass through that will tell the package to replicate the previous versions behavior of auto-filling the manifest information.

**Comment by UnderlineWords** [comment]
Great, thanks :) :+1:

**Comment by kaidesu** [comment]
This was added in the v3.0 release (`--quick` or `-Q`)! Specifically 372783e65564d47a03d011050d4db3f0d0a87342

**Comment by UnderlineWords** [comment]
Thanks for update :+1: 

_Usage after the update :_
```php
Artisan::call('make:module', ['slug' => $request->name, '--quick' => true]);
// or ['--Q' => true]
```

**Comment by alhassancse** [comment]
Command "make:module" is not defined.

at Application->find('make:module')
in Application.php line 229


Help me

**Comment by rylxes** [comment]
@alhassancse , this happens in all caffinated module commands, still no fix
