### ISSUE TITLE
The migration run as pretend

### ISSUE THREAD

**Issue by mikhi** [caffeinated/modules#151]
Hi, 
i think that any migration run with pretent option true. I use L.5.1

This is my migration response, after runnig the command:  
alter table `suppliers_invoices` add `deductible` double(5, 2) not null after `tax_value`

**Comment by mikhi** [comment]
Hello @kaidesu 
can you please help me solving this issue when running migrations?

Thanks,
Mikhi

**Comment by mikhi** [comment]
@kaidesu i found the issue in the Migrator.php file, method runUp line131.
 `if ($pretend) {
   return $this->pretendToRun($migration, 'up');
}`
variable pretend is an array. Please change this into $pretend['pretend'] or something appropiate.

Thanks,
Mikhi

**Comment by kaidesu** [comment]
Thanks for the find - I'll get this patched in a few minutes~

**Comment by kaidesu** [comment]
should be good to go now in v2.2.2
