### ISSUE TITLE
route strange behavior

### ISSUE THREAD

**Issue by geo903** [caffeinated/modules#153]
Hello! I noticed strange behavior. If the application is configured to rout all URL application module intercepts route. How can I change this behavior?

\app\Http\routes.php
`Route::any('{url}', 'FrontController@showPage')->where('url', '.*');`

```
Route::group(['prefix' => 'admin'], function() {
	Route::get('/', function() {
		dd('This is the Admin module index page.');
	});
});
```

**Comment by kaidesu** [comment]
Routing and module ordering is important. In your case, you need to be sure that your catch-all route comes absolutely last. Laravel will fire off the first route match it finds when going through the collection of routes in your application.
