### ISSUE TITLE
module:migrate does not work

### ISSUE THREAD

**Issue by sebastienheyd** [caffeinated/modules#155]
When I run `php artisan module:migrate mymodule` I have this error message :

`[ErrorException]                                                                                                                                                                 
Argument 2 passed to Illuminate\Database\Migrations\Migrator::run() must be of the type array, boolean given, called in /pathtomywebsite/vendor/caffeinated/modules/src/Console/Commands/ModuleMigrateCommand.php on line 99 and defined
`

dd() said that $pretend = false, but migrator->run() ask for an array as second argument.

Putting an `if($pretend === false) $pretend = [];` will fix the error, but this is certainly not very clean.

**Comment by kaidesu** [comment]
What version of Laravel are you running?

**Comment by sebastienheyd** [comment]
Laravel 5.2

**Comment by kaidesu** [comment]
Give v.2.2.4 a go~

For some background information, the migrator parameters were changed from Laravel 5.1 and Laravel 5.2:

- **Laravel 5.1 Migrator:** `run( string $path, bool $pretend = false)`
- **Laravel 5.2 Migrator:** `run( string $path, array $options = array())`

Caffeinated Modules v2.2.4 checks the current version of Laravel and will pass the correct parameter through.
