### ISSUE TITLE
factories inside modules

### ISSUE THREAD

**Issue by m-behr** [caffeinated/modules#156]
Hi! :)
Does someone know a (better) way to integrate module-specific factories ?
Currently we load them via 

```php
$factory->load('app/Modules/<Module>/Database/Factories');
...
# other $factory->define( ... )
```

in <pre>app/database/factories/ModelFactory.php</pre>

perhaps a location that belongs to the module folder structure itself ..

Thanks in advance,
Michael

**Comment by gerardreches** [comment]
Actually I'm using this:
```php
foreach(Module::enabled() as $active_module){
	$factory->load('app/Modules/'.$active_module->get('name').'/Database/Factories');
}
```
I'm searching a way to load module factories without the *ModelFactory.php* file, but I can't find from where is loaded.
