### ISSUE TITLE
Undefined index: namespace

### ISSUE THREAD

**Issue by adamzwakk** [caffeinated/modules#158]
Hey there,

I'm getting the error 

`Undefined index: namespace `

When I try to run artisian commands, they don't seem to happen with 2.1.11. Is there some kind of upgrade procedure I'm missing?

I saw the added

```
'paths' => [
        'core' => [
            'namespace' => 'App\Modules\\',
            'path'      => app_path('Modules')
        ]
    ],
```
in the new version, but adding it didn't seem to help anything.

Any ideas?

**Comment by SquallX** [comment]
Hey

I have the same problem since 2 days, I've tried to update my composer.jspon and to dump autoload but without success. If anybody has an idea I get !

Thanks.

**Comment by kaidesu** [comment]
Hm, I've never run into this issue before. The `paths` key in the config file wasn't supposed to be there - it's been removed in v3.0 (which I released yesterday).

What versions of Laravel and of the package are you running?

**Comment by adamzwakk** [comment]
I'm running Laravel 5.1.*

packages currently are

"laravel/framework": "5.1.*",
        "mcamara/laravel-localization": "1.0.*",
        "caffeinated/modules": "~2.0",
        "barryvdh/laravel-debugbar": "^2.0",
        "intervention/image": "^2.3",
        "cviebrock/eloquent-sluggable": "^3.1",
        "nicolaslopezj/searchable": "1.*",
        "firebase/php-jwt": "^3.0",
        "guzzlehttp/guzzle": "^6.1",
        "pulkitjalan/geoip": "2.*"

**Comment by kurganskiy** [comment]
I`ve the same problem. How to solve this problem? laravel 5.1

**Comment by kurganskiy** [comment]
I fixed this issue by adding "namespace" property to module.json.

`{
	"name": "Core",
	"slug": "core",
	"version": "1.0",
	"description": "This is the description for the Core module.",
	"enabled": true,
	"namespace": "Core"
}`

**Comment by SquallX** [comment]
@kurganskiy Thanks, it works for me too =)

**Comment by oLDu67** [comment]
i'm getting the error when `php artisan module:seed`
i'm running Laravel 5.3.*

composer.json

```
    "require": {
        "php": ">=5.6.4",
        "laravel/framework": "5.3.*",
        "barryvdh/laravel-debugbar": "^2.2",
        "zizaco/entrust": "5.2.x-dev",
        "laravelcollective/html": "5.3.*",
        "caffeinated/themes": "^3.0",
        "arcanedev/log-viewer": "^3.10",
        "rinvex/repository": "2.0.*",
        "caffeinated/modules": "^4.0"
    },
```

**Comment by oLDu67** [comment]
ı solve my seed error DatabaseSeeder  replace ModuleNameDatabaseSeeder and add to the file namespace.
