### ISSUE TITLE
module:make & namespace

### ISSUE THREAD

**Issue by v0k1c** [caffeinated/modules#159]
Is there a step that I am maybe missing? Everything seems correctly installed, config published, and yet when I run

`php artisan make:module Test`

namespaces for generated files stay like this:

`namespace {{path}}\and\the\rest\which\is\correct;`

Seems like {{path}} is not being correctly replaced. At least in my instance. So, for example when I change format function in:

`vendor/caffeinated/modules/src/Console/Generators/MakeModuleCommand.php`

to:

```
	/**
	 * Replace placeholder text with correct values.
	 *
	 * @return string
	 */
	protected function formatContent($content)
	{
		return str_replace(
			['{{slug}}', '{{name}}', '{{namespace}}', '{{version}}', '{{description}}', '{{author}}', '{{license}}', '{{path}}'],
			[$this->container['slug'], $this->container['name'], $this->container['namespace'], $this->container['version'], $this->container['description'], $this->container['author'], $this->container['license'], $this->module->getNamespace()],
			$content
		);
	}
```

(notice added {{path}} replacement from default function) it starts making namespaces correctly. Not sure if someone already reported this or not. Did a quick scan of closed issues, didn't find it. Maybe didn't search hard enough. So, a bug possibly? Let me know, because I would hate the need to extend/overwrite this package. Actually might end up forking it anyway for our purposes, but that is another story. Thanks in advance.

**Comment by kaidesu** [comment]
Definitely a bug - thanks for reporting~ I'll have this patched shortly.

No closed issue on this, but there is an open one for the same issue found here: https://github.com/caffeinated/modules/issues/158
