### ISSUE TITLE
Request make:module:controller --resource

### ISSUE THREAD

**Issue by theomessin** [caffeinated/modules#160]
Should do whatever make:controller --resource does, but for a module controller!

**Comment by ZelimDamian** [comment]
+1
Get the following when try doing this
```
  [Symfony\Component\Console\Exception\RuntimeException]  
  The "--resource" option does not exist.

**Comment by michail1982** [comment]
+1

**Comment by www666** [comment]
+1

**Comment by tkzaum10** [comment]
You can change the stub to create the full controller without the resouce option 

https://gist.github.com/tkzaum10/d950905f10748b7ef88ba4e08d578dac

If you dont need one of the functions then you can comment it out or dont add the route =D

**Comment by gerardreches** [comment]
@kaidesu Already implemented too, right?

**Comment by michail1982** [comment]
yeap https://github.com/caffeinated/modules/blob/master/src/Console/Generators/MakeControllerCommand.php#L68
