### ISSUE TITLE
Artisan command do not consider namespace

### ISSUE THREAD

**Issue by ChristianGiupponi** [caffeinated/modules#164]
When I create the first module I set the namespace to `MyCompany\Core\Settings` and it compiled the filed.  
The module was created but the `namespace` is ignored, it create the `Settings` module in `app/Modules` not in `app/Modules/MyCompany/Core`.

Same for  `php artisan make:module:migration blog create_posts_table` it tried to create the migration in `app/Modules/Settings` ignoring the namespace

**Comment by kaidesu** [comment]
Thanks for the report~ this was also brought up in issue #157
