### ISSUE TITLE
Continuous "[ERROR] Aborted" during php artisan make:module

### ISSUE THREAD

**Issue by gerardreches** [caffeinated/modules#165]
Hi,

I was creating my first module with `php artisan make:module core` and during the process it has begun to show this error like crazy without tap a single key.

![screenshoot](https://cloud.githubusercontent.com/assets/7549815/13963223/d7203ad2-f064-11e5-9425-d4222290daf6.JPG)

**Comment by gerardreches** [comment]
Begins to appear everytime you takes several seconds to move to the next configuration step. I have to manually close the command line everytime this happens.

**Comment by kaidesu** [comment]
What version of Laravel and of the package are you using?

**Comment by gerardreches** [comment]
Laravel 5.2 and Caffeinated/modules ~2.0

**Comment by gerardreches** [comment]
Still happening in version ^3.0

**Comment by kaidesu** [comment]
I'm unsure of what could be causing this. If you could, it'd be helpful to get a breakdown of the steps you took leading up to the error with a clean install of Laravel.

**Comment by gerardreches** [comment]
Created a fresh project and installed the package. The error persists on **git bash** for windows. Error not showing in the default windows cmd.
