### ISSUE TITLE
Module structure documentation doesn't match with new module structure

### ISSUE THREAD

**Issue by gerardreches** [caffeinated/modules#168]
The **Module Structure** section in the documentation tells about a *Config* folder inside the module structure, but my modules haven't this.
![captura2](https://cloud.githubusercontent.com/assets/7549815/14032509/a6825030-f213-11e5-90bb-a43727abf918.JPG)
![captura](https://cloud.githubusercontent.com/assets/7549815/14032516/acf8621a-f213-11e5-9209-186c322e8ff5.JPG)

**Comment by gerardreches** [comment]
I modified the Wiki page to correct this.

**Comment by kaidesu** [comment]
Thanks man! :+1:
