### ISSUE TITLE
There is no seed generator for modules

### ISSUE THREAD

**Issue by gerardreches** [caffeinated/modules#169]
Already exists a `make:module:migration` but not a `make:module:seed` artisan command. Can this be added as an enhancement in the future?

**Comment by tkzaum10** [comment]
It's a great idea @gerardreches i would appreciate it.

**Comment by tkzaum10** [comment]
@gerardreches @kaidesu 
Hey guys i made a command for making models im sharing it with the stub on this gist.

https://gist.github.com/tkzaum10/4bb6caac8308b63b8ea2bb1b61374323

**Comment by tkzaum10** [comment]
@gerardreches @kaidesu 
Command for seed also here with the stub
https://gist.github.com/tkzaum10/48a5607af0a52b0648414305575126b0

Thanks for the module i'll keep helping when i have some time

**Comment by gerardreches** [comment]
@kaidesu This enhancement is already implemented, right?

**Comment by kaidesu** [comment]
@gerardreches Yup! You're right~ Thanks for pointing this out!
