### ISSUE TITLE
Module not loading

### ISSUE THREAD

**Issue by TheTechnoMan** [caffeinated/modules#17]
Hello,

i have created a module, enabled it, put a dd('Test') in the ServiceProvider and did a dump-autoload.

However, it does not seem to load the module. Also the routes are not accessible, so it is surely not loading the module.What am I doing wrong? 

Thanks

**Comment by kaidesu** [comment]
Sounds like you need to register the packages service provider and facade classes in your app config file.

**Comment by TheTechnoMan** [comment]
Oh, i thought the package does that automatically. Is there a way to automate that? I was using L4 before and everything was automated there (with the module package). I want to develop some modules for end users and it would be not that nice if they need to manually dig around in the code.

Thanks

**Comment by TheTechnoMan** [comment]
Just saw that it tries to automatically register the service-provider for the specified slug. It would still be much more flexible if you could make it so that it uses the json file to get the service.providers which it should register. You could make it so that, when you create a module (with the artisan command) it automatically adds the default service provider to the JSON file.

**Comment by kaidesu** [comment]
I'm a little confused by what you mean. You would register any additional service providers you may have for your module through the modules service provider.

e.g., say you have a Users module - you would have a **UsersServiceProvider.php** service provider generated and autoloaded for you. You could then register additional service providers within the `register` method, like so:

```php
/**
 * Register the Users module service provider.
 *
 * @return void
 */
public function register()
{
	// This service provider is a convenient place to register your modules
	// services in the IoC container. If you wish, you may make additional
	// methods or service providers to keep the code more focused and granular.
	App::register('App\Modules\Users\Providers\RouteServiceProvider');
	App::register('App\Modules\Users\Providers\RepositoryServiceProvider');

	$this->registerNamespaces();
}
```

**Comment by kaidesu** [comment]
Also, I want to clarify that you should not be adding your modules service providers to your app config file. You only need to add the Caffeinated Modules package service provider - it will handle auto-loading any modules you have for you.
