### ISSUE TITLE
Delete/Remove Module

### ISSUE THREAD

**Issue by JamesJJMurray** [caffeinated/modules#170]
Is there any functionality to remove/delete a module, so that it does not display with the `module:list` command?

I've gone so far as to delete the directory for the module I wish to remove, but can't manage to locate where it's defined exactly what modules exist.

**Comment by kaidesu** [comment]
Module manifest information is cached within the `modules.json` file within your storage directory. This can definitely be improved, but you can simply delete the file and run `php artisan module:optimize`

I'll work on improving this workflow though. If you (or anyone else) have any suggestions, I'm all ears!
