### ISSUE TITLE
Not sure where to put module specific assets? Public folder items

### ISSUE THREAD

**Issue by phillipmadsen** [caffeinated/modules#171]
Do I  use the root public folder or is there a module specific folder so I  can keep this a bit cleaner?

**Comment by theomessin** [comment]
Well, I keep them in the resources folder of the module in an assets folder. The thing is, if the assets are images or Sass or JavaScript, or something along those lines you need to make sure they get moved to the public folder using gulp or grunt (I use grunt) or something like that....

**Comment by kaidesu** [comment]
The package development docs on Laravel's website can still be applied to your modules. Modules can come with their own assets where you may then *publish* them to your public directory.

https://laravel.com/docs/5.2/packages#public-assets
