### ISSUE TITLE
Inconsistent slug handling

### ISSUE THREAD

**Issue by biwerr** [caffeinated/modules#173]
Please change the slug collection to strlolowser because exists function converts the slug to lower and the result will not find the slug.
[current function](https://github.com/caffeinated/modules/blob/69c7a70845093b33bfa736f3677c5ab5fe41a82a/src/Repositories/LocalRepository.php#L64)
```
public function slugs()
	{
		$slugs = collect();

		$this->all()->each(function($item, $key) use ($slugs) {
			$slugs->push(strtolower($item['slug']));
		});

		return $slugs;
	}
```

**Comment by gerardreches** [comment]
That's not an issue. Lowercase slugs are a convention. If you want your module name with uppercase letters you can get its `name` property.

**Comment by biwerr** [comment]
ok, but this function will not work if you ignore the convention ;)

https://github.com/caffeinated/modules/blob/69c7a70845093b33bfa736f3677c5ab5fe41a82a/src/Repositories/LocalRepository.php#L114

**Comment by gerardreches** [comment]
Yeah, but conventions exists for some reason. You can decide to not follow them, but then you will have a lot of problems, because most things are based on conventions.

**Comment by biwerr** [comment]
ok, so we could add a notice in the documentation that caffeinated/modules
will not work with slugs which are not in lowercase :)

**Comment by kaidesu** [comment]
Going to re-open this actually - there are some inconsistencies with how slugs are handled that need to be ironed out throughout the codebase
