### ISSUE TITLE
Undefined index: slug after creating the first module

### ISSUE THREAD

**Issue by er-karim** [caffeinated/modules#175]
Hello, I have an issue in creating other modules, i have already created the first module using `php artisan make:module nameOfModule` but when i wanted to create the second one with the same command i had this error on my cmd
`  [ErrorException]
  Undefined index: slug`
i don't know what to do, pleas any helps ?

**Comment by er-karim** [comment]
i don't why `php artisan` doesn't work anymore

**Comment by Uhelliton** [comment]
@kaidesu, I am having the same problem and found no solution, using with laravel 5.1.  Help me

**Comment by kaidesu** [comment]
@Uhelliton the only reason that I can think of is if you have improperly formatted JSON in your module manifest file. Please double check and make sure its properly formatted and that you don't have any trailing commas~
