### ISSUE TITLE
Broken modules after update

### ISSUE THREAD

**Issue by gerardreches** [caffeinated/modules#176]
I updated from ~2.0 to ^3.0 and my modules has stopped working. I want to see a package changelog to know the changes on each version, but I can't find it.

After update, I created a new module but it either works. Do I have to execute `php artisan vendor:publish` again after update the package in order to make it work again? Will this overwrite my modules config?

**Comment by kaidesu** [comment]
Changelog is here: https://github.com/caffeinated/modules/releases/tag/v3.0

You'll need to run the `module:optimize` artisan command as with v3+ the package creates a cache of your module manifest information to aid in speed improvements.
