### ISSUE TITLE
caffeinated/modules viewa using a double-colon syntax

### ISSUE THREAD

**Issue by 1007380462** [caffeinated/modules#177]
i usecaffeinated/modules to create modules,i need to render view that useing a double-colon syntax ,
i have a doubt,laravel is don't support this syntax ,can you tell me the theory about to  implementation.

**Comment by gerardreches** [comment]
It's simple, you don't have to take care about if laravel supports this syntax, the package make Laravel work with this syntax to get specific module views.

`return view('posts.show');`
Returns view in  `base_path('resources/views/posts/show.blade.php')`

`return view('blog::posts.show');`
Returns view in  `config('modules.path')/blog/Resources/Views/posts/show.blade.php`
