### ISSUE TITLE
Module does not exist

### ISSUE THREAD

**Issue by acccims** [caffeinated/modules#179]
I tried creating migration but it says Module does not exist:
`php artisan make:module:migration App\Modules\UserLogin create_tblEmpProfile_table`
i also tried:
`php artisan make:module:migration UserLogin create_tblEmpProfile_table`

My module is enabled too....anything i am doing wrong?

**Comment by theomessin** [comment]
You need to enter the slug if I remember correctly.

Also be sure to run ```composer dump-autoload -o```.

**Comment by acccims** [comment]
Thanks, It works with lowercase...two more question: 
1. how do i route from a view or controller  of module x to route of module y?  
2. how do i route from one module to the route of another module?

**Comment by gerardreches** [comment]
You can use routes normally. Only make sure to not overwrite an existing route in a new module.

Personally I use something like this in order to avoid overwritten routes:
```
Route::group(['prefix' => 'blog', 'as' => 'blog::', 'middleware' => ['web'] ], function() {
    Route::get('/', [
			'as' => 'index',
			'uses' => 'PostsController@index'
		]);
}
```
and then I call `route('blog::index')`.
