### ISSUE TITLE
Different Folder, modules not working

### ISSUE THREAD

**Issue by developernaren** [caffeinated/modules#18]
I created a modules with `modules:make` but I defined the path in the config as 
I created the config file in `config/caffeinated/modules.php`. I looked around in the code and seemed config needed to be there.

This is my config file. The creation worked and the module is created as expected in the defined folder.

```php    
<?php
return [
    'path'      => './components/modules',
    'namespace' => 'App\Modules\\'
];
```

the module was created in the right path but when I do `module:list` it says not modules defined 
`Your application doesn't have any modules.`
and the routes.php inside the folder is not being read. the route defined in the default routes.php in the newly created module is not working.

I thought may be the files are not being loaded so I added `components/modules` in the autoload in composer.json file but that is not also working.

**Comment by developernaren** [comment]
is there any update on this. Is this a user error or the issue in the package?

**Comment by kaidesu** [comment]
I'll be taking a look into it tonight, I'm slowly getting around to writing unit tests to cover everything as well.

**Comment by developernaren** [comment]
No problem. Take your time.

**Comment by kaidesu** [comment]
Got ya covered~ Should be good to go now.

**Comment by developernaren** [comment]
Tried and working like a charm.. 

thanks for the help..there is one thing though that I would like to see as a feature. If there was a way that I could define multiples paths and multiple namespaces to group the modules themselves as part of a bigger package that would be awesome.

**Comment by kaidesu** [comment]
Yeah, I have that on my to-do list! Maybe after I get tests written and a stable 1.0 released.
