### ISSUE TITLE
routing between modules

### ISSUE THREAD

**Issue by acccims** [caffeinated/modules#180]
1. how do i route from a view or controller of module x to route of module y?

2. how do i route from one module to the route of another module?

**Comment by gerardreches** [comment]
You can use routes normally. Only make sure to not overwrite an existing route in a new module.

Personally I use something like this in order to avoid overwritten routes:
```
Route::group(['prefix' => 'blog', 'as' => 'blog::', 'middleware' => ['web'] ], function() {
    Route::get('/', [
            'as' => 'index',
            'uses' => 'PostsController@index'
        ]);
}
```

and then I call route('blog::index').
