### ISSUE TITLE
View [layouts.master] not found.

### ISSUE THREAD

**Issue by oLDu67** [caffeinated/modules#181]
I created Admin module.I tried make a blade structure but  it says View [layouts.master] not found.
in Views folder of Admin module.

-layouts
--header.blade.php
--sidebar.blade.php
--footer.blade.php

-pages
--index.blade.php

master.blade.php

**index.balde.php**
**@extends('layouts.master')**

it says "ErrorException in FileViewFinder.php line 137:
View [layouts.master] not found. (View: /home/vagrant/Code/ensarnews/app/Modules/Admin/Resources/Views/pages/index.blade.php)"

Any ideas?

**Comment by gerardreches** [comment]
You have to use your module slug before the view:
`@extends('admin::layouts.master')`

**Comment by oLDu67** [comment]
Thank you @gerardreches ..

**Comment by gerardreches** [comment]
@oLDu67 Remember to close the issue if it is already resolved ;)
