### ISSUE TITLE
Provide an option to keep a new module disabled

### ISSUE THREAD

**Issue by VizuaaLOG** [caffeinated/modules#184]
I'm not sure whether this would be a quick addition, in my head it seems like it 'might' be but when are some things ever easy in the world of programming ;).

Anyway back on topic. I'm using this module as a wrapper around plugins for a custom CMS, these plugins could have their own composer dependencies, for example a store plugin may need the PayPal REST API. Currently, if a new module is found it is enabled by default, this can cause problems when running composer update as Laravel is expecting the composer dependencies to be available, running '--no-scripts' seems to also disable the wikimedia merge plugin.

I was thinking of adding a new config option which sets the default state for a module either enabled or disabled, I also run Database setup etc when a module is enabled, which wouldn't be run if the plugin is added and enabled by default.

In my head I'm thinking this would be "simply" replacing the area where 'enable' is set on the module with a config flag, which defaults to enabled if not provided.

I could probably hack this together myself but if it something you think would be a good option to have in the package then I'm happy to make a PR?

**Comment by kaidesu** [comment]
This would be an awesome addition to the config file for sure~

Hack away!
