### ISSUE TITLE
Running command optimize overwrites status of existing modules.

### ISSUE THREAD

**Issue by sroutier** [caffeinated/modules#186]
Hello,

First I would like to thank you for this excellent project, I forked a copy that I use for one of my project and it really works very well. 

Lately I noticed that when the optimize command is called it will read the manifest files of all existing modules and combine them all in one cached file. The problem that I have is that if an existing module is enabled or disabled, that setting is set/updated in the cache and not in the manifest, so when a new module is added and the optimize command called to have the cache updated, the enabled state of the existing module is overwritten with the content of the manifest and essentially lost.

Is this behaviour by design? If this is an unexpected behaviour, I created a fix for this by having both the cache and the manifest updated during a LocalRepository::Set(). i will submit a PR if you are interested.

Thank again.
/S

**Comment by sroutier** [comment]
Nerver-mind. False alert, sorry about that.
I was causing my own trouble by having a default value for the state in the stub of the manifest file.
When the enable state is only kept in the cache, all subsequent optimize command preserve the current state....

**Comment by kaidesu** [comment]
Oh, (just to clarify) did you have the `enabled` key set in your module's manifest file manually?

**Comment by sroutier** [comment]
Yes, I added the `enabled ` key in the manifest, and in the stub manually, in my fork. It seemed like a sensible idea at the time, but I have now reverted.
All is good on your end.

Thanks.
/S

**Comment by kaidesu** [comment]
Awesome! Glad to hear everything's working for you~
