### ISSUE TITLE
autoload/register middleware

### ISSUE THREAD

**Issue by alainbelez** [caffeinated/modules#19]
can't seem to find a way to autoload/register middleware, other than adding it manually in Kernel.php

**Comment by kaidesu** [comment]
Can you not register the middleware through your modules route service provider?

**Comment by alainbelez** [comment]
i did.
protected $middleware = [
	'App\Modules\Blog\Http\Middleware\SomeMiddleware'
];

**Comment by kaidesu** [comment]
Unfortunately this doesn't seem to be possible. You'll need to manually update your `app/Http/Kernal.php` file with any Middleware classes you create.

See here for more on the topic, maybe something will come along to achieve this in a future Laravel update:
- https://laracasts.com/discuss/channels/general-discussion/register-middleware-via-service-provider
- https://github.com/laravel/framework/issues/7331

**Comment by kaidesu** [comment]
Also https://github.com/laravel/framework/issues/6211
