### ISSUE TITLE
A way to add new folders in /modules/ to the modules.json?

### ISSUE THREAD

**Issue by m3nt0r** [caffeinated/modules#191]
I was trying out this package and the first module i created with `artisan make:module` worked great. I trimmed it down to be my _boilerplate_ for future modules of the same _type_. 

For testing i duplicated the folder and renamed everything. Then i did a "module:list" and to my surprise the folder was nowhere to be found. I tried many things and double-checked until i figured that the modules must be in some type of stale registry. 

That brought me to the `storage/app/modules.json` and i was wondering how i can add my new (rogue) module. - perhaps artisan or facade? But they don't have any type of "add" or "init" command it seems.

Modules may not always be created on the same application via "make". 
Maybe i'm importing from another project, cloning from github, etc.

Am i missing something? Thanks.

**Comment by kaidesu** [comment]
Sorry, its simply due to some missing documentation.

You may run the `php artisan module:optimize` command and the cache will be updated with your new module!
