### ISSUE TITLE
debugbar not showing

### ISSUE THREAD

**Issue by sachinvrg** [caffeinated/modules#193]
Can anyone please help me to find out , why debug bar is not showing in laravel module structure
please check the following screen shot, it is working only for root url -
![screen1](https://cloud.githubusercontent.com/assets/12329845/16034811/66711568-3231-11e6-8ee7-819319a5d7de.png)
However the same code is not working for below url-
![screen2](https://cloud.githubusercontent.com/assets/12329845/16034829/882a4f12-3231-11e6-8beb-c94d3b0e61ae.png)
'api' is nothing but a module created in '/var/www/html/demo/app/modules/Api' 

Please help
Thanks much.

**Comment by kaidesu** [comment]
If you take a look at the the route file for your module, you'll see that the default route is simply a closure with a die and dump statement. You need to return a response in order for the debug bar to render.

**Comment by sachinvrg** [comment]
Thanks much dude! for your precious time, it was a silly mistake (: +1
