### ISSUE TITLE
php artisan migrate:refresh - class not found

### ISSUE THREAD

**Issue by camel-chased** [caffeinated/modules#194]
I have modules folder in root folder of my project.
In modules i have `database/migrations` classes.
`php artisan module:migrate:refresh` work's just fine.
Problem is when I want to run main migrate:refresh on the `project_root/database/migrations`
migrate cannot locate the files under the `modules/database/migration` but they are in `migrations` table in the database so I have an `Classs ... not found` exception.
Default migration script is trying to remove table from modules and have no idea where it is :)

---

Laravel 5.2
caffeinated/modules 3.0

**Comment by godeg123** [comment]
have same issue,

        "laravel/framework": "5.1.*",
        "caffeinated/modules": "~2.0"

**Comment by godeg123** [comment]
solve by adding this

        "classmap": [
            "database"
        ],

on every composer.json modules

**Comment by jadsalhani** [comment]
Happening with me as well and I already have 
```    
"classmap": [
        "database"
    ],
```
Any way to resolve this?

**Comment by A-Lawrence** [comment]
@camel-chased are you still having a problem? Have you tried any of the later versions?  I'm unable to reproduce this error.

**Comment by camel-chased** [comment]
ask others  - I don't use this lib anymore. Too many problems were here and there. Sorry. Idea is very good i appreciate work that has been done, and I know that that peaople doing this for free, but in reality there was a lot more problems than solutions. You can close this topic.

**Comment by shanecp** [comment]
I came across this issue. Seems it's an issue with Laravel 5.2, because the rollback command doesn't accept the `path` argument. Looks like upgrading to 5.3+ would resolve it.
