### ISSUE TITLE
module:enable don't revalidate list of modules 

### ISSUE THREAD

**Issue by pyatnitsev** [caffeinated/modules#197]
I'm just fetching code from our git with changes and new modules. if module don't exists in storage/app/modules.json and if I try execute:
 ```php artisan module:enable <module name>``` 
I have a message: 
```Module is already enabled```
and if I try get a list of installed modules by 
```php artisan:modules:list``` 
it shows some modules are disabled. 

I removed file storage/app/modules.json to resolve this issue.

**Comment by sroutier** [comment]
Hello,

Did you try to run:
```
php artisan module:optimize
```
right after getting the changes from your git?

Perhaps there really is a bug if you are told that your module is already enabled if it is not, but I think that the ```module:optimize``` command should fix this for you.

Cheers.
/S

**Comment by kaidesu** [comment]
When pulling from Git, you will want to run the `artisan module:optimize` command as @sroutier mentioned before running any enable/disable commands when you have new modules present.
