### ISSUE TITLE
Module order when executing migrations

### ISSUE THREAD

**Issue by agent306** [caffeinated/modules#199]
It'd be great if **module:migrate** without a module name could follow an order when executing module migrations. Certain foreign key constraints fail, when one module requires a migration from another module to be run before it is run. So I think a key - value pair in the manifest file might do the trick.

Thanks!

**Comment by kaidesu** [comment]
You can specify an `order` key in your module manifest files to control the order in which they're loaded~

**Comment by agent306** [comment]
Hi! the ```order``` key doesn't seem to be working. Here is my manifest file from two of my modules:

**Core Module**
```php
{
	"name": "Core",
	"slug": "core",
	"namespace": "Core",
	"version": "1.0",
	"author": " ",
	"license": "MIT",
	"order": 1,
	"description": "All core functionality included in this module"
}
```

**Misc Module**
```php
{
	"name": "Misc",
	"slug": "misc",
	"namespace": "Misc",
	"version": "1.0",
	"author": " ",
	"license": "MIT",
	"order": 2,
	"description": "This is the description for the Misc module."
}
```

Is there something wrong with my manifest files? It still migrates and seeds my files in a random order I cannot decipher.

**P.S:**
The ```order``` key works in https://github.com/pingpong-labs/modules
