### ISSUE TITLE
App namespace is hardcoded in stub files

### ISSUE THREAD

**Issue by virtualstep** [caffeinated/modules#20]
The following error appears after installation from modules package:

"`App\Modules\Users\Providers\UsersServiceProvider` not found"

Reason (I think):

I've change the app name from "app" to "cms". So this produce an error. Please fix this! Thanks.

Sorry for my bad english, I'm from Germany ,)

**Comment by kaidesu** [comment]
Did you change your App namespace before or after you created the module?

**Comment by virtualstep** [comment]
before creating the Module.

this is normal I think



Am 29. Januar 2015 19:19:15 schrieb Shea Lewis <notifications@github.com>:

**Comment by kaidesu** [comment]
Alright, thanks! I believe I have the App namespace hard-coded in the stub files. I'll be sure to get it updated to pull in the configured App namespace automatically.

In the mean time you'll just need to update the namespace's in your module files manually to get things working again.

**Comment by kaidesu** [comment]
Actually, this is covered by the `namespace` config option supplied with the package. Be sure to update this if you move where your modules are housed or if you change your App namespace.

```php
/*
|--------------------------------------------------------------------------
| Modules Base Namespace
|--------------------------------------------------------------------------
|
| Define the base namespace for your modules. Be sure to update this value
| if you move your modules directory to a new path. This is primarily used
| by the module:make Artisan command.
|
*/	

'namespace' => 'App\Modules\\'
```
