### ISSUE TITLE
'Order' Key in manifest file not working!

### ISSUE THREAD

**Issue by agent306** [caffeinated/modules#202]
Hi! the ```order``` key doesn't seem to be working. Here is my manifest file from two of my modules:

**Core Module**
```php
{
	"name": "Core",
	"slug": "core",
	"namespace": "Core",
	"version": "1.0",
	"author": " ",
	"license": "MIT",
	"order": 1,
	"description": "All core functionality included in this module"
}
```

**Misc Module**
```php
{
	"name": "Misc",
	"slug": "misc",
	"namespace": "Misc",
	"version": "1.0",
	"author": " ",
	"license": "MIT",
	"order": 2,
	"description": "This is the description for the Misc module."
}
```

Is there something wrong with my manifest files? It still migrates and seeds my database in a random order I cannot decipher.

**P.S:**
The ```order``` key works in https://github.com/pingpong-labs/modules

**Comment by kaidesu** [comment]
you'll need to run `module:optimize` after updating any manifest file~
