### ISSUE TITLE
Getting Illegal string offset when running module:list and others

### ISSUE THREAD

**Issue by Jaronloch2** [caffeinated/modules#204]
Encountered just today (07-12-2016) on a fresh caffeinated/module installation.

Replicate:
Install Laravel 5.2

**CMD:**
`composer require caffeinated/modules`
**config/app.php**
_added to providers_ `Caffeinated\Modules\ModulesServiceProvider::class,`
_added to aliases_ `'Module' => Caffeinated\Modules\Facades\Module::class,`
**config/compile.php**
_added to providers_ `Caffeinated\Modules\ModulesServiceProvider::class,`

**CMD**:
`composer dump-autoload`
`php artisan make:module doge`

`php artisan module:list`
**returns** 

> [ErrorException]
> Illegal string offset 'enabled'

Caffeinated modules installed yesterday works. (07-11-2016)

**Comment by Jaronloch2** [comment]
Solved it by myself.
Check this post for the [solution ](http://bgtsworks.blogspot.com/2016/07/caffeinated-modules-command-error-31.html)I found.

http://bgtsworks.blogspot.com/2016/07/caffeinated-modules-command-error-31.html

**Comment by Jaronloch2** [comment]
In case anyone points out that in the Wiki it says Caffeinated Modules supports Laravel 5.0 - 5.1 only, I saved a screenshot of my case. Hope the Coffee guys can help us clear things out soon. :)

![cafff](https://cloud.githubusercontent.com/assets/17738997/16778820/45b01cf2-48a2-11e6-9b47-b8bd671a8383.PNG)

**Comment by kaidesu** [comment]
Thanks for the report, I'll get this fixed in a couple minutes~

**Comment by VizuaaLOG** [comment]
@kaidesu also receiving this error in ```LocalRepository.php``` on ```line 171```. Have done some investigating and the ```$values``` variable contains the modules name rather than a module object.

**Comment by kaidesu** [comment]
@VizuaaLOG thanks for finding this! Would you mind opening a new issue here with this information so we can track it separately? Thanks!
