### ISSUE TITLE
FatalErrorException in RouteServiceProvider.php line 42:

### ISSUE THREAD

**Issue by cerberus478** [caffeinated/modules#207]
I'm getting this error

> FatalErrorException in RouteServiceProvider.php line 42: Modules\Menus\Providers\RouteServiceProvider::Modules\Menus\Providers{closure}(): Failed opening required 'Modules/Menus/Http/routes.php' (include_path='.;C:\php\pear')

It happens when I create a module. I'm not sure what I should do to fix this.

**Comment by Jaronloch2** [comment]
tried
php artisan make:module Menus 

worked fine for me. have you tried to
composer dump-autoload

or

composer update

**Comment by cerberus478** [comment]
I've tried both and they didn't work

**Comment by Jaronloch2** [comment]
what version are you using?

**Comment by cerberus478** [comment]
caffeinated module = 3.1
Laravel = 5.2
Wamp = 2.5

**Comment by Jaronloch2** [comment]
I can't replicate this on my cafmod 3.1 and lara 5.2

have you tried running composer require caffeinated/modules again and then running php artisan vendor:publish?

**Comment by cerberus478** [comment]
I've done that and still the same issue

**Comment by Jaronloch2** [comment]
Check if you have vendor/caffeinated/modules/src/Support/ServiceProvider.php

**Comment by cerberus478** [comment]
Yes I do

**Comment by cerberus478** [comment]
Would it be possible for someone to give me either their wamp or xampp settings? I would like to compare and see if maybe it's an issue there

**Comment by kaidesu** [comment]
I personally don't use WAMP or XAMPP - I would consider using Homestead~

**Comment by jjasiunas** [comment]
It looks like you moved Modules out of app. Try setting your path in `config/modules.php` to

```
`'path' => app_path('../Modules'),`
```

**Comment by A-Lawrence** [comment]
@cerberus478 have you resolved this issue?  I'd highly recommend upgrading to the latest 4.x version to make use of all the bug fixes that have been pushed out!

**Comment by ashinzekene** [comment]
Issue isn't resolved, i have the latest laravel and and i'm using xamp

**Comment by kaidesu** [comment]
I simply can't provide support for windows based development platforms (like XAMPP) - please use a *nix based platform such as Homestead.

**Comment by davin4i88** [comment]
Its same in Linux based platform, i moved modules folder outside of App and receiving same issue.

`"Modules\Pages\Providers\RouteServiceProvider::Modules\Pages\Providers\{closure}(): Failed opening required 'modules/Pages/Routes/web.php' (include_path='.:')"`

**Comment by kaidesu** [comment]
And you followed the docs? Seems like you didn't update your composer file:

https://github.com/caffeinated/modules/wiki/Configuration#to-move-modules-folder

**Comment by davin4i88** [comment]
Yes, i followed the docs.
