### ISSUE TITLE
Module Seed needs to be modified to work

### ISSUE THREAD

**Issue by Jaronloch2** [caffeinated/modules#208]
When doing module:seed slug:

ErrorException
Illegal string offset 'namespace'

Fixed temporarily from vendor/caffeinated/modules/src/Console/Commands/ModuleSeedCommand.php
line 89 and 91

Replaced $module['namespace '] with just $module

    protected function seed($slug)
    {
        $module        = $this->module->where('slug', $slug)->first();
        $params        = [];
        $namespacePath = $this->module->getNamespace();
        // $rootSeeder    = $module['namespace'].'DatabaseSeeder';
        $rootSeeder    = $module.'DatabaseSeeder';
        // $fullPath      = $namespacePath.'\\'.$module['namespace'].'\Database\Seeds\\'.$rootSeeder;
        $fullPath      = $namespacePath.'\\'.$module.'\Database\Seeds\\'.$rootSeeder;

**Comment by Jaronloch2** [comment]
Seems that almost everything related to the $module variable returns an error. index 'slug' index 'namespace' etc... how can I revert to 3.0 beta?

**Comment by Venko007** [comment]
this is fix: https://github.com/caffeinated/modules/pull/209

**Comment by Jaronloch2** [comment]
I just recomposed the latest commit, but it now returns Error Undefined Index: enabled 
I think it is in the where() function of LocalRepository please check.

**Comment by Jaronloch2** [comment]
![dede](https://cloud.githubusercontent.com/assets/17738997/16807904/d3e2c538-494c-11e6-85e1-3c2dde79853d.PNG)

**Comment by Venko007** [comment]
the pull request is not merget yet!

**Comment by kaidesu** [comment]
Merged and tagged your pull-request, thanks for that @Venko007 ! And sorry for the issues @Jaronloch2!

**Comment by Jaronloch2** [comment]
lol thanks guys, sorry for being to excited venko xD
