### ISSUE TITLE
php artisan module:make-request throws Command "dump-autoload" is not defined.

### ISSUE THREAD

**Issue by RonnieVisser** [caffeinated/modules#21]
Hi,

I want to run following command: `php artisan module:make-request Importer CreateCountryRequest`. When doing this the following errors is thrown.

```
exception 'InvalidArgumentException' with message 'Command "dump-autoload" is not defined.'
```

**Comment by kaidesu** [comment]
Thanks for pointing this out.

Just to verify, was the request file still created?

**Comment by RonnieVisser** [comment]
The response says it did but the actual file wasn't created!

—
Verzonden via Mailbox

**Comment by kaidesu** [comment]
Thanks! I'll be sure to get it ironed out.
