### ISSUE TITLE
Write Tests!

### ISSUE THREAD

**Issue by kaidesu** [caffeinated/modules#210]

**Comment by Jaronloch2** [comment]
module:seed slug --class=SlugDatabaseSeeder

SlugDatabaseSeeder does not exist.

but app/Modules/Slug/Database/Seeds/SlugDatabaseSeeder.php

same instance,
module:seed slug 
- can detect the SlugDatabaseSeeder but returns
- SlugDatabaseSeeder contains $this->call('App\Modules\Slug\Database\Seeds\SlugOthertableSeeder');

App\Modules\Slug\Database\Seeds\SlugOthertableSeeder does not exist

**Comment by Jaronloch2** [comment]
Solved  2nd issue (withoug --class) 

namespace App\Modules\Slug\Database\Seeds;
was added to the SlugOthertableSeeder

**Comment by A-Lawrence** [comment]
This would be helpful 😄 Once you get started, I'll throw in whatever I can @kaidesu!
