### ISSUE TITLE
MakeModuleCommand class fail to make module on 5.1 Easy to fix I think

### ISSUE THREAD

**Issue by GianNipitella** [caffeinated/modules#212]
Hi, I'm using laravel 5.1 and when i Try php artisan make:module blog y get 

`  [Illuminate\Contracts\Filesystem\FileNotFoundException]
  File does not exist at path C:\xampp\htdocs\sailuz4\vendor\caffeinated\modu
  les\src\Console\Generators/../../../resources/stubs/seeder_v5.1.stub
`

so looking at the resources/stubs there is not seeder_v5.1 so I copied seeder.stub content to seeder and rerun make:module to find out that  there wasn't a routes_v5.1.stub neither so i went and take a look at the code of MakeModuleCommand and find these lines 

`    protected function getStubContent($key)
    {
        $stub    = $this->moduleStubs[$key];
        $laravel = app();

        if (
            version_compare($laravel::VERSION, '5.2.0', '<') and
            version_compare($laravel::VERSION, '5.1.0'. '>=')) {
            $stub = $stub.'_v5.1';
        }

        return $this->formatContent($this->files->get(__DIR__.'/../../../resources/stubs/'.$stub.'.stub'));
    }` is there 

 since the only  stub that ends in _v5.1 is routeserviceprovider_v5.1 (I Imagine because the web middlewere) I modify the code this way 

`protected function getStubContent($key)
    {
        $stub    = $this->moduleStubs[$key];
        $laravel = app();

        if (
            version_compare($laravel::VERSION, '5.2.0', '<') and
            version_compare($laravel::VERSION, '5.1.0'. '>=')) {
        switch ($stub) {
            case 'routeserviceprovider':
                $stub = $stub.'_v5.1';
                
                break;

            default:
                break;
        }
           
        }

        return $this->formatContent($this->files->get(__DIR__.'/../../../resources/stubs/'.$stub.'.stub'));
    }`

I know this isn't pretty and I would prefer just to add all the stubs needed to my app/resources/stubs folder using the php artisan vendor:publish --tag=stubs that I found in the modules.php but they didn't work so if you could please fix it in the future I'll be very thankfully since It looks like We(my team) are going to be using this package a lot

**Comment by GianNipitella** [comment]
Ok I'm back, after taking a further look into the code


```
 protected function displayHeader($file = '', $level = 'info')
    {
        if(!empty(config('modules.custom_stubs'))){
            $stub = $this->files->get(config('modules.custom_stubs').'/console/'.$file.'.stub');
        }else{
            $stub = $this->files->get(__DIR__.'/../../../resources/stubs/console/'.$file.'.stub');
        }
        
        return $this->$level($stub);
    }
```
So I modified the same function again like this 
```
protected function getStubContent($key)
    {
        $stub    = $this->moduleStubs[$key];
        $laravel = app();

        if (
            version_compare($laravel::VERSION, '5.2.0', '<') and
            version_compare($laravel::VERSION, '5.1.0'. '>=')) {
            $stub = $stub.'_v5.1';
        switch ($stub) {
            case 'routeserviceprovider':
                $stub = $stub.'_v5.1';
                
                break;

            default:
                break;
        }
           
        }
        
        if(!empty(config('modules.custom_stubs'))){
           return $this->formatContent($this->files->get(config('modules.custom_stubs').$stub.'.stub'));
        }else{
           return $this->formatContent($this->files->get(__DIR__.'/../../../resources/stubs/'.$stub.'.stub'));
        }
    }
```
also had to modify the content inside module.custom_stubs like this 

`'custom_stubs' => base_path('resources\stubs\\'),`

 so now I can use my Custom Stubs and switch inside getStubContent can be overlooked I leave to you ppl to chose the solution I Just hope this gave you some ideas

**Comment by GianNipitella** [comment]
you could also make stubs for folder dependent for the version of laravel for example 

resource/stub
----console
----v5.1
------------stubs for laravel 5.1
----v5.2
------------stubs for laravel 5.2 
----v5.3
------------stubs for laravel 5.3

this is simply by changing the line 
$stub = $stub.'_v5.1';
$stub = 'v5.1\\'.$stub;

**Comment by zhouyixiang** [comment]
Same issue here. I modified the source code like this:
```php
        if (
            version_compare($laravel::VERSION, '5.2.0', '<') and
            version_compare($laravel::VERSION, '5.1.0'. '>=')) {
            $l51SpecificPath = __DIR__.'/../../../resources/stubs/'.$stub.'_v5.1.stub';
            if ($this->files->exists($l51SpecificPath)) {
                return $this->formatContent($this->files->get($l51SpecificPath));
            }
        }

        $stubPath = __DIR__.'/../../../resources/stubs/'.$stub.'.stub';
        return $this->formatContent($this->files->get($stubPath));
```
So if you use Laravel 5.1 it will try 5.1 specific stub files first, and will fallback to the general version if there's none.

**Comment by sarfraznawaz2005** [comment]
I had the same issue, I commented this line `$stub = $stub.'_v5.1';`

**Comment by GianNipitella** [comment]
@sarfraznawaz2005 carefull mate that will make all your modules RouteServicesProviders to use the 'web' Middleware wich does not exists by default in laravel 5.1 therefore making all your new modules unusables you will also need to change the routeservicesprovider.stub

**Comment by kaidesu** [comment]
I'll get this on my radar to be cleaned up~

If anyone wants to take a stab at it though I'm open to pull requests!

**Comment by sarfraznawaz2005** [comment]
@GianNipitella yes i just removed "web" middelware one it was generated :)
