### ISSUE TITLE
namespace issue

### ISSUE THREAD

**Issue by brocklesnah** [caffeinated/modules#214]
When i change the app:name using artisan from the App namespace. If i try to use make:module: controller, well it places it in the right namespace but just below namespace declaration it uses imports classes from App namespace still.

For instance, controller will still use App\Http\Requests 
instead of 
NewNamespace\Http\Requests

**Comment by kaidesu** [comment]
Just need to update your modules config file:

```php
/*
|--------------------------------------------------------------------------
| Modules Base Namespace
|--------------------------------------------------------------------------
|
| Define the base namespace for your modules. Be sure to update this value
| if you move your modules directory to a new path. This is primarily used
| by the module:make Artisan command.
|
*/

'namespace' => 'App\Modules\\',
```

**Comment by kaidesu** [comment]
Oh wait, nevermind, I see what you mean. This will be taken care of soon with the ability to define custom stubs.
