### ISSUE TITLE
Submodule / Subfolder structure

### ISSUE THREAD

**Issue by zigapompe** [caffeinated/modules#215]
Hi, 
I need a custom directory structure in modules folder, so I can organize modules in a more structured fashion. I know I can solve this by just using namespaces, but what I would need is the actual automatic logic of the plugin which loads module.json and handles routes, service providers, etc... So, is the following structure possible? 

Example
App\Modules
1. Module1
2. Module2
3. Folder1
3.1 Module3
3.2 Module4

**Comment by VizuaaLOG** [comment]
Have you tried adding ```Folder1``` as an additional namespace folder?

So if you want to define Module 1 / use Module 1 you would do
```PHP
namespace App\Modules\Module1;

use App\Modules\Module1;
```

And then if you wnat to define Module 3 / use Module 3 you would do
```PHP
namespace App\Modules\Folder1\Module3;

use App\Modules\Folder1\Module3;
```

**Comment by zigapompe** [comment]
That works, yes, but the problem is in the plugin itself.. It does not parse module.json in subdirectories, only on the first level - which means it won't automatically load all the service providers, routes, etc...
I think I'll just stick to my own module solution for now.

**Comment by kaidesu** [comment]
Currently no, but adding additional module locations is a planned update already. See #92 for more information~
