### ISSUE TITLE
Illegal string offset when running module:disable and module:enable

### ISSUE THREAD

**Issue by X3nz** [caffeinated/modules#216]
I've installed Laravel 5.2 and included this module in my clean system and when i was trying it out, i get that error.

![image](https://cloud.githubusercontent.com/assets/1015027/17098538/7b3d5888-5295-11e6-9018-4f685c932145.png)

![image](https://cloud.githubusercontent.com/assets/1015027/17098546/845b6ad6-5295-11e6-8a58-ce1322199058.png)

{
	"name": "Doge",
	"slug": "doge",
	"namespace": "Doge",
	"version": "1.0",
	"author": " ",
	"license": "MIT",
	"description": "This is the description for the Doge module."
}

i tried inserting the "enabled" in the module.json
{
	"name": "Test",
	"slug": "test",
	"namespace": "Test",
	"version": "1.0",
	"author": " ",
	"license": "MIT",
	"description": "This is the description for the Test module.",
    "enabled": false,
}

but it didn't work, both still gets the same error

module:list works though
![image](https://cloud.githubusercontent.com/assets/1015027/17098585/c0386914-5295-11e6-82a2-cc272e4fee30.png)

which i assume is not related to this issue as listed : #204 

Further testing with system, I tried using the facade but its giving similar effect.
![image](https://cloud.githubusercontent.com/assets/1015027/17134931/8f9d5b00-535f-11e6-9a25-8c702c934dd8.png)

**Comment by kaidesu** [comment]
This should be fixed with c504a1c347a941cb4b3f280b397e7517eda6bc39.
