### ISSUE TITLE
Cannot declare class

### ISSUE THREAD

**Issue by UnderlineWords** [caffeinated/modules#219]
I get an error now after the last update ;
```
Cannot declare class Caffeinated\Modules\Repositories\Repository because the name is already in use 
in .....\vendor\caffeinated\modules\src\Repositories\Repository.php on line 9
```
I changed lines the 5. and 9. in Repository.php as followings and It's works fine ;
```php
<?php

namespace Caffeinated\Modules\Repositories;

use Caffeinated\Modules\Contracts\Repository as AnyName; # !!
use Illuminate\Config\Repository as Config;
use Illuminate\Filesystem\Filesystem;

abstract class Repository implements AnyName # !!
{
```

Strangely, I can't get any error when i install a new Laravel from scratch.

**Comment by kaidesu** [comment]
Hmm, odd. Will take a look~

**Comment by kaidesu** [comment]
Fixed, but yeah, strange that it doesn't throw an exception on a clean install.

Thanks for the report! v3.2.3 has been tagged with the fix~

**Comment by mohamedsharaf** [comment]
abstract class implemets ?

**Comment by mohamedsharaf** [comment]
i have two installation 
one have the error and the other not 
may be php version make this 
the working is php 7.0.3
the one with error is 7.0.08

**Comment by mohamedsharaf** [comment]
Caffeinated\Modules\Repositories\Repository cannot implement Caffeinated\Modules\Repositories\Repository - it is not an interface

**Comment by UnderlineWords** [comment]
I'm developing under Php 7.0.8 and it's working fine after the https://github.com/caffeinated/modules/commit/541cdf602ad1068049051d76eb93589db607d07c update (v3.2.3). I have not tried on previous versions of Php.
