### ISSUE TITLE
module:migrate --pretend command option is broken

### ISSUE THREAD

**Issue by TerrePorter** [caffeinated/modules#22]
The option `--pretend`  doesn't work with the console command for `module:migrate`.

```
php artisan module:migrate blog --pretend
```

- from http://codex.caffeinated.ninja/modules/master/artisan-commands#modulemigrate-module

**Comment by kaidesu** [comment]
This is a weird one - when I run `php artisan migrate --pretend` I get the same behavior.

I'll keep looking into this though; either I'm missing something obvious or this is a bug with Laravel.

**Comment by TerrePorter** [comment]
Sorry, didn't see this until now.

I'm guessing the --pretend is for you to be able to catch errors before you do the real run, as when it is midway in the migration and crash the db is left incommplete.

I ran a pop artisan migrate on the base L5 and this is my return, 
```
```

**Comment by kaidesu** [comment]
Right - the `--pretend` option is supposed to spit out the generated SQL that the migrations create. I'm guessing this is a bug with Laravel since the main `migrate` command is not outputting anything when using `--pretend`.

**Comment by TerrePorter** [comment]
Looks like that is the case. I found a issue already setup upstream, laravel/framework#7085

**Comment by kaidesu** [comment]
Ah nice, good find! I'll keep an eye on that issue.

**Comment by pavankumarkatakam** [comment]
This is because the $logingquery has default value to false. So we want to manually enable the logging by calling the enableLogging() in pretend function in src/Illuminate/Database/Connection.php . I have submitted a pull request on this issue [see this](https://github.com/laravel/framework/pull/7477)

**Comment by kaidesu** [comment]
:+1: Let's hope it gets merged~

**Comment by kaidesu** [comment]
Taylor merged your PR, so this issue is now resolved in the latest version of Laravel :+1:

Thanks!
