### ISSUE TITLE
Vendor Publish Problem

### ISSUE THREAD

**Issue by boparaiamrit** [caffeinated/modules#220]
<img width="1147" alt="screenshot 2016-08-01 17 30 34" src="https://cloud.githubusercontent.com/assets/1220153/17293425/cc531d2a-580d-11e6-8e0d-0bdebcaf6dd0.png">

**Comment by boparaiamrit** [comment]
So when I try to publish configurations then package causes problem with above error

**Comment by brryfrmnn** [comment]
I have same problem too. I am using latest laravel 5.2 and caffeinated 3.2.4

**Comment by kaidesu** [comment]
Thanks, I'll take a look.

**Comment by boparaiamrit** [comment]
// when I uncomment below line , vendor:publish working fine
`'custom_stubs' => base_path('resources/stubs/'),

**Comment by dimassrio** [comment]
got it
```
public function boot()
    {
        $this->publishes([
            __DIR__.'/../config/modules.php' => config_path('modules.php'),
        ], 'config');

        $this->publishes([
            __DIR__.'/../resources/stubs/' => config('modules.custom_stubs'), //should be config_path
        ], 'stubs');

        $this->app['modules']->register();
    }

```

**Comment by jadsalhani** [comment]
Having the same issue, but I don't have the same `ModulesServiceProvider.php`

```
public function boot()
    {
        // For each of the registered modules, include their routes and Views
        $modules = config("module.modules");

        while (list(,$module) = each($modules)) {

            // Load the routes for each of the modules
            if(file_exists(__DIR__.'/'.$module.'/Http/routes.php')) {
                include __DIR__.'/'.$module.'/Http/routes.php';
            }

            // Load the views
            if(is_dir(__DIR__.'/'.$module.'/Views')) {
                $this->loadViewsFrom(__DIR__.'/'.$module.'/Views', $module);
            }
        }
    }
```

But im pretty sure the error isnt from here. I `dd()` inside it until the end while running `vendor:publish` and it reached the end, and then the flysystem error was popping up

**Comment by A-Lawrence** [comment]
Unable to reproduce in any of the latest versions @kaidesu
