### ISSUE TITLE
make module seeder - stub file not found

### ISSUE THREAD

**Issue by PR3M1UM** [caffeinated/modules#222]
I have a module with slug test and name Test.
`php artisan make:module:seeder test TestSeeder`
Gets me the error output:
`[Illuminate\Contracts\Filesystem\FileNotFoundException] File does not exist at path (omitted)\vendor\caffeinated\modules\src\ Console\Generators/../../../resources/stubs/5.2/seeder_plus.stub`

I already tried composer `dump-autoload`, `artisan optimize` and even removed the entire vendor folder and let composer install the packages again.

**Comment by kaidesu** [comment]
Thanks I'll take a look~

**Comment by WilliamNovak** [comment]
I found the same problem.

**Comment by shanecp** [comment]
Found the same issue. 

On `MakeSeederCommand.php`, line 55, it's referencing a file called `seeder_plus.stub`. Looks like this file is moved.

**Comment by A-Lawrence** [comment]
This no longer appears to be a problem in the latest version, @kaidesu

**Comment by kaidesu** [comment]
👍
