### ISSUE TITLE
how to use models in controller ?

### ISSUE THREAD

**Issue by moeinrahimi** [caffeinated/modules#223]
hi, i had created a model using php artisan make:module:model  command now in my controller how to make a object of it ?
$obj = new classname();
i suppose i need to add use command but i don't know how

**Comment by kaidesu** [comment]
Please take a look at the Basic Task List tutorial within Laravel's documentation:

https://laravel.com/docs/5.2/quickstart

The same concepts are used for building out modules. However, I would consider not using the module structure until you've had experience building some basic applications with Laravel on its own.
