### ISSUE TITLE
how to delete module?

### ISSUE THREAD

**Issue by putrakuningan** [caffeinated/modules#225]
how to delete module if not use?

**Comment by illuminate3** [comment]
I just disable modules I don't need at the moment.

Or just delete the whole directory for that module. Don't forget to rollback that migration for the module and other assets,configs that you have published.

**Comment by prashantidealittechno** [comment]
Yes I disable and delete the directory but when I run command php artisan module:list it shows the deleted module. How can I delete with command or anything that remove it safe.

**Comment by kaidesu** [comment]
You'll need to run `module:optimize` afterwards to update the module cache.

**Comment by Rajani-salvi** [comment]
i use php artisan module:disable blog but,it show error message  [ErrorException]Undefined index: enabled.
