### ISSUE TITLE
5.3 compatibility, estimated timeline?

### ISSUE THREAD

**Issue by illuminate3** [caffeinated/modules#226]
Just wondering if a 5.3 version is already under development and when the main package will be available to use?

**Comment by miranrasulian** [comment]
+1 for 5.3 compatibility

**Comment by h4mzt3r** [comment]
Interested too for a 5.3 compat 👍

**Comment by TheDeadCode** [comment]
+1

**Comment by kaidesu** [comment]
4.0 will be tagged tonight!

**Comment by vrkansagara** [comment]
:+1:
