### ISSUE TITLE
Module seed not running

### ISSUE THREAD

**Issue by tirjok** [caffeinated/modules#227]

**Comment by kaidesu** [comment]
I need more information on your setup and the steps taken when you encountered this issue.

**Comment by chriscubos** [comment]
same here

[Illuminate\Contracts\Filesystem\FileNotFoundException]                                                                                                                  
  File does not exist at path 
... 
vendor/caffeinated/modules/src/Console/Generators/../../../resources/stubs/5.3/seeder.stub

**Comment by JavierOrellanaR** [comment]
I have the same problem but the error is different... when i try to use the command:

**php artisan module:seed test**

I get this message:

<pre>
[ErrorException]            
Undefined index: namespace 
</pre>

And the Exception trace is this:

<pre>
Exception trace:
 () at /var/www/html/project/vendor/laravel/framework/src/Illuminate/Support/Collection.php:1274
 Illuminate\Foundation\Bootstrap\HandleExceptions->handleError() at /var/www/html/project/vendor/laravel/framework/src/Illuminate/Support/Collection.php:1274
 Illuminate\Support\Collection->offsetGet() at /var/www/html/project/vendor/caffeinated/modules/src/Console/Commands/ModuleSeedCommand.php:89
 Caffeinated\Modules\Console\Commands\ModuleSeedCommand->seed() at /var/www/html/project/vendor/caffeinated/modules/src/Console/Commands/ModuleSeedCommand.php:58
 Caffeinated\Modules\Console\Commands\ModuleSeedCommand->fire() at n/a:n/a
 call_user_func_array() at /var/www/html/project/vendor/laravel/framework/src/Illuminate/Container/Container.php:507
 Illuminate\Container\Container->call() at /var/www/html/project/vendor/laravel/framework/src/Illuminate/Console/Command.php:169
 Illuminate\Console\Command->execute() at /var/www/html/project/vendor/symfony/console/Command/Command.php:256
 Symfony\Component\Console\Command\Command->run() at /var/www/html/project/vendor/laravel/framework/src/Illuminate/Console/Command.php:155
 Illuminate\Console\Command->run() at /var/www/html/project/vendor/symfony/console/Application.php:818
 Symfony\Component\Console\Application->doRunCommand() at /var/www/html/project/vendor/symfony/console/Application.php:186
 Symfony\Component\Console\Application->doRun() at /var/www/html/project/vendor/symfony/console/Application.php:117
 Symfony\Component\Console\Application->run() at /var/www/html/project/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php:122
 Illuminate\Foundation\Console\Kernel->handle() at /var/www/html/project/artisan:35
</pre>

As you can see in the trace, the exception starts at the line 89 of **/var/www/html/project/vendor/caffeinated/modules/src/Console/Commands/ModuleSeedCommand.php** 
Which is:

<pre>$rootSeeder    = $module['namespace'].'DatabaseSeeder';</pre>

I've already tried to var_dump the $module variable but there's no namespace index as the error says:

<pre>
array (
      'basename' => 'Test',
      'name' => 'Test',
      'slug' => 'test',
      'version' => '1.0',
      'description' => 'This is the description for the Test module.',
      'enabled' => true,
      'order' => 9001,
    )
</pre>

**Comment by nurmanhabib** [comment]
there is no solution for now?

**Comment by A-Lawrence** [comment]
Fixed in PR #272.

@JavierOrellanaR you need to run `composer update` to update to the latest version.  Then delete `storage/app/modules.json` followed by running `php artisan module:optimize`.

@nurmanhabib @tirjok @chriscubos Until @kaidesu accepts the PR, you can (although it's not recommend) make the changes from the PR yourself.
