### ISSUE TITLE
Artisan make:module naming problem

### ISSUE THREAD

**Issue by kevmt** [caffeinated/modules#228]
Hi,

I tried your script, followed your Wiki, and I created my first module:

`php artisan make:module Organization`

Asked me questions, I just hit enter until completes. But gazing to the sources genereated, It bothers me something about `RouteServiceProvider.php`

`require (config('modules.path').'/Organization/Http/routes.php');`

while my folder is `App\Modules\organization`, I know this will work on windows `wamp` but It might error on unix systems due to `organization !== Organization`

was there a regression or I'm missing something? I know I can just refactor it but, I guess you should now.

Best Regards,

**Comment by JayLancaster** [comment]
Your issue lies in using Camel case in your artisan command. Try it creating is as php artisan make:module organization. Should work

**Comment by A-Lawrence** [comment]
@kevmt has this been resolved for you, by @JayLancaster ?
