### ISSUE TITLE
[Question] on performance

### ISSUE THREAD

**Issue by TheDeadCode** [caffeinated/modules#229]
How is performance when handling lots of modules? Is there some kind of caching mechanism to load quickly all the providers?

Thanks!

**Comment by kaidesu** [comment]
The package supports the built in `compiles` method provided with Laravel where you may specify classes to be cached by the `artisan optimize` command~

This isn't documented yet, but I'll be getting it up soon.

**Comment by TheDeadCode** [comment]
Thanks! Sorry for bothering... Although, let's say I unzip a package and install the module directly from the interface, is it possible to call \Artisan::call('optimize'), and it'll auto-recompile the framework? (Without having to go into the main `config/compile.php` and manually adding the providers)

Thanks <3

**Comment by kaidesu** [comment]
You are correct!
