### ISSUE TITLE
Facades (Updated with facade references)

### ISSUE THREAD

**Issue by Asoseil** [caffeinated/modules#23]
How can i use enable and disable a module in facades?

**Comment by kaidesu** [comment]
**Enable a module:**
```php
Module::enable('moduleSlug');
```

**Disable a module:**
```php
Module::disable('moduleSlug');
```

I'll get the documentation updated this week~ Sorry for the inconvenience!

**Comment by kaidesu** [comment]
Documentation has been updated~

http://codex.caffeinated.ninja/modules/master/facade-reference
