### ISSUE TITLE
Caffeinated Modules give me error after upgrading to laravel 5.3

### ISSUE THREAD

**Issue by ghost** [caffeinated/modules#232]
I have a project in laravel 5.2 and i want to upgrade my project to laravel 5.3, the laravel upgraded successfully, but my modules give me error undefined index : basename after my laravel upgraded. of course i have change the caffeinated/modules to v4.0 in composer.json.
in config/app.php i have  Amodules\afinance\Providers\AfinanceServiceProvider::class, but when i comment on it there is no error, but the module routing not detected in php artisan r:l and give me NotFoundHttpException when i try in browser

**Comment by syphernl** [comment]
@rifkyaziz To resolve the basename issue you should remove the `modules.json` from your application storage path (`storage/app/modules.json`). 

The new version now requires this particular key, but is missing from your cache :)

**Comment by rifkyaziz** [comment]
@syphernl it's work. thanks a lot :+1:

**Comment by oLDu67** [comment]
thank you @rifkyaziz
