### ISSUE TITLE
Routes not registered in 4.0.1

### ISSUE THREAD

**Issue by RonnieVisser** [caffeinated/modules#233]
Hi,

I just upgraded to Laravel 5.3 and to 4.0 of this package. All routes belonging to modules are not accessible and give me a lot of errors.

Can you please fix this?

**Comment by syphernl** [comment]
Upgrading to Modules 4.x requires some changes to your modules before it'll work:

- The `SLUGServiceProvider` (replace SLUG wIth your application slug) has been renamed to `ModuleServiceProvider` and uses a [different structure](https://github.com/caffeinated/modules/blob/master/resources/stubs/module/Providers/ModuleServiceProvider.php) e.g. by extending the `Caffeinated\Modules\Support\ServiceProvider`
- The [RouteServiceProvider](https://github.com/caffeinated/modules/blob/master/resources/stubs/module/Providers/RouteServiceProvider.php) uses a different approach for loading the routes. In Laravel 5.3 the routing has changed from loading `app/Http/routes.php` to loading `routes/web.php` and `routes/api.php`. 4.0 in this module has also changed to this approach.

If you make the above changes, it _should_ work again (assuming there is no other non-default Laravel magic)

**Comment by RonnieVisser** [comment]
Hi,

I already discovered that. and have changed the files. I'm now running into a different issue: Undefined index: basename. caffeinated/modules/src/Helpers/module.php line 26

still figuring out what i miss...

**Comment by RonnieVisser** [comment]
got that fixed. used an incorrect slug.

**Comment by kaidesu** [comment]
@syphernl Thanks for the helping users out around here!

**Comment by syphernl** [comment]
Happy to help @kaidesu !

**Comment by thandonguocmo2020** [comment]
what change  : 
 'path' => app_path('./Modules'), 

===>  'path' => base_path ('./Modules'), 

==> Errors Route...  when : php artisan route:list 

sorry my english is not good
