### ISSUE TITLE
Routes and controllers not found

### ISSUE THREAD

**Issue by guillaume23** [caffeinated/modules#235]
Hi !
I've created one module called todolist,
it's the only module written "todolist" without "T" in first letter...
So, i've created it, it' works fine with in localhost with MAMP, but, when i put it online, my routes are not found, and my controller called TaskController not found too. 

This is very strange. 
The namespace is App\Modules\Todolist\Http\Controllers\TaskController
but when i change it with App\Modules\todolist\Http\Controllers\TaskController
 it seems to works, but my vienw are not found like 'todolist::myview'

Someone knows where it came from ? 
Sorry for my bad english, i'm french...
Thanks !

**Comment by guillaume23** [comment]
PS: Laravel 5.2 
Caffeinated 3.2.5

**Comment by seem2810** [comment]
hi, 

I've the problem, too.

Developing in Mac with MAMP.
PHP 7 and PHP CLI 5.5.3

Local all routes are okay and working but on my live-system (PHP 5.6.24 CLI & Apache) it doesn't work.
I've try to run `php artisan module:enable dcm` I got:
<img width="234" alt="bildschirmfoto 2016-09-04 um 21 08 17" src="https://cloud.githubusercontent.com/assets/4076434/18233308/c2b1e3c8-72e3-11e6-9389-2943d7c05c0a.png">

**Comment by A-Lawrence** [comment]
Does the file `modules.json` exist in `storage/app/`?

Have you ran `composer install` or `composer update` with the `-o` flag?

Have you tried running `php artisan module:optimize` to check if it resolves the issue?

**Comment by guillaume23** [comment]
I've solved the problem.
First, you have to remove in the /storage/app/modules.json the lines about your module.
And regenrated the module.json of your module and do a 
`php artisan module:optimize`

For me, i've rename my module in lowercase "todo" > "Todo"
and change the module.json, change the basename "todo" in "Todo" 
and now it seems to work everywhere. It came form case sensitive in linux env. 

I think the module need an update !
Thanks

**Comment by seem2810** [comment]
this module is very strange with case_sensitve... 

It work now.. 
I recreate a module with the name Dcm (not dcm now)
There were a lot of problems with the dcm or Dcm

But now: 
`php artisan make:module:migration Dcm create_dcm_key_table --create=dcm_keys`
Module  does not exist.

**Comment by A-Lawrence** [comment]
Should:
`php artisan make:module:migration Dcm create_dcm_key_table --create=dcm_keys`

Not be:
`php artisan make:module:migration dcm create_dcm_key_table --create=dcm_keys`

Since the slug is always lowercase?

**Comment by seem2810** [comment]
My slug is lowercase but that doesn't work too :/

**Comment by A-Lawrence** [comment]
Can you post your `storage/app/modules.json` file?

**Comment by seem2810** [comment]
`{
    "dcm": {
        "basename": "dcm",
        "name": "Dcm",
        "slug": "dcm",
        "namespace": "Dcm",
        "version": "1.0",
        "author": "seem",
        "license": "MIT",
        "description": "some module",
        "enabled": true,
        "order": 9001
    }
}`

I've regenerated the module again.
But now a new Problem... 
The folder named "dcm", but the module look up for:
`php artisan module:optimize`
`PHP Warning:  Uncaught exception 'ErrorException' with message 'require(app/Modules/Dcm/Http/routes.php): failed to open stream: No such file or directory' in app/Modules/dcm/Providers/RouteServiceProvider.php:42
Stack trace:
`

**Comment by guillaume23** [comment]
{
"Dcm": {
"basename": "Dcm",
"name": "Dcm",
"slug": "dcm",
"namespace": "Dcm",
"version": "1.0",
"author": "seem",
"license": "MIT",
"description": "some module",
"enabled": true,
"order": 9001
}
}

Try with it maybe ?

**Comment by seem2810** [comment]
sorry but this doesn't work :( 
Same error... 

The module want to include Modules/Dcm/Http/routes.php
It must be Modules/dcm/Http/routes.php

Local it works fine but on my debian live-system not :(

**Comment by guillaume23** [comment]
`"Todo": {
        "basename": "Todo",
        "name": "Todo",
        "slug": "todo",
        "namespace": "Todo",
        "version": "1.0",
        "author": "Guillaume Batier",
        "license": "MIT",
        "description": "Todo list",
        "enabled": true,
        "order": 9001
    }`

empty your cache, 
and launch many commands 
`composer dumpautoload`
`composer clearcache`
`php artisan cache:clear`
`php artisan module:optimize`

for me it's works 24hours after my modifications.... 
I think it came from cache or something else
try to reboot apache maybe

**Comment by seem2810** [comment]
It doesn't work... 

The module is working now, but the route doesn't list.. (php artisan route:list)
I've restart apache, cleared the cache and so on.. 

My modules.json
{
    "dcm": {
        "basename": "dcm",
        "name": "Dcm",
        "slug": "dcm",
        "namespace": "Dcm",
        "version": "1.0",
        "author": "seem",
        "license": "MIT",
        "description": "some module",
        "enabled": true,
        "order": 9001
    }
}

Foldername: dcm

**Comment by thandonguocmo2020** [comment]
when error : 
change : config/path

**Comment by A-Lawrence** [comment]
@guillaume23 are you still having an issue?  I'm still unable to replicate, so any further information would be gladly received.  If you can make sure you format your code using full code blocks, that'd be great (video below)!

http://ss.7ux.co.uk/2016/12/323_1482195709.gif

**Comment by guillaume23** [comment]
@A-Lawrence 
Hi, I fixed it, i think it's a bug from the plugin after an update, so i just rename the module folder with the first letter in uppercase like todo => Todo and it works. 
Clear cache and optimize module and laravel it should works.

Bye

**Comment by kaidesu** [comment]
👍
