### ISSUE TITLE
Error in vendor:publish

### ISSUE THREAD

**Issue by nejtr0n** [caffeinated/modules#238]
Use command: php artisan vendor:publish
Copied Directory [/vendor/laravel/framework/src/Illuminate/Notifications/resources/views] To [/resources/views/vendor/notifications]
Copied Directory [/vendor/laravel/framework/src/Illuminate/Pagination/resources/views] To [/resources/views/vendor/pagination]
Copied File [/vendor/caffeinated/modules/config/modules.php] To [/config/modules.php]
Can't locate path: </home/a6y/docker/L5-clear/www/vendor/caffeinated/modules/src/../database/migrations/>
Publishing complete for tag []!

Error
Can't locate path: </home/a6y/docker/L5-clear/www/vendor/caffeinated/modules/src/../database/migrations/>

Clear laravel latest installation

**Comment by JayLancaster** [comment]
Im getting this error also.

**Comment by dimassrio** [comment]
look at #220  its the same problem, next time read all open issue first before submitting another issue.
