### ISSUE TITLE
Frontend and Backend strategy

### ISSUE THREAD

**Issue by fana605** [caffeinated/modules#24]
Hi,
What do you suggest in order to have Frontend and Backend Modules? Should I have a common controller, route file, middleware, etc? Maybe separate in diferent modules like blog and blogAdmin?

Thanks

**Comment by kaidesu** [comment]
There's no need to create a separate module to handle your blog admin functionality, simply create an `AdminController` and set up routes specifically for your blog module:

```php
Route::group(['prefix' => 'admin', 'middleware' => ['auth']], function() {
    Route::get('blog', [
        'as'   => 'admin.blog',
        'uses' => 'AdminController@index'
    ]);
]);
```

Then you'll be able to hit **http://example.com/admin/blog**. Just continue with this pattern~
