### ISSUE TITLE
php artisan migrate:refresh and migrate:rollback - undefined index

### ISSUE THREAD

**Issue by Skreci** [caffeinated/modules#240]
Hi,

When trying to run php artisan module:migrate:refresh or php artisan module:migrate:rollback it is working fine. However trying to run regular migrate:refresh or rollback causes an error.

[ErrorException]
  Undefined index: 2016_09_03_153652_create_gallery_table

Laravel 5.3
caffeinated/modules 4.0.2

**Comment by oceanhost** [comment]
Hey man, use $this->loadMigrationsFrom(DIR.'/../Database/Migrations', 'namefrommodule'); in your ModuleServiceProvider. :D
