### ISSUE TITLE
Can't locate path: </vendor/caffeinated/modules/src/../database/migrations/>

### ISSUE THREAD

**Issue by DeeJaVu** [caffeinated/modules#246]
Hello in `ModulesServiceProvider` you have this code,
```
$this->publishes([
            __DIR__.'/../database/migrations/' => database_path('migrations')
        ], 'migrations');
```

but when i run `artisan vendor:publish` i'm getting an error because, 
`vendor/caffeinated/modules/database/migrations/` doesn't exist..

please fix it.

**Comment by oceanhost** [comment]
Hey man, use  $this->loadMigrationsFrom(__DIR__.'/../Database/Migrations', 'namefrommodule'); in your ModuleServiceProvider. :D

**Comment by kaidesu** [comment]
This has been fixed~
