### ISSUE TITLE
make:module endless run in Step #1

### ISSUE THREAD

**Issue by Brotzka** [caffeinated/modules#255]
My project is running on Laravel 5.2.45 and I tried coffeinated/modules  v2.2.4 as well as v3.2.5 because of problems installing v4.0.7 (see issue #254).

Installation was no problem. But when I trie to create a new module with `php artisan make:module teams` it reruns Step #1 again and again until I stop the process. Here a small excerpt from the console output:

```
*-----------------------------------------------*
|                                                           |
|          Step #1: Configure Manifest          |
|                                               |
*-----------------------------------------------*

You have provided the following manifest information:
Name:        Teams
Slug:        teams
Namespace:   Teams
Version:     1.0
Description: This is the description for the Teams module.
Author:       
License:     MIT
*-----------------------------------------------*
|                                               |
|          Step #1: Configure Manifest          |
|                                               |
*-----------------------------------------------*

You have provided the following manifest information:
Name:        Teams
Slug:        teams
Namespace:   Teams
Version:     1.0
Description: This is the description for the Teams module.
Author:       
License:     MIT
*-----------------------------------------------*
|                                               |
|          Step #1: Configure Manifest          |
|                                               |
*-----------------------------------------------*

You have provided the following manifest information:
Name:        Teams
Slug:        teams
Namespace:   Teams
Version:     1.0
Description: This is the description for the Teams module.
Author:       
License:     MIT
......
```

Is there something I am doing wrong?

**Comment by illuminate3** [comment]
same as what I posted a while back: https://github.com/caffeinated/modules/issues/250

**Comment by illuminate3** [comment]
Just tired again for giggles. Steps taken:

1. composer clear-cache (lets make sure get new code)
2. composer global require "laravel/installer" (freshen our laravel)
3. larval new APPy
4. cd APPy
5. composer require caffeinated/modules
5.1. add classes to config
5.2 make app/Modules directory
6. composer dump-autoload (cause we all know this solves all of laravel's problems)
7. pa make:module test (pa: short cut for php artisan)
8. hit enter for ['no'] to continue and still get a chance to create another module

**Comment by kaidesu** [comment]
I'll take a look at this in the morning - I'm sure its a stupid bug. Sorry for the inconvenience and time this has been open for!

**Comment by kaidesu** [comment]
Wait... are you guys (@Brotzka & @illuminate3) are hitting **no** to the message asking to continue? That's the confirmation message asking if you'd like to actually create the module. It's asking to confirm that the information you provided is correct. Hit **Y** to actually create the module and the command will then exit.

Seems the message is unclear, so I can update that to make it more coherent?

**Comment by illuminate3** [comment]
Yes, I'm hitting "no" or just enter. However, I'm not even getting a module made. I can live with a bad message but no module is a let down.

**Comment by kaidesu** [comment]
Definitely will. Sorry for the confusion!
