### ISSUE TITLE
Modules View Composers

### ISSUE THREAD

**Issue by beeInteractive** [caffeinated/modules#256]
Hi!

I have created a Module and i'm trying to pass a data to all view (within the main layout) with the view composer method. But it doesn't seem to pass.. I got a "Undefined variable" exception when I call my variable. Here's what i got:

My module name is Frontend

In my Modules/Frontend/Providers folder, i'v created a ViewComposersServiceProvider file, and added the line in my config\app.php

Then, in this file, here's my boot() method:

```
View::composer('frontend::layouts.home', function($view) {
    $view->with('data', Seo::find(1)->first());
});
```

I'v tried different views path (Frontend::layouts.home, frontend.layouts.home) But none seems to be the right way..

I have my layouts files also in the same module folder, in the Resources/View folder.

Does anyone have an idea how to achieve this? Or a direction to take?
Thank you!

**Comment by A-Lawrence** [comment]
In my project, I have the following setup and it works:

**Method inside my ModuleServiceProvider**
```php
/**
     * Register the Visittransfer module composers.
     *
     * @return void
     */
    protected function registerComposers()
    {
        View::composer(
            ["visittransfer::admin._sidebar"],
            \App\Modules\Visittransfer\Resources\Viewcomposers\StatisticsComposer::class
        );
    }
```

**Call this method inside register()**
```php
public function register()
    {
        ...

        $this->registerComposers();
    }
```

**Comment by beeInteractive** [comment]
Hi!
Wonderful! It worked like a charm! thank you!
