### ISSUE TITLE
Using Modules  with Lumen

### ISSUE THREAD

**Issue by adrevol** [caffeinated/modules#257]
I would like to use  Modules  package  with Lumen.  Is it compatable?  If so  can someone please help me with it. 

Here is what I have given a try : 
1. Loaded  Modules Package 
2.  added  foundation helpers.php  to Lumen Project  

Getting the following  error

[ReflectionException]  
  Class path.public does not exist

**Comment by wowthemes** [comment]
I am running into the same issue with Lumen. Getting error 
`Call to undefined function app_path()` how to make it work wit Lumen

**Comment by kaidesu** [comment]
This has not been developed with Lumen in mind. Open to pull requests or suggestions though!
