### ISSUE TITLE
Laravel 5.3 validation errors are not persisted when redirect from one controller to another control in the same module

### ISSUE THREAD

**Issue by hungtruongquoc** [caffeinated/modules#260]
I have a controller to do the validation: 

`<?php

namespace App\Modules\Front\Http\Controllers;

use Illuminate\Http\Request;
use Illuminate\Support\Facades\DB;

use App\UserInfo;
use App\User;
use App\Http\Controllers\Controller;

class RegistratorController extends Controller{

  public function index(Request $request){
    $userInfo = new UserInfo;
    $userLogin = new User;
//    $request->session()->forget('firstname');
//    $_POST['firstname'] = null;
    $params = $request->all();
    $params['firstname'] = null;
    $request->replace($params);
    $this->validate($request, [
      'firstname' => 'bail|required|min:2',
      'lastname' => 'bail|required|min:2',
      'username' => 'bail|required|min:2',
      'password' => 'bail|required|min:5',
      'email' => 'bail|required|min:10',
    ]);
//    echo 'Valid input';
//    DB::beginTransaction();
  }
}
`
When the validation fails, the request is redirected to back to 'register' action of following controller: 

`<?php

namespace App\Modules\Front\Http\Controllers;

use Illuminate\Http\Request;
use \App\Group;
use \App\User;
use App\Http\Requests;
use App\Http\Controllers\Controller;
use Illuminate\Support\Facades\Log;

class IndexController extends Controller
{
  public function index()
  {
    return view('front::index');
  }

  public function about()
  {
    return view('front::about');
  }

  public function contact()
  {
    return view('front::contact');
  }

  public function accreditation()
  {
    return view('front::accreditation');
  }

  public function resources()
  {
    return view('front::resources');
  }

  public function registration(Request $request){
    $groups = Group::all();
    $usernames = User::all();
    Log::info($request->session()->all());
    return view('front::register', ['user' => null, 'groups'=>$groups, 'usernames'=>$usernames]);
  }
}
`

The line `Log::info($request->session()->all());` printed me a session array with no errors

**Comment by A-Lawrence** [comment]
@hungtruongquoc can I ask that when you post code in the future, you properly format it?  It'll make it far easier for us to read and diagnose.  You can do this by following the tutorial video below:

http://ss.7ux.co.uk/2016/12/323_1482195709.gif

It sounds like you're not properly starting your sessions.  Can you share your Module's routes file with us?  It'll be in `app/Modules/Front/Routes/web.php`.  Please make sure you format it with the backtick characters, as shown in the video.
