### ISSUE TITLE
Batch in migrations ignored on rollback

### ISSUE THREAD

**Issue by madebymouses** [caffeinated/modules#263]
For a module we've created several migrations. All these migrations got their own batch number. As soon as we preform a rollback the batch number is ignored and all migrations will be rolled back.

Also the order of the rollbacks on the migrations are wrong, as they are prefromed ascending while you'd expect descending.

**Comment by pauluse** [comment]
Posted the issue on my work account, anyhow, I created a PR for this issue #264
