### ISSUE TITLE
Can I safely not load this package in production?

### ISSUE THREAD

**Issue by DanVeira** [caffeinated/modules#267]
Hello!

This is a great package which will save me a lot of work, but I have a concern regarding performance, so my question is if I can manually register each individual module service and route providers. I don't like having the code search for modules every time so I think this is better. It works, but maybe I'm missing something?

This is what I'm doing:

- I'm checking the environment, if it's production I don't register the `Caffeinated\Modules\ModulesServiceProvider`, if it's development I register it so I can use the artisan commands.
- I'm manually registering every module service provider in the provider's array like this: `App\Modules\Administration\Providers\ModuleServiceProvider::class,`
- And finally registering the module's `RouteServiceProvider` like this so I don't need helper functions: `require base_path('app/Modules/Administration/Routes/web.php');`
- ...same thing for migrations, middlewares, etc...

It appears to be working, and I no longer need this package in production and it improves performance a tiny little bit. I can even remove it completely if I no longer wish to use it.

What do you think? Will this cause me problems?

**Comment by kaidesu** [comment]
I don't think that'd be a problem! I'd be interested to hear how this approach works out for you after being out in the wild for a while 😃

**Comment by mohamedsharaf** [comment]
there will be no problem i tried this before no issue 
good idea to check for development then register
