### ISSUE TITLE
Module order

### ISSUE THREAD

**Issue by fana605** [caffeinated/modules#27]
Hi,
Is there a way to set the loading order of the modules? Maybe a order option in the module.json file?
Something like this would work:

Modules.php:
```php
public function getByEnabled($enabled = true)
	{
		$data    = [];
		$modules = $this->all();
		$order = [];

		if (count($modules)) {
			foreach ($modules as $module) {
				if ($enabled === true) {
					if ($this->isEnabled($module['slug']))
						$data[] = $module;
						$order[] = $module['order'];
				} else {
					if ($this->isDisabled($module['slug']))
						$data[] = $module;
				}
			}
		}

		array_multisort($order, SORT_ASC, $data);

		return $data;
	}
```

module.json:

```json
{
	"name": "Pages",
	"slug": "pages",
	"version": "1.0",
	"description": "This is the description for the Pages module.",
	"enabled": true,
	"order": 0
}
```

**Comment by kaidesu** [comment]
At the moment there isn't, but I do see the need for the functionality. Thanks for the example, I'll take a look into getting this rolled in with the release of v1.0.

**Comment by fana605** [comment]
Hi,
Seems like the modules.stub file doesn't have the ```order: 1``` line in place. This way, new modules created by artisan module:make won't have that line in the json file.

**Comment by kaidesu** [comment]
It's optional and not needed by default. If it's not found, the package will automatically assign a loading order of `9001` to the module. This ensures that if you do set a module to load first (e.g. `order: 1`) it will be loaded before any of the others.

**Comment by illuminate3** [comment]
Just adding a note here:

1. can you add that to the codex? I just happened to read this and it made my day :smile:
2. adding the order to the json file helps but this is still not working ... edge case
```
Artisan::call('module:seed', [
	'manager'
	]);

$test = Artisan::output();
dd($test);
```

What happens is that all of the modules will be called when migrating or seeding.

**Comment by kaidesu** [comment]
Pretty sure you need to use:

```php
Artisan::call('module:seed', ['module' => 'manager']);
```

And yeah, I'll make note to add it to the documentation. I need to take a day or two out of schedule and just focus on bringing all the docs up to date.

**Comment by illuminate3** [comment]
Gonna try that call. Thanks!

@ default order
No, I was asking if I could set a module to "1' and not if your package could do that.
I just reread your comment above the one I added and just realized that you plainly stated that.

Trying to read and comprehend during hours when vampires walk the streets isn't the smartest thing to do. lol
