### ISSUE TITLE
Laravel 5.4 testing

### ISSUE THREAD

**Issue by gayanhewa** [caffeinated/modules#275]
Has anyone tried this with the new release ? Any known issues ?

**Comment by veelasky** [comment]
I've been using this on my laravel 5.4, there's no apparent breaking changes that i know of, and I've created a pull request to accommodate laravel 5.4. see #283

**Comment by kamaroly** [comment]
Do you know why it is not being autoloaded on laravel  5.4.18    ? for example I am not able to access the route.

**Comment by kamaroly** [comment]
@veelasky  is it version still working for you ? I am not able to use it for laravel 5.4

**Comment by veelasky** [comment]
@kamaroly Yes, it still working for me,, just make sure you correctly setup the directory structure, and your composer autoload section.
