### ISSUE TITLE
(dev-master 7ed243e) problems

### ISSUE THREAD

**Issue by illuminate3** [caffeinated/modules#28]
on route:clear

error

```
PHP Warning:  Uncaught exception 'ErrorException' with message 'require(/Kagi/Http/routes.php): failed to open stream: No such file or directory' in /Users/...app/Modules/Kagi/Providers/RouteServiceProvider.php:41
Stack trace:
```

do you need more info?

**Comment by kaidesu** [comment]
This was probably caused by aa38a7e9e7bb6c7d8725b4f52e24de0d3adc9614. The config namespace was changed from `caffeinated::modules` to just `modules`. You'll need to go through your existing modules `Providers/RouteServiceProvider.php` file and update the `config` call within the `map` method to:

```php
(config('modules.path')
```

So, for a "Blog" module, it would be:

```php
require (config('modules.path').'/Blog/Http/routes.php');
```

**Comment by kaidesu** [comment]
Also note that the config file is now referenced at `config/modules.php` rather than `config/caffeinated/modules.php`.

**Comment by illuminate3** [comment]
I deleted my auto_load_classmap.php and reran composer dump-autoload. Both composer update and php artisan commands come up with this error.

```
exception 'ErrorException' with message 'array_multisort(): Argument #3 is expected to be an array or a sort flag' in /Users/...vendor/caffeinated/modules/src/Caffeinated/Modules/Modules.php:264
Stack trace:
#0 [internal function]: Illuminate\Foundation\Bootstrap\HandleExceptions->handleError(2, 'array_multisort...', '/Users/...', 264, Array)
#1 /Users/...vendor/caffeinated/modules/src/Caffeinated/Modules/Modules.php(264): array_multisort(Array, 4, NULL)
```

The first error above was more likely on my side.

I haven't used a configuration file yet besides what was in the package.

**Comment by illuminate3** [comment]
I updated the package because I was having issues with the view facade. Views were being pulled from the main L5 resources directory instead of from the module.

**Comment by kaidesu** [comment]
How are you calling the module view?

Using `View::make('blog::index')` loads `app\Modules\Blog\Resources\Views\index.blade.php` for me.

**Comment by illuminate3** [comment]
That was one mistake. I had a feeling that it was something like that.
I used the welcome.blade as a test and worked.

At the moment, I'm stuck on
```
@extends('layouts.default')
```

As for the original error: I reverted back to dev-master#0da309... for now. I'm still trying to get my head around your package and L5 at the same time.

**Comment by illuminate3** [comment]
update on the views.
I used @extends('blog::layouts.default') and I solved my issues.

Thanks for the heads up!

**Comment by kaidesu** [comment]
Certainly, let me know of you run into anymore issues!
