### ISSUE TITLE
Laravel 5.2: No hint path defined for [modulename]

### ISSUE THREAD

**Issue by acccims** [caffeinated/modules#280]
I get the 
`No hint path defined for [modulename]` 
when i 
return view('modulename::method);

This happens when i deploy it in ubuntu server running nginx. But the module works fine in windows using xampp server. I tried config:cache...clear etc... even granted 777 permission to all the files. This issue came up recently when i was creating new modules. My previous modules are working fine. 

Can you please help me out with this? thanks

**Comment by getwes** [comment]
Im also having this issue.

**Comment by ntdorji** [comment]
Any solution to this issue?

**Comment by kj9933** [comment]
I am also getting same issue. Is there any solution?
