### ISSUE TITLE
Who can help me answer this question?

### ISSUE THREAD

**Issue by caoyuanlianni** [caffeinated/modules#288]
php artisan make:module:controller Wxmall IndexController

[ErrorException]           
Undefined index: basename

**Comment by oLDu67** [comment]
i think 
 you should add `"basename": "Article",` of part module info in storage/app/module.json.

For example my article module in storage/app/module.json

```
    "Article": {
        "basename": "Article",
        "name": "Article",
        "slug": "article",
        "namespace": "Article",
        "version": "1.0",
        "description": "This is the description for the Article module.",
        "id": 37359206,
        "order": 9001,
        "enabled": true
    },
```

**Comment by pankitgami** [comment]
You can run ` php artisan module:optimize `. It will automatically regenerate module.json file in storage/app

**Comment by kaidesu** [comment]
Yup - that'd be the easiest solution.
