### ISSUE TITLE
Composer's packages

### ISSUE THREAD

**Issue by mod3st** [caffeinated/modules#29]
Hey,

You created very interesteing way to create L5 modules.The only thing that I don't like is the necessity of keepeing all that modules stuff within the main app structure.

Why can't modules be like regular composer's packages?

**Comment by kaidesu** [comment]
You definitely could create a module as a composer package - this is just another means of accomplishing the task. I personally didn't want to create "modules" out of packages as I view modules being a part of a single application or ecosystem (a CMS or any large scale app for example) - not something that could be used for any PHP application as packages can be.

In short, I personally see modules (in the way that Caffeinated Modules presents them) as an extension to *your application*; wheres packages are a means to extend *Laravel* as a framework.

Hope this answers your question :relaxed:

Also, you're more than welcome to move the `Modules` directory wherever you like - just publish the provided config file and edit the path to wherever you like.

**Comment by illuminate3** [comment]
@mod3st 

I come from old school php3/4 days so, personally, I don't understand why many people want to push everything into packages. Added onto this, is the fact that there are so many different terms for the same thing.

For me:
Packages = a way to extend the framework / the overall app
Module = a way to extend functionality of the app
Widget = a way to extend the functionality of a function that is within the app

So:
Carbon, Sentry, Baum nested set = packages
news, photo galleries, forum = module
news ticker, twitter feed view = widget (however, widgets are really just mini modules)


But! that is just my opinion :-)
The awesome aspect of Laravel is that it is very able to accept both of our opinions :-)


@ general idea
Should a forum be a package or a full app in itself?

**Comment by mod3st** [comment]
Interesting division :)

Package - a set of re-usable code, maintained independently. That's all.
If you keep several similar apps, some of them provide the same functionality ('modules'), I see no reason why these functions would not be separated into packages.
The benefit is obvious - you keep the modue in one location, available for subsequent applications.

@ general idea
I don't know. As always, all depend on your needs, context..

**Comment by illuminate3** [comment]
I totally agree if the components are re-usable that they should be a package.
Hmmm, I guess why I am in favor of modules for what I do is because they are almost mini aps, which are similar to a "forum". Hence why I don't turn them into packages. But, they could be packages. I guess it all comes down to preference since many times the lines are very blurry.

yes, I agree. It's all context!
