### ISSUE TITLE
Is it possible to use hooks?

### ISSUE THREAD

**Issue by filtration** [caffeinated/modules#290]
For example, I have modules like so: polls, albums (pictures), now on my timeline I have hardcoded icons and javascript in my timeline:

<img src="https://i.gyazo.com/447094e2811283dbeb3c2757b7fb8a67.png">

I plan on creating modules, that won't installed by default, but because I have no idea how to append the partials from the modules folders to those folders I have no way to do it....

For example, this is my status partials in a timeline modules:

```
<div class="box profile-info n-border-top">
    <form action="{{ route('CreateStatus') }}" method="post">
        {{csrf_field()}}
        <textarea class="form-control input-lg p-text-area" name="status" rows="2" placeholder="Whats in your mind today?"></textarea>
        <div class="box-footer box-form">
            <input type="submit" value="submit" class="btn btn-azure pull-right">
            <ul class="nav nav-pills">
                <li><a href="#"><i class="fa fa-map-marker"></i></a></li>
                <li><a href="#"><i class="fa fa-camera"></i></a></li>
                <li><a href="#"><i class=" fa fa-film"></i></a></li>
                <li><a href="#"><i class="fa fa-microphone"></i></a></li>
            </ul>
        </div>
    </form>
</div>
```

So, is there a way with this package to add partials from another module to another module automatically?

**Comment by Cyber-host** [comment]
@filtration you can inject your partials by view composer

something like this

in view:
`@stack('my_stack_place')`

and for add:
```
// -> Factory $viewFactory

$viewFactory->composer('VIEWS.MY_VIEW', function (\Illuminate\View\View $view) {
                $factory = $view->getFactory();

                $factory->startPush('my_stack_place', 'HTML FOR INJECT');
            });
```
