### ISSUE TITLE
Registering module specific artisan commands

### ISSUE THREAD

**Issue by oleksandr-shubin** [caffeinated/modules#292]
Is it possible to register artisan command, specific for particular module inside this module?

1. I've created new Module
2. I've created command Module\Console\Commands\MyCommand.php

Now I want to register MyCommand not in App\Console\Kernel.php but inside module. 
How can I achieve this? (Same with schedules)

Thanks

**Comment by cracker182** [comment]
Hi,

I have tried the same. 
The solution for me was, that i added `\App\Modules\Sappassword\Console\Commands\testCommand::class` in `app\Console\Kernel.php`.

I hope it helpes you.

Greetings

**Comment by cracker182** [comment]
Even better:

on the top of `app\Console\Kernel.php`
make
```
use App\Modules\YOURMODULE\Console\Commands as YOURCOMMAND;

//...
protected $commands = [
    ...
    YOURCOMMAND\testCommand::class
    ];
```

**Comment by oleksandr-shubin** [comment]
cracker182, 

Thank you for your reply. That is exactly the way I do ( I mean your last message).
Your description is just more detailed with examples of code. 
Anyway my aim is to separate module as far as possible from the global scope.

**Comment by cracker182** [comment]
oh I'm sorry, it seems i missread your question.
sorry

**Comment by cesarga** [comment]
In case someone wants a more reusable solution, this is what I'm doing:

Extend _Caffeinated\Modules\Support\ServiceProvider_ with this method

```php
use ReflectionClass;
use Illuminate\Support\Str;
use Illuminate\Console\Command;
use Symfony\Component\Finder\Finder;
use Illuminate\Console\Application as Artisan;

// ....

    /**
     * Register a console file namespace.
     *
     * @param  string|array  $path
     * @return void
     */
    protected function loadCommandsFrom($path)
    {
        $namespace = $this->app->getNamespace();

        foreach ((new Finder)->in($path)->files() as $command) {
            $command = $namespace.str_replace(
                ['Providers/../', '/', '.php', ],
                ['', '\\', ''],
                Str::after($command->getPathname(), app_path().DIRECTORY_SEPARATOR)
            );

            if (is_subclass_of($command, Command::class) &&
                ! (new ReflectionClass($command))->isAbstract()) {
                Artisan::starting(function ($artisan) use ($command) {
                    $artisan->resolve($command);
                });
            }
        }
    }
```
_Inspired_ in [this one](https://laravel.com/api/5.7/Illuminate/Foundation/Console/Kernel.html#method_load).

Now you just have to base your module's service provider on it, and use it like so
```php
    /**
     * Bootstrap the module services.
     *
     * @return void
     */
    public function boot()
    {
        $this->loadCommandsFrom(__DIR__.'/../Console/Commands');

        // ...

        $this->loadTranslationsFrom(__DIR__.'/../Resources/Lang', 'namespace');
        $this->loadViewsFrom(__DIR__.'/../Resources/Views', 'namespace');
        $this->loadMigrationsFrom(__DIR__.'/../Database/Migrations', 'namespace');
        $this->loadConfigsFrom(__DIR__.'/../config');
    }
```

F or this specific example to work command files should be stored in _app/Modules/Namespace/Console/Commands_, where _Namespace_ is the module's name.
