### ISSUE TITLE
Undefined variable:  in laravel 5.4

### ISSUE THREAD

**Issue by PlaynowGames** [caffeinated/modules#293]
I try to call my view like this

$data = array(
            'name'  => 'Test',
            'email' => 'test@gmail.com'
        );

        return View::make('copas::posts.index')->with(compact($data));

my route 

Route::get('/', function () {
        return View::make("copas::posts.index");
    });

What's wrong?

**Comment by ChristianGiupponi** [comment]
`compact` do not need the `$` but need it as a string `compact('data')`
