### ISSUE TITLE
Wrong Seeder name with command

### ISSUE THREAD

**Issue by ChristianGiupponi** [caffeinated/modules#297]
If I use this command: `artisan make:module:seeder users UserSeeder` the file name that is generated if wrong, for some reason it add a `App/` prefix so the result is:

`App/UserSeeder.php`

I have noticed that the `App` is passed in `MakeSeederCommand@getPath` but I can't understand where it comes from.

**Comment by erenmustafaozdal** [comment]
I am getting same issue
