### ISSUE TITLE
Error when composer update

### ISSUE THREAD

**Issue by koray-mobven** [caffeinated/modules#30]
Hello,

I installed caffeinated and realized that it gives "exception 'ErrorException' with message 'array_multisort(): Argument #3 is expected to be an array or a sort flag' in /Applications/MAMP/htdocs/myproject/vendor/caffeinated/modules/src/Caffeinated/Modules/Modules.php:264" error when i try to use composer update command.

Is it a bug?

Thanks.

**Comment by illuminate3** [comment]
Same error I was getting.
I down graded to:
```
		"caffeinated/modules": "dev-master#0da309eb34c135bf08d270dc5c4166019934ed67",
```

It doesn't have the latest publish commands but ... it works.

**Comment by kaidesu** [comment]
f99dcec0524163d0bfbe48e382e44d49a1a79b42 should fix this issue; let me know if it clears things up for you two!

**Comment by illuminate3** [comment]
hmmm ...

updated to newest commit.

With and without the Modules directory (even just an empty directory) I pretty much get this error on php artisan

```
exception 'ErrorException' with message 'Undefined index: enabled' in /Users/.../l5/vendor/caffeinated/modules/src/Caffeinated/Modules/Modules.php:264
Stack trace:
```
Browser is just a white screen of death. I even have whoops enabled as per https://laracasts.com/discuss/channels/general-discussion/whoops-removed-from-laravel-5?page=4

**Comment by illuminate3** [comment]
So far so good on a clean install. Now I need to see if it works beyond "php artisan" :-)
