### ISSUE TITLE
How to set the call order of the modules

### ISSUE THREAD

**Issue by lucassmacedo** [caffeinated/modules#301]
I need to know that one module should be called after all others, because in it I have a route
`Route::any('{any}','PagesController@view')->where('any', '.*');`

If I call before, it overwrites the routes of the following modules

**Comment by kaidesu** [comment]
Set the `order` value within your module's manifest file~

**Comment by lucassmacedo** [comment]
Yes, but if new module is added, broken again.

**Comment by kaidesu** [comment]
The default order value for modules is `9001` - simply set your Page module with a higher order to maintain its position if you want to ensure that it's always last.
