### ISSUE TITLE
Routes not Working in production

### ISSUE THREAD

**Issue by lucassmacedo** [caffeinated/modules#302]
Hello! I`m deploy my application now and the routes not working! In localhost working perfectly, but i deploying in Forge + Digital Ocean (php 7.1 + laravel 5.4).
All modules are enabled, but in php artisan route:list doest not appear..

*** 
SOLVED

**Comment by lucassmacedo** [comment]
The error is going here
`    private function registerServiceProvider($module)
    {
        $serviceProvider = module_class($module['slug'], 'Providers\\ModuleServiceProvider');
        
        if (class_exists($serviceProvider)) {
            $this->app->register($serviceProvider);
        }
    }`
Its not find the ModuleServiceProvider..  i change the namespace of aplication..

'path' => app_path('Modules') => to 'path' => base_path('Modules'),
'namespace' => 'App\Modules\\' => to 'namespace' => 'Modules\\',

 And add "Modules\\": "modules/" to composer.json

**Comment by minasvisual** [comment]
i have the same error, how fix them?

**Comment by lucassmacedo** [comment]
@minasvisual php artisan module:optimize

**Comment by minasvisual** [comment]
Thanks
