### ISSUE TITLE
Execute function on enable() / disable()

### ISSUE THREAD

**Issue by rmit-s3546815-nicholas-zuccarelli** [caffeinated/modules#303]
Is there a way to make a module execute a function when it is enabled/disabled?

For example, when I call 
`Module::enable('blog');`
can I make the module execute a certain function? Same if I called Module::disable('blog'); ?

**Comment by kaidesu** [comment]
Events are fired when modules are enabled/disabled, allowing you to listen for these events and perform any action you wish within your application:

`$slug.module.enabled` and `$slug.module.disabled`, where `$slug` is the slug of your module. These events will pass through the module's manifest information.
