### ISSUE TITLE
InvalidArgumentException on install

### ISSUE THREAD

**Issue by assoft** [caffeinated/modules#31]
Laravel version: 5.0.1
html package added!

composer require caffeinated/modules
<code>
[InvalidArgumentException]
Could not find package caffeinated/modules at any version for your minimum-stability (stable). Check the package spelling or your minimum-stability
</code>

**Comment by kaidesu** [comment]
Now that Laravel 5 is released, you'll need to reference Caffeinated Modules with the `@dev` tag within your composer.json file until I get a stable 1.0 release out.

`composer require` doesn't seem to do this automatically.
