### ISSUE TITLE
Laravel 5.5 - will be compatible?

### ISSUE THREAD

**Issue by vertisan** [caffeinated/modules#313]
Question for the future - will the package be compatible with Laravel 5.5?

**Comment by shivampaw** [comment]
2nd this. Any ideas?

**Comment by kaidesu** [comment]
Certainly - and feel free to contribute and open a pull request!

**Comment by Litiano** [comment]
Hello @kaidesu https://github.com/caffeinated/modules/pull/329

**Comment by denisrocks** [comment]
@Litiano it works unless you change `pathMap` config. In that case `class_exists($serviceProvider)` in \Caffeinated\Modules\Modules::register-service provider return `false`.

**Comment by denisrocks** [comment]
For example, if you move your code to `src` directory as it described in  [restructure-your-modules](https://github.com/caffeinated/modules/wiki/Configuration#restructure-your-modules)

**Comment by Litiano** [comment]
@denisrocks Does this work with Laravel 5.4?

**Comment by denisrocks** [comment]
@Litiano Yes, it is. I've tried to fix but haven't had enough time to sort out the issue

**Comment by Litiano** [comment]
@denisrocks Try to run the "composer dump-autoload" command. It worked for me.

**Comment by denisrocks** [comment]
`composer dumpautoload --optimize` does the trick. It has been a part of [`php artisan optimize`](https://github.com/laravel/framework/blob/54aa18a4e8495c4b6902d9665ec9fa4d3a1f3d2e/src/Illuminate/Foundation/Console/OptimizeCommand.php#L57) command but it has been removed in laravel 5.5. I think it should migrate to `php artisan module:optimize` command now.

**Comment by Litiano** [comment]
@denisrocks I added composer dump-autoload to module:optimize command. See https://github.com/caffeinated/modules/pull/329

**Comment by Litiano** [comment]
We could move to abstract class GeneratorCommand in the handle method.
`
public function handle()
    {

        parent::handle();
        $this->info('Generating optimized autoload files');
        $composer = new Composer(new Filesystem());
        $composer->dumpAutoloads();
    }
`

What do you think, @denisrocks and @kaidesu ?

**Comment by denisrocks** [comment]
@kaidesu you should use `$this->composer->dumpOptimized();`

**Comment by denisrocks** [comment]
@Litiano you should use `$this->composer->dumpOptimized();`

**Comment by denisrocks** [comment]
There are 2 approach to solving the issue that I see.
1. Make `composer dumpautoload --optimize` command a part of caffeinated/modules
2. Assign the obligation to specify autoload information to user like
```json
"autoload": {
    "psr-4": {
      "App\\": "app/",
      "Admin\\": "modules/Admin/src/",
      "Blog\\": "modules/Blog/src/",
  }
```
The second approach seems to me the most adequate cause all responsibility of module restructure falls on the user. Here, it is as simple as a add kindly reminder to `php artisan module:optimize` command. Anyhow choice is @kaidesu

**Comment by Litiano** [comment]
@denisrocks 
`$this->composer->dumpOptimized();` no work.

  [ErrorException]
  Undefined property: Caffeinated\Modules\Console\Generators\MakeProviderComm
  and::$composer

Anxious awaiting a decision from @kaidesu

**Comment by kaidesu** [comment]
I added a few review comments to your pull-request before I saw the discussion here. I will take a look at things when I'm back at my computer tomorrow~

**Comment by Litiano** [comment]
@kaidesu please create a new version.

**Comment by nickurt** [comment]
@kaidesu Can you tag a new version with the Laravel 5.5-support ?

**Comment by ngugijames** [comment]
Some features of this package don't work on 5.5
e.g the `php artisan make:module` command fails with the following error
` Method Caffeinated\Modules\Console\Generators\MakeModuleCommand::handle() does not exist `

**Comment by Litiano** [comment]
@ngugijames use "caffeinated/modules": "dev-master" in your composer.json.
We are waiting for @kaidesu to create a new version.

**Comment by kaidesu** [comment]
Tagged release has been pushed!

**Comment by ngugijames** [comment]
Thanks
