### ISSUE TITLE
php artisan make:module:controller failing when Modules moved outside App namespace

### ISSUE THREAD

**Issue by pacilondo** [caffeinated/modules#315]
First, I wanted to say good job on the package. I installed it and I've been playing around for the past couple of days but I have noticed when trying to create a controller it was failing.
I have created my modules outside Laravel's default app folder. I have updated my modules.php config file so the namespace looks now like this `'namespace' => 'Modules\\'` and I made sure to add it to my composer.json to be autoloaded `"Modules\\": "modules"`.
So far, everything seems to be working fine. I even managed to create 2 modules already, just that when I want to create a controller, it runs out of memory.

With xdebug enabled, I get the following error 

`PHP Fatal error:  Maximum function nesting level of '256' reached, aborting! in ....../vendor/laravel/framework/src/Illuminate/Container/Container.php on line 687`

Without xdebug, I get the following error
`[Symfony\Component\Debug\Exception\FatalErrorException]
  Allowed memory size of 536870912 bytes exhausted (tried to allocate 100914 bytes)`

I have done a little investigation and I have noticed that it's looping on `vendor/laravel/framework/src/Illuminate/Console/GeneratorCommand.php` file when calling this class `qualifyClass($name)`.

For now, I'm creating my controllers manually but it'd be nice if I could with the command.

P.S: I'm using Laravel 5.4

**Comment by angujo** [comment]
Experiencing the same.

@pacilondo Were you able to resolve it?

**Comment by pacilondo** [comment]
No, I haven't resolved it. For now, I'm just create my controllers and move them around and change the namespace.

**Comment by SamoilenkoEvgeniy** [comment]
Hello! Any news for this issue? I have same error.

**Comment by pacilondo** [comment]
Unfortunately still nothing.

**Comment by Andrew-Shook** [comment]
@pacilondo , what command are you using that is causing the crash? is it crashing with make:module:controller or make:controller? Also, are you attempting to make a controller for the app or for one of your modules.

**Comment by pacilondo** [comment]
I'm using the command make:module:controller. I'm making the controller for one of my modules.
