### ISSUE TITLE
[enhancement] composer.json

### ISSUE THREAD

**Issue by illuminate3** [caffeinated/modules#32]
Could you / Are you thinking of adding the ability to let modules have their own composer.json files?
Which would also mean some way to automatically add Service Providers and Aliases to config/app.php or have the module be able to autoload them.

**Comment by kaidesu** [comment]
I'd like to do something like this for sure, maybe with v1.1 :+1:

**Comment by illuminate3** [comment]
That would be awesome!

**Comment by k4Zz** [comment]
Hey guys! I use https://github.com/wikimedia/composer-merge-plugin. Then just add

```
  "extra": {
    "merge-plugin": {
      "include": [
        "app/Modules/*/composer.json"
      ]
    }
  }
```
to your composer.json file in root. After that you can add composer.json to your modules. ;)

**Comment by kaidesu** [comment]
That's a pretty sweet find, @k4Zz. Thanks for sharing it!

I may close this and add a reference to this to the documentation for module composer support over trying to roll my own implementation.

**Comment by illuminate3** [comment]
I'll try to test this solution out later after work.

**Comment by kaidesu** [comment]
Tested this and it works beautifully. I've added documentation on this here: https://github.com/caffeinated/modules/wiki/Composer
