### ISSUE TITLE
Seeder class path wrong with wrong namespace

### ISSUE THREAD

**Issue by rutvij2292** [caffeinated/modules#321]
Hello,

When I run,
`php artisan make:module:seed [SLUG] [NAME]`

this command generates files in \Modules\ModuleName\Database\Seeds\App\SeedClassName.php

Code in SeedClassName.php

```
<?php

namespace App\Modules\ModuleName\Database\Seeds;

use Illuminate\Database\Seeder;

class App\SeedClassName extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        //
    }
}
```

I don't know why App is prefixed and created file in Database\Seeds\App <-- this is wrong file structure. 

Please take a look. Thanks.

**Comment by d8vjork** [comment]
See #316
