### ISSUE TITLE
where are models created for each module?

### ISSUE THREAD

**Issue by MaryamMoeindarbari** [caffeinated/modules#323]
Hello,I use your package in laravel, when I run the command "php artisan make:module [modulename]" there is no model folder to put models of module in it, what should I do?

**Comment by kaidesu** [comment]
That's up to you - generally I would create a `Models` directory to store them in - however, it's perfectly acceptable to place them at the root of your module.

However, I'd like to point out that this is a sign that you should read more into **namespacing**. There's an excellent article here: https://daylerees.com/php-namespaces-explained/
