### ISSUE TITLE
Translation Error

### ISSUE THREAD

**Issue by indowebdeveloper** [caffeinated/modules#324]
Hello.. i'm trying to using the translation from the modules but i get an error, here is the details

My Module Service Provider

`
namespace Thanatos\Modules\Invoice\Providers;

use Caffeinated\Modules\Support\ServiceProvider;

class ModuleServiceProvider extends ServiceProvider
{
    /**
     * Bootstrap the module services.
     *
     * @return void
     */
    public function boot()
    {
        $this->loadTranslationsFrom(__DIR__.'/../Resources/Lang', 'invoice');
        $this->loadViewsFrom(__DIR__.'/../Resources/Views', 'invoice');
        $this->loadMigrationsFrom(__DIR__.'/../Database/Migrations', 'invoice');
    }

    /**
     * Register the module services.
     *
     * @return void
     */
    public function register()
    {
        $this->app->register(RouteServiceProvider::class);
    }
}
`
I already create the translation inside my modules folder Resources/Lang with this structure
`
Modules > Invoice > Resources > Lang > id > index.php
Modules > Invoice > Resources > Lang > en > index.php
`
Both of them contain this 

`return [
	'product_name_label' => 'Nama Produk',
];`

and when i try to use it on views, 

`@extends('front.header')
@section('content')
    <div class="container">
        <div class="row">
            <div class="col-md-12 checkout-heading">
                <div class="col-md-4 product-img">
                    <small>{{trans(invoice::index.product_name_label)}}</small>
                </div>
            </div>
        </div>
    </div>
@endsection
@push('script')
@endpush`

It returns me an error like this
`Class 'invoice' not found (View: D:\webDev\bandingin\app\Modules\Invoice\Resources\Views\index.blade.php)`

anybody here facing a same issue ?

**Comment by chriskonnertz** [comment]
Hi,

`$this->loadTranslationsFrom(DIR.'/../Resources/Lang', 'invoice');`

Is this really your code or is it `__DIR__` in your code?

**Comment by mishbah** [comment]
add quote for `trans` helper
```php
{{trans('invoice::index.product_name_label')}}
```

**Comment by chriskonnertz** [comment]
Yep.
