### ISSUE TITLE
Question about the module manifest file

### ISSUE THREAD

**Issue by chriskonnertz** [caffeinated/modules#326]
Hello,

from the wiki https://github.com/caffeinated/modules/wiki , this is a valid manifest file:

```
{
	"name": "Blog",
	"slug": "blog",
	"version": "1.0",
	"author": "Author Name",
	"license": "MIT",
	"description": "Only the best blog module in the world!",
    "order": 100
}
```

It also says:

> name - A human-friendly name of the module. Not required.
> description - A description of the module. Not required.

So `name` and  `description` are optional.

However, in the method `getModuleInformation` in the class `ModuleListCommand` ( https://github.com/caffeinated/modules/blob/v4.2/src/Console/Commands/ModuleListCommand.php#L92 ) the `name` and `description` keys are accessed without a check if they exist. 

Is this right?

**Comment by chriskonnertz** [comment]
PS: I can also provide a pull request with a solution.

**Comment by kaidesu** [comment]
Good catch, a PR would be awesome~

**Comment by chriskonnertz** [comment]
Here it is: https://github.com/caffeinated/modules/pull/327

I am not sure about the difference between `name` and `basename`. In my `storage/app/modules.json` every module entry has the `basename` attribute but none has the `name`attribute. Does it makes sense to use the `basename` attribute as a fallback if `name`does not exist? (Here : https://github.com/caffeinated/modules/blob/v4.2/src/Console/Commands/ModuleListCommand.php#L92 )

**Comment by kaidesu** [comment]
Hmm, no - every module should have a `name` property. The `basename` attribute is used to scaffold namespace paths during file generation.

**Comment by chriskonnertz** [comment]
Ok.
