### ISSUE TITLE
Artisan Command  'make:module:model'   Undocumented

### ISSUE THREAD

**Issue by pixelskribe** [caffeinated/modules#332]
Just a note that the Wiki Documentation does not  indicate the availability of the generator `make:module:model [slug] [modelName]`  

https://github.com/caffeinated/modules/wiki/Artisan-Commands

**Comment by daveismyname** [comment]
I've added that to thw wiki. 

https://github.com/caffeinated/modules/wiki/Artisan-Commands#makemodulemodel-slug-name
