### ISSUE TITLE
Command "maker:migration" is not defined.

### ISSUE THREAD

**Issue by kevin1193** [caffeinated/modules#336]
When I run php artisan maker:module:migration  I encountered this issue [Symfony\Component\Console\Exception\CommandNotFoundException]
  Command "maker:migration" is not defined. Im using version 4.2.2

**Comment by umefarooq** [comment]
its make:module:migration or maker?

**Comment by kevin1193** [comment]
Its maker. It is the command when I run php artisan module. I think the make command is now replaced with maker.

**Comment by kevin1193** [comment]
I think the module version that I've installed is the 5.0 dev. Version 4.2.2 is working normally. Closing this issue.
