### ISSUE TITLE
module:make-migration Acme

### ISSUE THREAD

**Issue by illuminate3** [caffeinated/modules#34]
no error message, no log message,  no file ...
Looks like a bug

**Comment by kaidesu** [comment]
Hmm, did you try just running `module:make-migration Acme`? You need to supply the migration name after:

`php artisan module:make-migration Acme create_test_table`

With that, I'll be sure to take a glance over it to make sure everything is correct.

**Comment by illuminate3** [comment]
ugh, missed that!
Thanks
