### ISSUE TITLE
Add Kernel Middleware

### ISSUE THREAD

**Issue by Asoseil** [caffeinated/modules#35]
How can i add middleware in the kernel at runtime?

**Comment by kaidesu** [comment]
You can't. See this closed issue on the topic: #19

**Comment by kaidesu** [comment]
FYI, the ability to dynamically add middleware has been added to Laravel (though I dont think it's been pushed to a stable tagged release yet): https://github.com/laravel/framework/pull/7834#issuecomment-76901320
