### ISSUE TITLE
Wrap modules in parent directories such as: Admin/Modules, User/Modules, ...

### ISSUE THREAD

**Issue by waiylgeek** [caffeinated/modules#350]
Can we wrap modules in parent directories such as: Admin/Modules, User/Modules, ...?

**Comment by Zakintosh** [comment]
Hello i m struggling over using the --location feature so i can add Module under Platform folder as mentionned in my modules.php config file
'locations' => [
        'system' => [
            'driver'    => 'local',
            'path'      => app_path('Modules'),
            'namespace' => 'App\\Modules\\Platform\\',

I m getting module.json at Platform which is just a directory for me not a module

**Comment by kaidesu** [comment]
Please open a new issue with more information @Zakintosh
