### ISSUE TITLE
custom driver

### ISSUE THREAD

**Issue by athiffau** [caffeinated/modules#355]
I need to write a custom driver to support my multi-tenant site. I wrote a new Repository that extends the base repository (src/Repositories/Repository) that I called TenantRepository.php . 

config/modules.php was modified to set the storage driver as follows
` 'driver' => 'tenant' `

With TenantRepository.php placed in the vendor Repositories folder everything works as expected.

My question is how do I implement TenantRepository.php from app/Repositories instead of the vendor folder? 

Thanks

**Comment by Nowi5** [comment]
Hi Athiffau, nice to see somebody else working on multiple tenant application. I agree that seems to be not very transparent. When I had a look to the coding, you need to set modules.driver to custom and than set modules.custom_driver to your file. What a pity that the documentation is not good on that.
```

'driver' => 'custom',
'custom_driver' => 'App\Repositories\TenantRepository',
```

I hope that helps.

How do you store the information about a module for your tenants? 

To have a more configurable Module perspective at all, have you thought about to have the Module itself as a Model with additional attributes at the database? Of course this entry need to be cached, but I think having a description and the possibility enable/disable at UI makes sense.
I looking into the way to have the enable/disable depending on environment / database setting in a multi tenant application, means I would have depending on domain a module enabled or not.
Even if you say, a config on database level makes no sense for you, it would be great to have the option to overwrite different function by creating a own Service Provider by extending the default one.

Thank you for sharing your ideas and progress.

**Comment by Nowi5** [comment]
Are you willing to share your code? I think you added the FQND to the name of the file, right?

**Comment by athiffau** [comment]
Normally I don't mind sharing but right now I just don't have the time to pull the relevant code out of this big app I am working on.  For my implementation this is tied into the purchasing model since some of my modules are free and some must be purchased.

I don't change the file name though.  Instead, my approach was to override the optimize() and getCachePath() methods in my TenantRepository custom driver.  These functions are now tenant-aware and alter the path from which the json file is read/saved.

In my implementation, the tenants have their own file repositories in storage/tenants/<fqdn hash>. The TenantRepository driver simply ensures that the reads and writes are in the correct path.

Hope that helps.

**Comment by kaidesu** [comment]
Custom drivers should be easier to register in v5.0.0.
