### ISSUE TITLE
Module's Route Group prefix from module's config file

### ISSUE THREAD

**Issue by owency** [caffeinated/modules#357]
L5.6 - PHP 7.1

News Module:

**web.php:** 
```
$admin_prefix = config('posts.admin_prefix');
// dd($admin_prefix) == null

Route::group([
	'prefix' => $admin_prefix / config('posts.admin_prefix'), // Nothing set here
	'prefix' => $admin_prefix / config('app.name'), // This works fine...
	], function() {
		Route::get('/', function () {
			//dd(config('posts.admin_prefix')); - this == '/dashboard'
		});
		Route::resource('news', 'PostController');
	}
);
```

**config/posts.php**
`return [
	/**
	 * 	Specify the prefix for the admin dashboard
	 */
	'admin_prefix' => "/dashboard",`

Seems like the config file is loaded too late, I wondered if this was a laravel issue, but if I replace the config setting with `config('app.locale')` for example everything works fine.

Any ideas?

**Comment by arthvrian** [comment]
Hi

Move `$this->loadConfigsFrom(__DIR__.'/../config');` from `boot()` to `register()` in **ModuleServiceProvider**

I'm not sure if it's a good idea, but it worked
