### ISSUE TITLE
How To Call View in Controller

### ISSUE THREAD

**Issue by AleksandarVucenic** [caffeinated/modules#36]
Hi, I just start using this package and its cool. What I didnt figure out is how to call View in Controller I have folder structure App\Components\System on example and how to call view in controller and is it possible to view layout in Module extend a main laravel view layout master on example and how to do it I dont have any ideas more.

**Comment by illuminate3** [comment]
My structure is:
www   /app/Modules/ModuleName/

I use in my Controller located at /app/Modules/ModuleName/Http/Controllers/UsersController 

```
		return View('ModuleName::users.index');
```

In my views I just call:
```
@extends('app')
```
They are located at:
/app/Modules/ModuleName/Resources/Views/Users/index.blade


My default view is located in the normal laravel location:
/app/Resources/Views/app.blade
Which is nothing different than normal.

I hope this helps!

**Comment by TerrePorter** [comment]
Look in your app/Modules/ModuleName/Providers/ModuleNameServiceProvider.php

Should have a function called registerNamespaces, that is where the namespace is registered

```
protected function registerNamespaces()
	{
		Lang::addNamespace('AdminModule', __DIR__.'/../Resources/Lang/');

		View::addNamespace('AdminModule', __DIR__.'/../Resources/Views/');
	}
```

Then as @illuminate3  said you can access the views using the like  :
```
return View('AdminModule::users.index');
```
Provided the file exists at the path referenced in the above function
