### ISSUE TITLE
How to speed up the caffeinated?

### ISSUE THREAD

**Issue by dadopl** [caffeinated/modules#372]
I have 57 caffeinated  modules. Laravel is booting 2 seconds on a blank page without sql queries and not used any modules. After I disabled the modules self-booting takes 470 milliseconds (on blank page). Please help!

**Comment by kaidesu** [comment]
57 modules is quite a lot! It's likely caused by the various files being loaded by each module. Will need to do a deep-dive and see what I can refactor. Unfortunately I don't have any answers or solutions right now.

**Comment by kaidesu** [comment]
Not finding anything directly with the package that would be causing such large loading times. Scaffolding a vanilla instance of Laravel with 60+ modules, while does see longer load times, is only at around 200ms on my machine.

I would suggest taking a look at your modules and running benchmarks against them, and even disabling modules that may not be needed as 57 is a lot to load.

If you find out anything else, please do open a new issue, but for now I will be closing this~
