### ISSUE TITLE
Question: What does the ID value stand for?

### ISSUE THREAD

**Issue by chriskonnertz** [caffeinated/modules#373]
Hello,

this is a typical entry of the `storage/app/modules.json` file:

```JSON
    "Users": {
        "basename": "Users",
        "slug": "Users",
        "id": -717059347,
        "enabled": true,
        "order": 9001
    },
```

My question is: What is the meaning of the `id` property?

**Comment by kaidesu** [comment]
Nothing in particular - it's just a unique ID value as an additional means of identifying modules within your application.

**Comment by chriskonnertz** [comment]
Thank you! :)
