### ISSUE TITLE
[question] extend a module through another module

### ISSUE THREAD

**Issue by illuminate3** [caffeinated/modules#39]
I was wondering but having a feeling that you can't but anyways,

Is there any to extend a module based on another module?

For example, adding relationships: You start of with a typical user model but then decide to split out the blog functionality into it's own module. But you are left with the issue of adding the relationship back to the blog within the user module.

**Comment by kaidesu** [comment]
I believe what you want are polymorphic relationships.

**Comment by illuminate3** [comment]
Thanks, I'll look into them.
