### ISSUE TITLE
Route name is not recognize with artkonekt menu

### ISSUE THREAD

**Issue by lucasdidur** [caffeinated/modules#393]
I'm trying to create a dynamic menu by modules. But when i use the route name says that is not exists. I'm register menus in a service provider inside a module.

There is a way that I can use with both? 

```
$sidebar = Menu::create('sidebar', [
            'active_element' => 'link',
            'active_class'   => 'menu-open',
            'share'          => 'bulmaMenu'
]);
$sidebar->addItem('menu', 'Menu', ['route' => 'admin.overview']);
```

https://github.com/artkonekt/menu

**Comment by kaidesu** [comment]
could be that the module that defines the route you're specifying hasn't been loaded yet - module loading order matters in these instances.

You can specify the loading order of your "core" modules in the module manifest file to ensure they're loaded before everything else.
