### ISSUE TITLE
Laravel function actioin() 

### ISSUE THREAD

**Issue by AleksandarVucenic** [caffeinated/modules#40]
First I created Module "System" then "Administration" and when in any view in any module call action(controllerName@method) I get namespace of first onyl Module System (App\Modules\System\Http\Contrllers) 

Is there any way to change that or namspace or ti tis a bug

**Comment by kaidesu** [comment]
Yes, this was indeed a bug, and was reported here #37 and fixed in 93e81ce5e839ab15b6fa8b9a4b6463e121773270. I'll push a tagged release with this fix out now~
