### ISSUE TITLE
Call to undefined function studly_case()

### ISSUE THREAD

**Issue by UnderlineWords** [caffeinated/modules#404]
I get following errors while create a new module (Laravel 6);

* src/Console/Generators/MakeModuleCommand.php:149
* src/Repositories/Repository.php:125

```php
use Illuminate\Support\Str;

Str::studly();
```

edit: Fixed at [https://github.com/caffeinated/modules/pull/406](url)

**Comment by kaidesu** [comment]
Thanks for the PR :+1: Merged and released!
