### ISSUE TITLE
Question: How to manage Vue components inside the module folder?

### ISSUE THREAD

**Issue by dwarkeshsoni** [caffeinated/modules#412]
Hi, I'm trying to use Vue JS components that are stored directly in a module Resources folder (Resources/js/components).
I would rather not write for each Vue component its path in the main Laravel app.js file, so i'm thinking about editing the app.js files to scan Modules components folder and require each component automatically, but I'm not so good with the Vue JS enviroment.
Is there a simpler way to use Vue components inside modules folders?

**Comment by kaidesu** [comment]
You'd want to publish your module assets to your applications public directory :+1: process would be the same as package development: https://laravel.com/docs/6.x/packages#public-assets
