### ISSUE TITLE
laravel 5.8 not support

### ISSUE THREAD

**Issue by Alok77** [caffeinated/modules#416]
Problem 1
    - Installation request for caffeinated/modules ^6.1 -> satisfiable by caffeinated/modules[v6.1.0].
    - Conclusion: remove laravel/framework v5.8.37
    - Conclusion: don't install laravel/framework v5.8.37
    - caffeinated/modules v6.1.0 requires illuminate/support ^6.0 -> satisfiable by illuminate/support[6.x-dev, v6.0.0, v6.0.1, v6.0.2, v6.0.3, v6.0.4, v6.1.0, v6.10.0, v6.11.0, v6.12.0, v6.13.0, v6.13.1, v6.14.0, v6.15.0, v6.15.1, v6.16.0, v6.17.0, v6.17.1, v6.18.0, v6.18.1, v6.18.2, v6.18.3, v6.2.0, v6.3.0, v6.4.1, v6.5.0, v6.5.1, v6.5.2, v6.6.0, v6.6.1, v6.6.2, v6.7.0, v6.8.0].

**Comment by breakeryouko** [comment]
Use the v5.1.1 because later the laravel 5 support is removed
`"caffeinated/modules": "5.1.1",`
