### ISSUE TITLE
codex-facades: correction

### ISSUE THREAD

**Issue by illuminate3** [caffeinated/modules#45]
```
Module::getProperty('blog::description', 'This is a new description for the blog module.');
```

probably should be:

```
Module::setProperty('blog::description', 'This is a new description for the blog module.');
```

**Comment by kaidesu** [comment]
I'm in the process of transitioning all the documentation from Codex to the wiki system here on Github. The documentation for this specific issue has been updated. Thanks for pointing it out!

https://github.com/caffeinated/modules/wiki/Facade-Reference#modulesetpropertypropertyslug-value
