### ISSUE TITLE
json write issue with Facade method -- permission denied

### ISSUE THREAD

**Issue by illuminate3** [caffeinated/modules#46]
Trying to fire the enable/disable facades but get permission errors.

```
module:disable Profiles
```
Works, but 

```
Module::enable($module->name)
```
errors out.

Error:
```
file_put_contents(/Users/school/Sites/l5/app/Modules/Profiles//module.json): failed to open stream: Permission denied
```

I haven't tried changing and reverting permissions from my model/repository yet.

**Comment by torrentalle** [comment]
To allow enable and disable in run-time you shlowd change modules.json permissions.
In order to avois this situation could be interesting make a cached modules.json in storage path

**Comment by torrentalle** [comment]
Yo have to give write permissions to file modues.json

**Comment by illuminate3** [comment]
Thanks.

I was hoping that I could get away without changing permissions and do it on the fly like how artisan is able to do it.

**Comment by bgarrison25** [comment]
Recommend to close
