### ISSUE TITLE
The Facade method Module::exists($slug) allways return false

### ISSUE THREAD

**Issue by torrentalle** [caffeinated/modules#47]
The Facade method **Module::exists($slug)** allways return false
This happens because the method don't search by *slug*, the method check if module exists using directory basename.
This causes that I have to search modules converting **first letter to uppercase**

I  create a module with slug *blog*
````
vagrant@homestead:~/www/laravel5$ php artisan module:make blog
Module [Blog] has been created successfully
````

When I execute this code:

````
echo 'shoud return true, returns '.(Module::exists('blog')? 'true': 'false')."\n";
echo 'shoud return false, returns '.(Module::exists('Blog')? 'true': 'false')."\n";
````

I don't get the expected results:
````
shoud return true, returns false
shoud return false, returns true 
````

**Comment by torrentalle** [comment]
thanks, quick fix!

**Comment by kaidesu** [comment]
That's how I roll :sunglasses:
