### ISSUE TITLE
Not loading module config

### ISSUE THREAD

**Issue by mybigman** [caffeinated/modules#49]
Hi,

Doesnt appear to load module config files?

Module
--Config
---config.php
```
\Config::get('module::config');
```

thanks

**Comment by kaidesu** [comment]
Config files aren't registered by default for your modules.

Simply add the following to your module's main service provider's `registerNamespaces()` method:

```php
$this->mergeConfigFrom(__DIR__.'/../Config/config.php', 'moduleSlug');
```

And the usage would be:

```php
Config::get('moduleSlug.configItem');
```

I'll make note to update the documentation about this.

**Comment by mybigman** [comment]
@kaidesu thanks but whats going to happen if you have 10, 20 config files... its going to start getting messy.

```
$this->mergeConfigFrom(__DIR__.'/../Config/other.php', 'moduleSlug.other');
...
```

Why not have it scan the config directory and autoload them?

Thanks

**Comment by kaidesu** [comment]
I honestly don't see why you would have that many config files bundled with your module.

If you do, take a step back and look at how it can be simplified.

Also:

```php
$configFiles = ['config', 'lorem', 'ipsum'];

foreach ($configFiles as $config) {
    $this->mergeConfigFrom(__DIR__."/../Config/{$config}.php", 'moduleSlug');
}
```

You do not need to specify `moduleSlug.other` when registering a config file; just the namespace slug for your module.
