### ISSUE TITLE
view not found exception

### ISSUE THREAD

**Issue by hardikaecor** [caffeinated/modules#50]
Hi,
when I keep the view file in original L5 views directory it works fine
but if I move the module specific views to module's view directory
and use 
return view('messenger.index', compact('threads', 'currentUserId'));
it gives me error like:
View [messenger.index] not found.
Am I doing anything wrong here?

**Comment by TerrePorter** [comment]
Take a look at https://github.com/caffeinated/modules/issues/36 and see if it helps

**Comment by kaidesu** [comment]
Gotta reference your module's namespace when calling views from a specific module.
