### ISSUE TITLE
[bug] when update, a 'PHP Fatal error' occurred.

### ISSUE THREAD

**Issue by fanybook** [caffeinated/modules#51]
PHP Fatal error:  Can't use method return value in write context in /data/www/54mz.cn/web/vendor/caffeinated/modules/src/Caffeinated/Modules/Handlers/ModuleMakeHandler.php on line 171

<pre>
if ( empty($this->finder->files($folder)) && empty($this->finder->files($folder)) ) {
</pre>

**Comment by kaidesu** [comment]
Thanks for the report, I'll be looking into this issue.

**Comment by kaidesu** [comment]
This has been resolved in 1b8dfa981fecc1dde42cbc28eb50676cfc0580d7. Let me know if you run into any issues, and thanks for testing out the latest dev build!
