### ISSUE TITLE
Feature Request: module:make:controller Artisan command

### ISSUE THREAD

**Issue by danve** [caffeinated/modules#52]
I am (starting) using this package and I find useful so far. But I couldn't figure out how to create a resource controller with artisan into a module. 

Can someone have an idea? Thanks

**Comment by illuminate3** [comment]
If you're looking for Jeffery"s generator package like ability this doesn't have that ability but you could create your files with artisan + genrator package and then copy paste those files into the module. I've been doing that.

**Comment by umefarooq** [comment]
i have checked laravel 5 make:controller is not flexible as jeffery way's generators where you can define path in command while creating any controller, model or migration there should be path definition while making controller in L5 check this L4 modules package developer is reusing jeffer way's package for creating controller and other resources of module

https://github.com/creolab/laravel-modules/blob/master/src/Commands/ModulesGenerateCommand.php

**Comment by kaidesu** [comment]
@illuminate3 is correct, currently Caffeinated Modules does not provide the means to generate controllers for your modules.

I'll look into adding the functionality to do so and expand on what's already present; it's not something that's at the top of my list right now though. Until then, I'll leave this issue open and close it when I get around to it.

**Comment by danve** [comment]
thanks, I am doing already as illuminate3: artisan make controller, move to module and update the controler's namespace.
I thought might be there some undocumented method.
@kaidesu many thanks for your work

**Comment by puricamaykol** [comment]
You can use the artisan:make controller / model and specify the full scaped namespace of your controller / model, so there's no need to use any additional package or to move the generated file.

**Comment by kaidesu** [comment]
:+1:
