### ISSUE TITLE
Migrations ignore module ordering

### ISSUE THREAD

**Issue by kowalk** [caffeinated/modules#53]
I'd like to launch migrations in proper order (using module.json order property), and i doesn't work. I suggest you should read all migartions from all modules first then you should sort them by name and launch in proper order (not module by module like you're doing now).

**Comment by kaidesu** [comment]
Thanks for reporting this, I'll be sure to look into it.

**Comment by kaidesu** [comment]
Fixed in https://github.com/caffeinated/modules/commit/1d370ab368f87258840b587852b94b42a60a4838.
