### ISSUE TITLE
Feature Request: Publish module assets

### ISSUE THREAD

**Issue by illuminate3** [caffeinated/modules#54]
I thought I saw somewhere in the docs but ... I was wondering how or if it is possible to access per module "assets".

**Comment by kaidesu** [comment]
Ee, right now there isn't a means to publish module asset files through the package. Asset files simply need to be copied to your public directory in order to be accessible via your website.

**Comment by illuminate3** [comment]
OK.

This package is really coming together and I guess this would be a feature request then :smile_cat:

**Comment by kaidesu** [comment]
Now that I think about it (and have tested/used) there's actually no need for the package to publish module assets for you. This is something that Laravel comes with out of the box. It's the same process as you would do for a package as outlined here:

http://laravel.com/docs/5.0/packages#public-assets
