### ISSUE TITLE
make-migration return "Module [MODULENAME] does not exists" on all modules.

### ISSUE THREAD

**Issue by mschadegg** [caffeinated/modules#57]
When I try to make a migration for my modules with `php artisan module:make-migration MODULENAME TABLENAME`, I get following return `Module [MODULENAME] does not exist.` 

It happens on everyone of my modules. And yes, I am in the right directory.  

Last time I tried (a week ago), it worked perfectly. Maybe you have made an update lately, which has a bug?

**Comment by kaidesu** [comment]
No, no changes on this end that would have affected the migrate creation command. I just ran it on the latest checkout with no problems too:

```
php artisan module:make-migration foobar test
Created Module Migration: [Foobar] 2015_03_24_173838_create_tests_table.php
```

Did you by chance change any of your module's slug names within their manifest files? That was the only way I could re-create this issue.

**module.json:**
```json
{
    "name": "Foobar",
    "slug": "fozbar",
    "version": "1.0",
    "description": "This is the description for the Foobar module.",
    "enabled": true
}
```

```
php artisan module:make-migration foobar test
Module [Foobar] does not exist.
```

**Comment by mschadegg** [comment]
I'm pretty sure I use the right slug, and it happens on all my modules:

**Example:**

    php artisan module:make-migration TaskSystem tasks

Returns:

    Module [TaskSystem] does not exists. 

module.json:

    {
    	"name": "TaskSystem",
    	"slug": "TaskSystem",
    	"version": "1.0",
    	"description": "This is the description for the TaskSystem module.",
    	"enabled": true
     }

**Comment by mschadegg** [comment]
I found the problem.

You have changed the Modules class exists method, where you have added `$slug = strtolower($slug);`, so even though you changed it a month ago, I just ran `composer update` around a week ago.

**Comment by kaidesu** [comment]
Thanks, and sorry about that, I'll get it squared away. I'm working on getting tests written to avoid these issues, but it's a slow process due to the learning curve!

**Comment by kaidesu** [comment]
Ah, actually I remember why I did this.

Slugs should be all lower case, as it's a consistent format where the package doesn't need to rely on the user to know the exact slug formatting (e.g. capitalization) of the module they wish to work against. It also gives your application a means to sanitize/format user input before sending it off to minimize any errors.

Changing your slugs to all lowercase should fix the issue in this case.

**Comment by mschadegg** [comment]
Then you should ensure, that the slug is all lowecase, when creating a new module.

**Comment by kaidesu** [comment]
Noted. I'll be sure to update the package as needed to ensure all lowercase slugs.

**Comment by kaidesu** [comment]
Fixed in https://github.com/caffeinated/modules/commit/3191500092fc593a76eeb26bf381814ee9f8eb2a.
