### ISSUE TITLE
[Question] Demo module

### ISSUE THREAD

**Issue by tomzmtl** [caffeinated/modules#59]
Hi, I've been playing with the package for a couple days and I'd like to know if you have any demo/example/sample to provide, even something really basic.

I understand that you have constraints to provide a better fleshed-out documentation, so as a developer who is learning Laravel at the same time, I would benefit greatly to see a "real-situation" implementation.

My main concern at the moment is figuring out how to handle namespaces in a module context.

For instance, when creating a new Module Controller, should I use

```
use App\Http\Controllers\Controller
```
or
```
App\Modules\MyModule\Http\Controllers\Controller
```

Sorry if my issue is all over the place, I'm in the middle of the steep learning curve.
I appreciate what the package has been doing so far and find it's a good alternative to package development.

**Comment by kaidesu** [comment]
No worries! I'll do what I can to help out.

Namespaces can be a little confusing when starting out, but it'll "click" after a while of having to utilize them. To answer your question, you would use:

```php
namespace App\Modules\MyModule\Http\Controllers;
```

as the namespace for your module's controllers (you don't need to specify the actual controller within the namespace). I would check out this excellent article by Dayle Rees explaining namespaces to learn more about them:

http://daylerees.com/php-namespaces-explained

As far as an example module goes - I do have plans of creating one, I just haven't gotten around to it yet.

**Comment by tomzmtl** [comment]
Thanks for the feedback!
