### ISSUE TITLE
need some improvement in module:make-migration command 

### ISSUE THREAD

**Issue by umefarooq** [caffeinated/modules#60]
Hi i have just used you module:make-migration command its just creating migration for create table, once the project in production and want to update a module specific migration you will not rollback or refresh migration you can check laravel make:migration command you can create update table migrations too like

for creating user table
make:migration create_user_table --create=users

for updating user table
make:migration update_user_table --table=users

in  you command you are taking table name adding to string 

module:make-migration users users it will generate create_users_table

for update
module:make-migration users update_users it will generate create_update_users_table

i think make migration should follow the standards of laravel make command

**Comment by kaidesu** [comment]
D'oh! Thanks for pointing this out. I'll be sure to get this resolved.

**Comment by kaidesu** [comment]
Fixed in https://github.com/caffeinated/modules/commit/6e4a0f578becc351aae9cdbefd1a23a658efd2fe.
