### ISSUE TITLE
how to define routes in modules routes.php?

### ISSUE THREAD

**Issue by umefarooq** [caffeinated/modules#61]
looking for an example for defining route in module routes.php right now its just 

```php
Route::group(['prefix' => 'module'], function() {
	Route::get('/', function() {
		dd('This is the module index page.');
	});
});
```

how to define resource routes and controller routes.

**Comment by kaidesu** [comment]
The same way you would normally in Laravel.

http://laravel.com/docs/5.0/routing

The default namespace will be set to your modules `Http\Controllers` path. Example: you wouldn't need to type out the full path to your controller:

```php
Route::get('blog', 'App\Modules\Blog\Http\Controllers\BlogController@index');
```

But rather, you only need to reference the controller itself:

```php
Route::get('blog', 'BlogController@index');
```
