### ISSUE TITLE
How to use Helpers or Aliases in Modules and register Middles for Modules?

### ISSUE THREAD

**Issue by ducminhgd** [caffeinated/modules#62]
Hi Kaidesu,

I don't know how to use Helpers (such as: `redirect()`, `response()`) or Aliases (such as: `Session`, `Redirect`) in Modules? I meant just use as the default App, no need to use namespace.
And how to register Middlewares for Module, I don't want to use the same Middleware directory.

**Comment by kaidesu** [comment]
I would look into learning more about Namespaces before jumping into using this package, as you simply need to reference the correct namespace to use anything like `Session` and `Redirect`.

http://daylerees.com/php-namespaces-explained is an excellent primer.

Same thing with Middleware, refer to the Laravel documentation here http://laravel.com/docs/5.0/middleware. Simply create a Middleware directory within your module, and then register them.

**Comment by ducminhgd** [comment]
When I said *as the default App*, I meant register them as alias, no need to use theirs namespaces on controllers files.

Sorry if my question was not clear.

**Comment by ducminhgd** [comment]
Anh for middleware, I meant each module has its middlewares and its kernel file to register. 

P.S: I tried to use namespaces before I ask this question. And it works, I just find if there are any other solutions.

**Comment by kaidesu** [comment]
I would personally refrain from using aliases in that manner, but you should be able to do so by adding the following to your module service provider's `boot` method:

```php
$loader = \Illuminate\Foundation\AliasLoader::getInstance();
$loader->alias('Lorem', 'Path\To\Your\Class');
```

I haven't used this before so I can't say if it'll work or not.

And about the middleware, unfortunately you cannot register middleware from within your module - this is a limitation on Laravel's part the last I checked into it.
