### ISSUE TITLE
How to use lang?

### ISSUE THREAD

**Issue by jinhongjie007** [caffeinated/modules#65]
```php
public function index()
{
    $a = trans('cms::pagination.previous');

    dd($a);
}
```

I want to use the module language pack, but he doesn't seem to work,How to configure the needed?thank you

**Comment by kaidesu** [comment]
Within your module's primary service provider, within the `registerNamespaces()` method you'll find where the module's `Lang` namespace is registered.

By default it'll be looking within your modules `Resources/Lang` directory.

**Comment by jinhongjie007** [comment]
thank you , Has been resolved
