### ISSUE TITLE
localization

### ISSUE THREAD

**Issue by illuminate3** [caffeinated/modules#68]
I'm using the "mcamara/laravel-localization" package and was wondering about the json files and the possibility of them being translatable too?

I thought about have a db table for this but I'm still playing around with a few ideas.

**Comment by kaidesu** [comment]
I think it'd be possible with what's already provided. Within your module's manifest file, have the properties simply define a localization key:

```json
{
    "name": "blog::manifest.name",
    "slug": "blog",
    "version": "1.0",
    "description": "blog::manifest.description",
    "_etc": "..."
}
```

Store your translation/lang files with your module:

**app/Modules/Blog/Resources/Lang/en/manifest.php**

```php
<?php

return [
    'name'        => 'Blog',
    'description' => 'Write blog entries.',
];
```

**app/Modules/Blog/Resources/Lang/jp/manifest.php**

```php
<?php

return [
    'name'        => 'ブログ',
    'description' => 'ブログエントリを書きます。',
];
```

You'll need to verify that your module's are loading their own translation files if you wish to bundle them together: http://laravel.com/docs/5.0/packages#translations. This would be defined in your module's primary service provider.

Then simply use the `lang()` helper method to translate the manifest:

```php
$blogModule = Module::getProperties('blog');

echo lang($blogModule['name']);
```

**Comment by illuminate3** [comment]
Thanks, will give this a try.

Do you have anything in the pipeline like a "mcamara/laravel-localization" type of package?

**Comment by kaidesu** [comment]
Haha, no, I don't.
