### ISSUE TITLE
Routes not loading

### ISSUE THREAD

**Issue by tankerkiller125** [caffeinated/modules#69]
It seems that the routes are not loading for my project. My files look as such:

app/Modules/Default/Http/routes.php
```php
<?php

Route::get('/', function () {
    return view('welcome');
});
Route::get('/test', function () {
    return view('welcome');
});
```

app/Modules/Default/module.json
```json
{
  "slug": "default",
  "name": "Default App",
  "description": "Default Module strictly for testing!",
  "version": "1.0",
  "enabled": true
}
```

Thats all I have right now for testing purposes. Attempting to access it from `/test` or `/default/test` doesn't work and sends a 404 error.

**Comment by tankerkiller125** [comment]
Nvm... Instead of using the module:make command I failed to make it myself... My fault! Closing issue.

**Comment by kaidesu** [comment]
No worries!

Also I'm curious, when I tried creating a module named "Default", PHP threw a fit due to "default" being a reserved word (http://php.net/manual/en/reserved.keywords.php). Did you stick with the name "default" for your module here?

**Comment by tankerkiller125** [comment]
No I had to change it to test... I found that out myself. Didn't realize that default was reserved.

**Comment by kaidesu** [comment]
:+1:
