### ISSUE TITLE
A issue with the install.

### ISSUE THREAD

**Issue by worldmc** [caffeinated/modules#70]
Hello, 

so i recently got started with laravel and your modules, its a very nice way to work with a module setup, only im recieving a error:
```
Writing lock file
Generating autoload files

  [ErrorException]
  Undefined index: slug

Script php artisan clear-compiled handling the post-install-cmd event returned with an error

  [RuntimeException]
  Error Output:

install [--prefer-source] [--prefer-dist] [--dry-run] [--dev] [--no-dev] [--no-plugins] 
[--no-custom-installers] [--no-autoloader] [--no-scripts] [--no-progress] 
[-v|vv|vvv|--verbose] [-o|--optimize-autoloader] [--ignore-platform-reqs] 
[packages1] ... [packagesN]

E:\web\bitami\apache2\htdocs\MVC>
```

what i have done in order to try and fix this error:
clean install using composer,
ran a composer update, (just to be sure)
checked file acces for the php scripts. all fine there
tried several commands like module:make, module:create but artisan fails at anything i try. even php artisan --help.

What could cause this and how can i reslove it? 
link to laravel setup: https://github.com/TrackingTeam/MVC-Framework/tree/modular-rewrite
link to module code: https://github.com/TrackingTeam/MVC-Module

**Comment by kaidesu** [comment]
Hmm, I'm not sure off the top of my head - let me do a clean install and see if I can recreate the issue you're having.

**Comment by kaidesu** [comment]
I was unable to recreate the issue you're having. I'm guessing there's an error somewhere with your sample module - I would remove it and check to see if that resolves your issue with running `php artisan`. If so, try re-creating the module via `php artisan module:make sample`.

I also noticed the `composer.json` file you have bundled with your sample module is missing a comma (https://github.com/TrackingTeam/MVC-Module/blob/master/composer.json).

**Comment by kaidesu** [comment]
You should also pull in the stable `~2.0` version for Laravel 5.1, rather than `^1.0@dev`.

**Comment by worldmc** [comment]
updating the version for modules, from ^1.0@dev to ~2.0 fixed the issue. 

Thanks for the help.

**Comment by kaidesu** [comment]
:+1: Cool, glad you got things resolved~
