### ISSUE TITLE
routes module 404

### ISSUE THREAD

**Issue by TolotraRam** [caffeinated/modules#72]
Hi,

After a php artisan module:make test i was reaching a 404 when i try to access /test uri.

i'm running a fresh laravel 5.1

TY

**Comment by kaidesu** [comment]
I'm unable to reproduce this - please make sure you've followed the installation instructions correctly (and be sure to pull in ~2.0 for Laravel 5.1).

https://github.com/caffeinated/modules/wiki/Installation
