### ISSUE TITLE
how assign view in modules

### ISSUE THREAD

**Issue by khanhnam99** [caffeinated/modules#73]
how assign view in modules

**Comment by kaidesu** [comment]
Hmm, not sure if I fully understand what you're asking. Modules follow the same structure as Laravel itself does, so your view files for your module would go inside the `Resources/Views` directory.

All modules are registered and namespaced automatically as well, so to call a module's view file, you simply need to reference the module's registered namespace, which will always be the `slug` defined in your module's manifest file.

So, if you have a module called "Blog", the slug would be `blog`.

```php
$posts = array('lorem', 'ipsum');

// Will load app/modules/Blog/Resources/Views/index.blade.php
return view('blog::index', compact('posts');
```

Hope this answers your question!
