### ISSUE TITLE
How cal a model in modules , controllers in Laravel 5.1.x

### ISSUE THREAD

**Issue by khanhnam99** [caffeinated/modules#74]
1.How make model in controller with modules
2.How cal a model , where i create ?
pls help me
thanks

**Comment by UnderlineWords** [comment]
You can create your models in app/modules/{your_module_folder}/. (or anywhere your modules folder)

Model;
```php
<?php 
// Blog Model (app/modules/Blog/Blog.php)
namespace App\Modules\Blog;

class Blog extends Model {

}
```

Controller;
```php
<?php
// Blog Controller (App/Modules/Http/Controllers/BlogController.php)
namespace App\Modules\Http\Controllers;

class BlogController extends Controller {

}
```

I hope this help you!

**Comment by kaidesu** [comment]
Please see my response to your other ticket [here](https://github.com/caffeinated/themes/issues/14#issuecomment-115096895).
