### ISSUE TITLE
Multiple Domain Module Control

### ISSUE THREAD

**Issue by c0m3nk** [caffeinated/modules#76]
I make project that have multiple domain, sample: pemda.localhost.loc and disdik.localhost.loc
now I have a module with name kiosk
my question is: 
how to make kiosk is enable for pemda.localhost.loc and disable for disdik.localhost.loc
if I do Module::disable('kiosk') the module will disable for both domain.
or
it is possible to add ability to doing like this
```
{
    "name": "Kiosk",
    "slug": "kiosk",
    "version": "1.0",
    "description": "This is the description for the Kiosk module.",
    "enabled": [
    	"pemda.localhost.loc",
    	"other.localhost.loc",
    ],
    "disabled": [
    	"disdik.localhost.loc",
    ],
}

Module::disable('kiosk', 'disdik.localhost.loc');
Module::enable('kiosk', 'pemda.localhost.loc');
Module::enable('kiosk', 'other.localhost.loc');
```

**Comment by kaidesu** [comment]
At this time I have no plans to implement such functionality and I probably never will. It isn't the package's responsibility to manage or even be aware of the domain that it's on. This is something you should build within your application to manage.

**Comment by c0m3nk** [comment]
I do fix this on myproject.
may I clone your repo to add functionality like that.. maybe someone have issue like me.

**Comment by kaidesu** [comment]
Of course you may~ :+1:
