### ISSUE TITLE
Performance issue

### ISSUE THREAD

**Issue by chriskonnertz** [caffeinated/modules#77]
Hello,

I am using 38 Caffeinated\Modules in  a Laravel 5.1.x project (has been https://github.com/creolab/laravel-modules with Laravel 4.2 in the past). The performance is really bad. Up to 5 seconds to load a route! Route cache is enabled. 

Is there something I can do to decrease the execution time? My development system is slow however 5 seconds are too many.

Regards

**Comment by kaidesu** [comment]
Thanks for the report on this, I'll definitely take a look into it. Off the top of my head, the culprit is probably due to the fact that the package scans the defined module directory on _every_ page load to look for modules (and then loads them). I'll implement caching for that and then run some benchmarks to open up any other possible bottlenecks.

**Comment by chriskonnertz** [comment]
Wow, thanks!

**Comment by kaidesu** [comment]
Give v2.1 a shot, some bottlenecks were opened up so you should see some faster load times. Caching will be implemented soon~

**Comment by chriskonnertz** [comment]
Hey nice. But now I exceptions. Example:
`InvalidArgumentException in FileViewFinder.php line 112:
No hint path defined for [contact]`
From the stack: `at View::make('contact::form', array())`
I guess the problem is that it's requesting 'contact' instead of 'Contact', right? Seems like somethink changed about case sensitiveness.

**Comment by chriskonnertz** [comment]
Well that's not the point, 'Contact' doesn't work either.

**Comment by chriskonnertz** [comment]
It does make sense, because I call this before:
`View::addNamespace('contact', realpath(__DIR__.'/../Resources/Views'));`

**Comment by chriskonnertz** [comment]
It's not loading the server provider of the module. (Or not calling its `register`method.)

**Comment by chriskonnertz** [comment]
If I open `Caffeinated\Modules\ModulesServiceProvider`, set $defer to false, delete `bootstrap/cache/services.json`, replace line 48-50 with only `$this->app['modules']->register();` I don't get the exception any more - but a blank page.

**Comment by kaidesu** [comment]
This is probably due to the same issue as reported in #81. I'll have a patch for it here shortly.

**Comment by kaidesu** [comment]
Give the latest update a try when you get the chance.

Sorry for the inconvenience in advance~!

**Comment by chriskonnertz** [comment]
No problem.

However, I still get the same error: `No hint path defined`

**Comment by chriskonnertz** [comment]
But: If I  I open `Caffeinated\Modules\ModulesServiceProvider` and set `$defer` to `false`- then it's working now!

**Comment by chriskonnertz** [comment]
Also, the performance seems to be better now, even with `$defer` set to `false`: ~2 seconds instead of 5!

**Comment by chriskonnertz** [comment]
Nevertheless I keep asking myself why I get this error when the service provider is deferred? When doing your own test, do you create routes in `app/Htpp/routes.php`?

**Comment by kaidesu** [comment]
No, I don't. Did you run `php artisan optimize` after updating by chance?

**Comment by kaidesu** [comment]
Also, the service provider is set to `false` by default (https://github.com/caffeinated/modules/blob/master/src/Caffeinated/Modules/ModulesServiceProvider.php).

Maybe try doing a fresh re-install of the package?

**Comment by kaidesu** [comment]
Also, going to close this now since the performance has been improved. If you continue having issues with anything, don't hesitate to open a new ticket!

**Comment by chriskonnertz** [comment]
> Also, the service provider is not set to be deferred. That was a mistake I made in the first version of 2.0.

Okay. Sorry, seems like I got hurdled with some "composer caching". My bad.

Yeah it's okay to close this, performance has been improved and everything is working fine now, thanks!

**Comment by kaidesu** [comment]
No worries man, glad everything is going smoothly now.

:+1:
