### ISSUE TITLE
Clean up Artisan commands

### ISSUE THREAD

**Issue by kaidesu** [caffeinated/modules#79]
Need to go through and update them all to make use of the new Artisan command structure shipped with Laravel 5.1.

**Comment by illuminate3** [comment]
Just was finally going to make a comment about this :smile: 

```
      module:migrate:rollback
```

I was thinking that it would be better as:

```
      module:rollback
```

reasoning: "rollback" is pretty specific to migrations and the term "migration" can be inferred. Besides, I type it too mush :wink:
