### ISSUE TITLE
Module Routes Not Working

### ISSUE THREAD

**Issue by Tesha-E** [caffeinated/modules#81]
I have completed the installation to the letter. I have created a module called blog using the command but I still get a NotFoundHttpException.I am using laravel 5.1.

**Comment by raysmithdev** [comment]
Il have a quick look for you.

**Comment by UnderlineWords** [comment]
+1... All module routes not working after 2.1.1 update

**Comment by oidnus** [comment]
Temp fix for developer. Not use in production. Put in app/Http/routes.php

```
foreach (Module::enabled() as $module){
    $file = 'app/Modules/'.$module['name'].'/Http/routes.php';
    if (file_exists($file)){
        include $file;
    }
}
```

**Comment by kaidesu** [comment]
This is a legit bug, I've found the issue and will be patching it here very shortly.

**Comment by kaidesu** [comment]
Please give `v2.1.2` a try. If you have modules already present, you'll need to run `php artisan optimize` in order for Laravel to become aware of your module classes.

The `optimize` command is ran automatically now when creating a new module through the package.

**Comment by UnderlineWords** [comment]
Thanks @kaidesu for your quick response and update. It works now!

**Comment by kaidesu** [comment]
:+1:

I'll wait for others here to chime in before closing this~

**Comment by Tesha-E** [comment]
Thanks @kaidesu, the laravel newbie is happy now.
