### ISSUE TITLE
[v2.1.4] ErrorException array_reverse() by migrate:refresh ...

### ISSUE THREAD

**Issue by nickurt** [caffeinated/modules#86]
After #85 & upgrade to 'v2.1.4'

    php artisan module:migrate:refresh

    [ErrorException]                                               
    array_reverse() expects parameter 1 to be array, object given

**Comment by kaidesu** [comment]
Sorry about that - I need to strap down and write unit tests to keep these issues from popping up.

`v2.1.5` contains the patch for this issue~
