### ISSUE TITLE
[Dependency Management] Migrations not run in correct order

### ISSUE THREAD

**Issue by rasmusdencker** [caffeinated/modules#88]
Migrations are not run in the correct, date-sorted order. If modules are interdependent and uses foreign key constraints, their migrations will fail because they are run in a (seemingly) random order. 

Migration files should be indexed, sorted by date and then run.

<img width="194" alt="screenshot" src="https://cloud.githubusercontent.com/assets/4710999/8658413/e061398a-29a3-11e5-8ea5-75311e878a1d.png">

**Comment by kaidesu** [comment]
Migrations are ran independently of other modules intentionally. I don't believe [module] migrations should be indexed and lumped together. This is why every module has a loading order property (`order`). This really boils down to dependency management.

I'm playing around with the thought of adding a new `dependsOn` property where you simply list the module (or modules) that the module depends on (that should be loaded first). This would replace the `order` property altogether if implemented correctly.

**Comment by dondencker** [comment]
That's a good point, actually. A simple solution could be adding an `--order-by-date` flag to the module:migrate command.

**Comment by alnour-altegani** [comment]
+1 for module dependences , did you finished this future or not ?

**Comment by cyrilmarois** [comment]
sure it could be usefull !

**Comment by gerardreches** [comment]
Yeah, this could be so useful. Any progress on this?

**Comment by kaidesu** [comment]
None yet so far - I've implemented this functionality in my Bonsai package though so it just needs to largely be migrated over.
