### ISSUE TITLE
Create Database based ModuleRepository 

### ISSUE THREAD

**Issue by denistorresan** [caffeinated/modules#89]
Hi,
many thanks for this fantastic package, it's very useful.

I found an improvement that can be useful: a Database repository implementation.
Actually there's only Local/ModuleRepository class, that modify modules.json file.
In some cases, where modules are on GIT repo, there's the problem that enabling / disabling some modules, the modules.json file is overwritten (and may create conflicts to git).

How complex is to put enable / disable flag (or other settings) on db or an external file outside application?
If you help me, I can do it than I'll pull a request with the new implementation.

Thanks!
Denis

**Comment by kaidesu** [comment]
Right, I recently updated the package to extract things out to repositories to tackle this very issue. I have plans of adding the ability to store information in the database but I don't have a time frame of when it'll happen at the moment.

In theory, one would only need to create a new repository implementing the `ModuleRepositoryInterface` class and create a config option to choose which repository to use (local or database) and bind it.

I'm always open to pull requests!

**Comment by denistorresan** [comment]
Thank you!
About the right point to modify, in order to load the right class, what's your suggestion?
I think we can modify the RepositoryServiceProvider->register binding another class?

In this way, we can create a conf with an external ModuleRepository (outside caffeinated package).

My suggestion is:

1) modify modules.php adding:
'module_repository_class' => 'Caffeinated\Modules\Repositories\Local\ModuleRepository'

2) Modify RepositoryServiceProvider->register to bind that class to the ModuleRepositoryInterface

3) We can implement wherever also outside package and re-define 'module_repository_class' in the app/config/modules.php


Let me know what you think about this approach.

Ciao!
Denis

**Comment by denistorresan** [comment]
So, following my approach, I made this changes:

1) Add to src/config/modules.php:

`'module_repository_class' => 'Caffeinated\Modules\Repositories\Local\ModuleRepository'`

2) Modify src/Caffeinated/Modules/Providers/RepositoryServiceProvider.php:

```
	public function register()
	{
		$this->app->bind(
			'Caffeinated\Modules\Repositories\Interfaces\ModuleRepositoryInterface',
			config('modules.repository_class')
		);
	}
```

3) Now, I can define a different repository class, and also implement my own repository class outside the package (IE: in my case I need something specific for my app that read from an external file).

What you think?

If this fix is ok for you, I can pull a request to your repo

**Comment by kaidesu** [comment]
Got ya covered man, simply pull in [v2.1.6](https://github.com/caffeinated/modules/releases/tag/v2.1.6) and you'll be good to go~

**Comment by denistorresan** [comment]
hey!
Many thanks!! I checked out and it works perfectly!

cheers,
denis

**Comment by kaidesu** [comment]
:+1:
