### ISSUE TITLE
Allow multiple locations & namespaces for modules

### ISSUE THREAD

**Issue by tomicakorac** [caffeinated/modules#92]
Hi, I was wondering if you would consider adding support for multiple locations and namespaces for modules. Would that be too much of an overhaul, and generally do you consider it a good idea?

**Comment by kaidesu** [comment]
I have been considering adding this functionality - it's been at the top of my list of things to do, actually. I don't have a time frame of when I'll get to it, but hopefully in the next month or so~ I'll leave this ticket open in the meantime for any discussion on the matter to continue.

**Comment by samwilson** [comment]
+1

**Comment by hierarchy-id** [comment]
yeah, multiple locations will be nice

**Comment by UnderlineWords** [comment]
+1

**Comment by mohamedsharaf** [comment]
+1

**Comment by mohamedsharaf** [comment]
@kaidesu 
any news about this 
if u have any code done in this please push as i need to work in same thing and i dont need to make separate package i can help in this 

or if u have any guide or idea will u handle this just through custom repository any suggestion will be appreciated

**Comment by mohamedsharaf** [comment]
after thinking i have idea 

    'groups' => [
        'Base'=>[
            'path' => base_path('Company'.DIRECTORY_SEPARATOR.'Base'),
            'namespace' => 'Company\Base\\',
        ],
        'Modules'=>[
            'path' => base_path('Company'.DIRECTORY_SEPARATOR.'Modules'),
            'namespace' => 'Company\Modules\\',
        ],
        'Themes'=>[
 // i like to treat theme as modules
            'path' => base_path('Company'.DIRECTORY_SEPARATOR.'Themes'),
            'namespace' => 'Company\Themes\\',
        ],
    ],

**Comment by kaidesu** [comment]
@mohamedsharaf feel free to fork and experiment!

The groups idea is a good start~ 👍

**Comment by fulopattila122** [comment]
Hello, loosely related to this: In case I'm willing to have modules as separate independent repositories/composer packages, what would be the recommended way? (just the major lines)

**Comment by kaidesu** [comment]
@fulopattila122 I've been thinking about that, and believe it to be a separate feature all on its own that I would like to add. If you want to create a new issue for such a feature, it'll help consolidate discussion and brainstorming efforts to making it happen~

**Comment by GhulamJafar** [comment]
Need help, How can i manage the common assets for all modules. Like i have admin theme, so i want central location of my assets(css,js,images etc) for all admin modules.

**Comment by darron1217** [comment]
@kaidesu So how's this issue going?

**Comment by kaidesu** [comment]
Better late than never, but this has been implemented in v5.0.0!
