### ISSUE TITLE
Use git submodules to use the modules in many projects

### ISSUE THREAD

**Issue by alnour-altegani** [caffeinated/modules#93]
do you use git submodules if you want to use laravel module in many projects ?
or what is your work flow when you develop your applications modules ?

**Comment by coding-sunshine** [comment]
I would prefer to make a composer package if I am going to use a module in multiple projects.
Git submodules are not that efficient as per me.

**Comment by kaidesu** [comment]
I don't. Normally I'll just zip modules up in an archive and simply unzip them in other projects. Nothing else really to it - it's ultimately up to you how you wish to distribute your modules.
