### ISSUE TITLE
You need to add psr-4 in your composer.json

### ISSUE THREAD

**Issue by ghprod** [caffeinated/modules#96]
Hi, docs for configuration or installation lack of info that you need to add path to modules as psr-4 autoload in composer.json

Thanks

**Comment by kaidesu** [comment]
You do not if you use the default module path, as they would be contained within the `app` directory, which is already autoloaded.

You only need to add it to your PSR-4 autoload list if you move the module path outside of `app`. This is stated in the documentation.
