### ISSUE TITLE
Question: Is there a place to set global route prefix?

### ISSUE THREAD

**Issue by justinmoh** [caffeinated/modules#98]
I think this is not a caffeinated/modules specific question but more toward Laravel.

Previously because all the routes are defined in a single file, we just use 
`Route::group(['prefix' => 'v1'], function ()`
to wrap up our routes, then it become like a global prefix for our application.

Now that routes are defined in separate files, if we would like to change `'prefix' => 'v1'` to `v2`, we will need to do it in every route files?

**Comment by kaidesu** [comment]
Yes, or you could create a config file to store that in - you should be able to use the `config()` helper method within your route files to access config items~

**Comment by justinmoh** [comment]
Ah, good idea. A variable rather than a string constant.
Thank you.
